### ISSUE TITLE
navigator.xr.isSessionSupported promise not working in chrome 81

### ISSUE THREAD

**Issue by stanlyjohn2** [immersive-web/webxr#1000]
**navigator.xr.isSessionSupported** promise not working in chrome 81. did anyone else faced this issue? Is it a chrome issue?
The promise is in pending state.

**Comment by toji** [comment]
This isn't a good forum for help with a particular browser's implementation. I'd suggest that you file a bug on https://crbug.com and include a few additional details about the hardware you're testing with, if it was working correctly previously or with a different browser, and (if possible) the page you're seeing the issue on. We'll be able to track the issue much better from there.
