### ISSUE TITLE
Cancelling a pending session request

### ISSUE THREAD

**Issue by iBicha** [immersive-web/webxr#1007]
The specification does not describe a way to "cancel" a pending session request.

It is possible for a session request to become irrelevant, for different reasons or based on certain conditions.

An example of this is a multiplayer experience, where it does not make sense to start an immersive session if the other user has disconnected.

Another use case is where the UI (to explain the immersive nature of a session, and what data is exposed, with the option to proceed or cancel) is not a fullscreen overlay, but a less intrusive pop-up, allowing the user to "ignore" the UI. This would lead to a session request that is never resolved nor rejected, staying at a "pending state" indefinitely.

The application should be able to cancel a pending session request when appropriate, to ensure a good user experience.

**Comment by toji** [comment]
I understand the concern here, but I'm not convinced that it's something we can implement without breaking the API at this point. Cancellable promises are a topic with a long and messy history that the web platform has (AFAIK) given up on, and all the same reasons that made it a hard problem would apply here as well. When you make the session request (and the user OKs any consent dialogs that are needed) the hardware side of things starts spinning up immediately, is usually pretty brief, and there's typically not a good way to interrupt it. The best you can do it wait for the initialization process to finish and then immediately close it down, which is something that the page can handle just about as well as the UA can. The difference in timing and overhead will be minimal.

**Comment by iBicha** [comment]
I agree that cancellable promises might or might not be the way to go, I'm really open for suggestions, but the session initialization step (from request to final step) is potentially long and complex, and might contain multiple steps that include user actions (the spec actually have a good example of this)

https://immersive-web.github.io/webxr/#initialize-the-session

> Note: Some devices require additional user instructions for activation. For example, going into immersive mode on a phone-based headset device requires inserting the phone into the headset, and doing so on a desktop browser connected to an external headset requires wearing the headset. It is the responsibility of the user agent — not the author — to ensure any such instructions are shown.

Going through all these steps, to find out the session is "expired" according to the application (even if the session does succeed) can be pretty disappointing.

What I'm suggesting is a way to signal to the UA that the pending request is no longer desired, and any initialization steps should cancelled, if possible (of course, if the hardware is already spinning and so on, it's up to the application to cancel said session, and explain to the user why)

**Comment by toji** [comment]
The editors have talked about this a bit, and in general we don't feel like it's enough of an issue to warrant any backwards compatibility breaks, which this would entail unless we wanted to add a secondary method for creating sessions, which would lead to additional maintenance burden and developer confusion over which to pick for a use case that feels like a relatively rare edge case.
