### ISSUE TITLE
[Controller EventListeners] How to directly add event listener for `thumbstick/thumbpad/menu press began/ended`?

### ISSUE THREAD

**Issue by kuixu** [immersive-web/webxr#1018]
Hi all, 

In the previous WebVR, I implemented all the Controller EventListeners below for both Microsoft mixed reality and HTC VIVE. [[code]](https://github.com/kuixu/VRmol/blob/68b208fc4f768ec0f5a064a6befc2fe2cc7b8a5e/libs/render.js#L1420)

- `primary press began/ended` for listening Trigger Down/Up
- `menu press began/ended` for listening Menu button Down/Up
- `thumbstick touch began/ended` for listening Thumbstick touch 
- `thumbstick axes changed` for listening Thumbstick axes changed 
- `thumbpad press began/ended` for listening Thumbpad button Down/Up
- `thumbpad axes changed` for listening Thumbpad axes changed

However, I found a very limited EventListeners list like `select/squeeze start/end` in the newest WebXR API (renderer.xr.getController with XRControllerModelFactory). 

I am upgrading my molecule VR visualization platform [VRmol](vrmol.net) to support the cool WebXR. How could I implement those EventListeners based on WebXR? pls help. Thanks all.

**Comment by Manishearth** [comment]
Hi, this is not a general webxr help forum.

These event listeners do not exist, however the underlying data does, and you can listen for them per frame.

**Comment by kuixu** [comment]
Thanks for your reply, another question. How could we get the data of the menu button?

**Comment by toji** [comment]
It depends on the platform, but the menu button is typically reserved for use by the browser and/or OS and as such isn't made available to the page.
