### ISSUE TITLE
Consider using `this`

### ISSUE THREAD

**Issue by annevk** [immersive-web/webxr#1021]
Instead of

> Let session be the target XRSession.

you can write

> `Let _session_ be <a>this</a>` (or simply use this throughout) 

these days.

**Comment by Manishearth** [comment]
Good catch, thanks!

**Comment by cabanier** [comment]
does this mean that we should replace "the target xxxx" with "this" everywhere?

**Comment by Manishearth** [comment]
Yep

**Comment by Manishearth** [comment]
Fixed in #1028
