### ISSUE TITLE
"local-floor" referance space doesn't work on oculus quest.

### ISSUE THREAD

**Issue by beProsto** [immersive-web/webxr#1038]
I'm not sure if it even should work - but it seems like it's supposed to. I'm bored of offsetting the referance space by -1.6 units on the y axis, I'd love to see "local-floor" actually respond when requested.

**Comment by Manishearth** [comment]
This repo is for issues with the specification only

**Comment by toji** [comment]
@Manishearth is correct, in that you'll need to reach out to Oculus for help with their browser, but anecdotally I'll add that I've successfully used "local-floor" on the Quest quite a bit and found it to work well. When you create the session are you adding "local-floor" to the optional or required features, like so?

```js
let session = await navigator.xr.requestSession('immersive-vr', {
    requiredFeatures: ['local-floor']
});
```

This is required by [the spec](https://immersive-web.github.io/webxr/#feature-dependencies) and demonstrated in the [WebXR samples](https://github.com/immersive-web/webxr-samples/blob/master/room-scale.html#L93).

**Comment by beProsto** [comment]
I'm very sorry for posting this issue here, I didn't know this repo was for specification related issues. Please forgive me. I would like to thank you, toji, as I didn't actually know we have to define "local-floor" as a required feature. Thank you.
