### ISSUE TITLE
Should XRRigidTransform reject non-finite values

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#1040]
XRRigidTransform currently doesn't have any validation on the values it takes in its constructor.
So, if the author passes NaN values, they will be forwarded to the WebXR internals and driver which might cause crashes or other undefined behavior.

XRRigidTransform should do some simple validation and reject non-sensical values.

**Comment by Manishearth** [comment]
It already does, [WebIDL `float`s are finite](https://heycam.github.io/webidl/#idl-float). There's [`unrestricted float`](https://heycam.github.io/webidl/#idl-unrestricted-float) if you want non-finite values. If your browser is allowing infinite floats in the constructor, that's a bug in its webidl bindings generation implementation.

**Comment by cabanier** [comment]
@Manishearth not so fast :-)
The [XRRigidTransform](https://immersive-web.github.io/webxr/#xrrigidtransform-interface) constructor takes 2 [DOMPointInits](https://drafts.fxtf.org/geometry-1/#dictdef-dompointinit) that allow unrestricted doubles.

**Comment by Manishearth** [comment]
oh HUH.

I think we should just fix this then
