### ISSUE TITLE
Clarify the concept of underlying view

### ISSUE THREAD

**Issue by svillar** [immersive-web/webxr#1047]
In [this commit](https://github.com/immersive-web/webxr/commit/b2d1bba08e68bd4806022fd741e57a2a1036eeb3) a new concept called "underlying view" was added. It's a bit difficult to understand what we are talking about from the text. On the one hand it looks like we're talking about a platform object which represents a hardware view but on the other, [its definition](https://immersive-web.github.io/webxr/#xrview-underlying-view) seems to suggest that it's another `XRView`.

Also defining the "underlying view" as "the underlying view that it represents" does not shed light on the issue.

**Comment by Manishearth** [comment]
The issue here is that the definition should be the _next_ line

"view" is an abstract concept here, each XRView represents a view at a given frame

**Comment by Manishearth** [comment]
Does https://github.com/immersive-web/webxr/pull/1048 address your concern? "underlying view" is just a way to distinguish between an XRView and the abstract view it represents.

**Comment by svillar** [comment]
> Does #1048 address your concern? "underlying view" is just a way to distinguish between an XRView and the abstract view it represents.

Yeah, now it makes sense. Thanks
