### ISSUE TITLE
getFrameData update of VRPose nullable readonly attributes

### ISSUE THREAD

**Issue by mncharity** [immersive-web/webxr#105]
In _Editor's Draft, 21 September 2016_,

getFrameData mutates its frameData argument,

```
interface VRDisplay : EventTarget {
  * Populates the passed VRFrameData ...
  boolean getFrameData(VRFrameData frameData);
```

>  getFrameData() Populates the provided VRFrameData object with the VRPose and ...

which contains a read-only pose,

```
interface VRFrameData {
  readonly attribute VRPose pose;
```

which contains several read-only properties.

```
interface VRPose {
  readonly attribute Float32Array? position;
  readonly attribute Float32Array? linearVelocity;
  ...
```

These pose properties may be a Float32Array object, or "MAY be null if the sensor is incapable of providing [the] data."

Now, the items of a Float32Array object can be mutated in place.  But a Float32Array cannot be mutated into a null, nor a null into a Float32Array.  And these read-only properties cannot be set.

How then can getFrameData populate a VRPose object?  And thus a VRFrameData object?

Perhaps the VRFrameData pose attribute needs to be writable?  ~~readonly~~

```
interface VRFrameData {
  attribute VRPose pose;
```

It will usually be possible to update a pose object in place.  But not always.  Especially the first time a new VRFrameData object is passed to getFrameData.  Because the VRFrameData and/or VRPose constructors cannot anticipate which data the display's sensors are capable of providing.

Or am I missing something?

A similar issue may arise with VRFrameData's `timestamp`.  But perhaps a [DOMHighResTimeStamp](https://www.w3.org/TR/hr-time/#dom-domhighrestimestamp) can somehow be updated without setting the frameData timestamp property?

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#17
