### ISSUE TITLE
Can not open camera when visit the samples

### ISSUE THREAD

**Issue by Davidwang007** [immersive-web/webxr#1050]
I am new to webXR,there are two questions ,any help would be appreciated.
1. Is webXR needs ARCore ,ARKit or other third part SDK to run AR ?
2. When i used chrome 81 to test this link: https://immersive-web.github.io/webxr-samples/hit-test.html,The phone camera can not open,I have used two phones to test this link: SAMSUNG S7 edge and HUAWEI P20 Pro. nothing happened expect the grey backgroud,so ,what  i missed or why ?

**Comment by Manishearth** [comment]
This is not a help forum for WebXR usage, this is where the specification is discussed.
