### ISSUE TITLE
Difficulty with multiprocess implementation of updateRenderState

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#1051]
The spec for `updateRenderState` (https://immersive-web.github.io/webxr/#dom-xrsession-updaterenderstate) is that it synchronously updates the pending render state, which is then applied (synchronously) to be the new active render state just before rAF callbacks are executed (https://immersive-web.github.io/webxr/#xr-animation-frame).

The end result of this is that it is very difficult to provide a mutiprocess implementation of `updateRenderState`, where the script is run in one process and the webxr device driver is run in another. Consider:
```js
   flag = false;
   session.updateRenderState(A);
   button.onclick = function () { flag = true; session.updateRenderState(B); }
   session.requestAnimationFrame(function f() { 
      session.requestAnimationFrame(f);
      if (flag) { assert(render state is B); }
   });
```
According to the spec, the assertion can never fail, but it is difficult to implement this without shared memory.

**Comment by asajeffrey** [comment]
A possible fix for this is to remove the pending render state, and instead to have `updateRenderState` schedule a task to update the active render state.

**Comment by asajeffrey** [comment]
(As a bit of context, multiprocess is a security feature for Spectre mitigation.)

**Comment by Manishearth** [comment]
The core of this issue is that we don't actually specify how the XR backend consumes the active render state, the pending and active render state are wholly script-side objects.

A good fix for this would be to introduce a nullable "applied pending render state" object that lives on the session thread that is sent down with each animation frame. `updateRenderState` updates this in parallel, and when it is non-null it's sent down with the XR animation frame callback, which we need to specify as a "queue a task" thing anyway.

**Comment by asajeffrey** [comment]
If we're queuing a task, we can get rid of the pending render state and just simplify the spec to make `updateRenderState` queue a task to update the active render state?

**Comment by Manishearth** [comment]
We can do that as well. @toji  is there any reason for the current design here?

**Comment by asajeffrey** [comment]
On a related note, https://immersive-web.github.io/webxr/#check-the-layers-state checks to see if the active render state has a layer, but not that the layer used to produce the frame is the same as the active render state's layer.

**Comment by toji** [comment]
/agenda to ask if it's appropriate to move when `updateRenderState()` changes are applied.

I recall that there was quite a bit of discussion about this timing when we first added `updateRenderState()`, and I don't recall why we landed on the currently pattern aside from a general sense that it would be more intuitive for the users. I think there's ample reason on the implementation side to change when it applies though and would like to reconsider it as a group.

**Comment by asajeffrey** [comment]
I think the simplest thing would be for a frame to remember which renderstate was active when it was created, and then in https://immersive-web.github.io/webxr/#check-the-layers-state check to see if the frame's render state is the same as the active render state. (This is the check I implemented in Servo.)
