### ISSUE TITLE
WebXR on Chrome 83 with Vive

### ISSUE THREAD

**Issue by Arj4ns** [immersive-web/webxr#1077]
On Chrome 81, I was able to run XR applications on the HTC Vive by enabling multiple flags for the XR itself, and then another flag specifically for the Vive. On Chrome 83 though, all web XR flags barring #webxr-incubations and #webxr-runtime have been removed. 
At first, I figured they were implemented in by default, but I can't run any web xr application on Chrome from the Vive anymore. Changing the settings of the 2 flags I listed doesn't change anything either.
Does anyone have any information on this, and any possible workarounds at the moment?
Thanks!

**Comment by Manishearth** [comment]
This repository is for discussing the webxr specification, not individual implementations.
