### ISSUE TITLE
One big `secondary-views` opt-in, or an opt-in per secondary view scenario?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr#1085]
One thing we should discuss here is whether to share one big `secondary-views` opt-in, or have an opt-in per secondary view scenario.  For example, an app might harden itself to render for "first-person observer", but if some other system asks it to render "third-person observer", it may now need to render an avatar or other annotations around the user, and it's unlikely the app is already ready to do that.  However, opt-ins that are too granular limit where these platform features can be applied.

_Originally posted by @thetuvix in https://github.com/immersive-web/webxr/pull/1083/review_comment/create_

**Comment by Manishearth** [comment]
@thetuvix My personal model around this is that there's one big opt in, but individual kinds of views can expose an additional flag on the view that identifies what they are.

**Comment by toji** [comment]
I'm pretty much in the same boat as @Manishearth, though if there are compelling edge cases that wouldn't work well in that scenario I'd like to discuss them. I feel like all the variants I'm aware of break down into a pretty clean split between "Widest compatibility" mode and "Most technically accurate" mode.

**Comment by Manishearth** [comment]
Fwiw, this is what the FPO view does for this: https://github.com/immersive-web/webxr-ar-module/pull/57

**Comment by Manishearth** [comment]
/agenda To determine what we want to do here.

**Comment by kearwood** [comment]
One reason to separate the opt-in for 1st person views vs 3rd person views...  Some rendering engines may have the capability of rendering more than two views for increasing FOV, doing foveated rendering, or supporting C.A.V.E by supporting multiple view frustum and render targets.  This functionality is not always sufficient to support a 3rd person camera.  Rendering a 3rd person perspective requires additional engineering complexity and overhead in the engine for views that are placed some distance from the other views.  In particular, these 3rd person views may require different LOD selection or culling.  Some engines may not have implemented the ability for this 3rd person camera to traverse acceleration structures (eg, octrees, BVH's...) to ensure that the objects seen only by the 3rd person view get streamed in and rendered.  It may also be that a 3rd person view can break gameplay, such as enabling cheaters to see around obstacles to spot other players when not intended.

Such sites may choose to opt in to all secondary views, except for the 3rd person view.

**Comment by asajeffrey** [comment]
And just to add another case, there may be content that had artefacts when rendering to CAVE, e.g. it culls everything behind the player.

**Comment by Manishearth** [comment]
This was discussed in the call, the rough consensus seems to be that we can keep things as is (one big opt in) and in the future can add further opt ins if we really want. Closing for now.
