### ISSUE TITLE
When a session's list of views changes, only the current baseLayer is updated

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#1094]
At https://immersive-web.github.io/webxr/#update-the-viewports there is text for what happens when the list of views changes, which updates the current `baseLayer`. Other layers are not updated, which means that a layer is created, then the list of views changes, then we set `baseLayer` to be the layer, it will have a list of viewports corresponding to the old views, not the current views.

**Comment by asajeffrey** [comment]
Hmm, making the list of views mutable appears to be quite a recent change: https://github.com/immersive-web/webxr/pull/1093.

Rather than making this list mutable, would it be better to have the list be immutable, but each view has a mutable flag saying whether it is active or not?

**Comment by Manishearth** [comment]
The list of viewports (which is what matters for the layer) is not mutable. The list of viewport _objects_ (i.e. `getViewport()`) is

**Comment by asajeffrey** [comment]
This is confusing, at least to me :/

**Comment by asajeffrey** [comment]
Can we use language like "active view", so that the list of views / viewports / viewporrt objects is immutable? And then change the language so that `getViewport` returns `null` when the view is inactive?

**Comment by Manishearth** [comment]
Yeah I'm about to propose that change

**Comment by Manishearth** [comment]
The list of viewport objects is expressly not immutable though, we want to trash them whenever the viewport changes
