### ISSUE TITLE
On resolving requested features without a valid session

### ISSUE THREAD

**Issue by svillar** [immersive-web/webxr#1095]
UAs have to [resolve the requested features](https://immersive-web.github.io/webxr/#resolve-the-requested-features) as part of the [request session](https://immersive-web.github.io/webxr/#dom-xrsystem-requestsession) algorithm (concretely as part of the permission request algorithm).

Resolving a feature implies that _"If session’s XR device is not capable of supporting the functionality described by feature or the user agent has otherwise determined to reject the feature, return null"_. However it is not always possible to do that without having initialized the XR device first. For example in the case of the OpenXR API in order to [get the list of supported reference spaces](https://www.khronos.org/registry/OpenXR/specs/1.0/man/html/openxr.html#xrEnumerateReferenceSpaces) (the only valid feature descriptors so far) you have to get a valid session first (a OpenXR `XrSession`).

I guess that's the reason why the specs mention that _"Requested features can only be enabled for a session if the XR device is capable of supporting the feature"_ instead of saying that the current configuration must support them. So the question is, how are UAs supposed to deal with that? Should they keep a whitelist of device ids with supported reference spaces to avoid having to initialize the device to get them?

**Comment by Manishearth** [comment]
> you have to get a valid session first (a OpenXR `XrSession`)

This is true, but note that OpenXR allows you to have a session object that you have not entered yet. The OpenXR XrSession object does not perfectly map to the WebXR XRSession object (which can only exist _after_ immersive mode has been entered). The way to implement this is to create the session object, query its supported reference spaces, and throw it away if it doesn't support what you need.


I'm not aware of any device API that forces you to _enter immersive mode_ before you can query the reference spaces.

**Comment by svillar** [comment]
Ah OK, so the key here is not creating the session but entering. Thanks for the clarification
