### ISSUE TITLE
Basic WebXR test fails in Chrome Android. 

### ISSUE THREAD

**Issue by naseemshah** [immersive-web/webxr#1099]
Hi, just trying out WebXR API. I just did this basic test using `if(navigator.xr)`. Works fine in Windows Chrome. doesDnot work in android chrome. I am sure I am missing something here or i am doing it the wrong way. I am new to this. Thanks in advance

```
if(navigator.xr){
    Bsup.innerHTML = "Your Browser supports WebXR!";
    chkVR.disabled=false;
    chkAR.disabled=false;

}else{
    Bsup.innerHTML = "Your Browser does not support WebXR!"
    chkVR.disabled=true;
    chkAR.disabled=true;
    status.innerHTML = "Please try with a WebXR supported Browser.";
    
}
```

**Comment by Manishearth** [comment]
I'm sorry, this is not the bug tracker for Chrome, this is the bug tracker for the WebXR specification.

See https://bugs.chromium.org/p/chromium/

**Comment by Manishearth** [comment]
It's likely that your android chrome is out of date somehow.

**Comment by naseemshah** [comment]
I have the latest chrome version 83. WebXR examples works perfectly fine for me! Even Google Sodar AR application works in my phone. I don't know why this doesn't work.

**Comment by naseemshah** [comment]
is it possible i am doing the check the wrong way?

**Comment by toji** [comment]
That check should work, but only if your origin is secure. (HTTPS or localhost) I suspect you may be testing with localhost on Windows and then deploying to a non-HTTPS server to test with Android?

**Comment by naseemshah** [comment]
Yes, exactly! That's what what I did. I ran my a local server on my pc and connected via wifi to check in my android! Again this is Development server not production server.

Thank you for that, will try that out!

And this is the only way to check? is there any different way that I don't know of?

**Comment by naseemshah** [comment]
@toji thanks man! It totally worked! I pushed to gh-pages and it worked. 

![IMG_20200726_152934.jpg](https://user-images.githubusercontent.com/44234669/88476287-d2db2080-cf54-11ea-8070-325fd586c1e9.jpg)

Thanks alot! 😄
