### ISSUE TITLE
How can I use this webxr (especially the immersive-ar session) using ionic for Android?

### ISSUE THREAD

**Issue by JastiDev** [immersive-web/webxr#1100]
I tried to use webxr-polyfill and it was successful for inline and immersive-vr session.
But for immersive-ar session, it was not supported. Maybe the webview which is used in ionic to render web app on Android, doesn't support web AR.
I think there could be some way to provide AR for ionic.
I really want to use webxr Hit Test example with my ionic project.

**Comment by Manishearth** [comment]
I don't think there is currently, and this is the issue tracker for the specification, not a help forum.
