### ISSUE TITLE
Is there any way to hide the immersive-vr stereo view? I just want to use the spatial tracking feature of this vr.

### ISSUE THREAD

**Issue by JastiDev** [immersive-web/webxr#1101]
Requesting immersive-vr local session always turns on the full-screen topmost stereo GL view.
I don't want to see this on my app. I just want to use the spatial tracking feature of this vr.
For example I hope to use like this.
```
onXRFrame(t, frame) {
...
  let pose = frame.getViewerPose(this.xrRefSpace);
...
    for (let view of pose.views) { 
      console.log("camera position = ", view.transform.position);
      console.log("camera orientation = ", view.transform.orientation);
...
```
This is enough to do some indoor positioning and navigation in my application. 
Thanks about this but please let me know how to hide that full screen stereo view that is automatically triggered what the session is requested.

If spatial tracking is possible in inline session, that would be OK too, but I found it was disabled for some reason.

**Comment by Manishearth** [comment]
User agents are allowed to support spatial tracking in inline sessions, however not all of them will do so.
