### ISSUE TITLE
shadeless default for examples?

### ISSUE THREAD

**Issue by DevinBayly** [immersive-web/webxr#1104]
Hello there,

I have a gltf model that is an image with transparency on a  plane, and it shows up when I use  a custom version of the hittest. However when its on the floor there's a reflective point where I guess the scene light is centered, and when I place it on a wall I can't see it at all.

Is there a way to specify that a scene should have shadeless lighting? Webxr seems like a great fit for my work minus this. Thanks!

**Comment by AdaRoseCannon** [comment]
The rendering is all handled by your WebGL renderer. Most libraries let you
change your lighting or materials.

I also believe that the GLTF format itself has away for you to mark a
material as one that should be shadeless.

Good luck with your issue but it's not a WebXR specific one so I will close
the issue.

**Comment by DevinBayly** [comment]
sounds good, thanks for the ideas!
