### ISSUE TITLE
Should `vrdisplayactivate` and `vrdisplayactivate` be consolidated to single event?

### ISSUE THREAD

**Issue by cvan** [immersive-web/webxr#111]
Per https://w3c.github.io/webvr/#window-vrdisplayactivate-event:

> **`onvrdisplayactivate`***\* A user agent MAY dispatch this event type to indicate that something has occured which suggests the `VRDisplay` should be presented to. For example, if the `VRDisplay` is capable of detecting when the user has put it on, this event SHOULD fire when they do so with the reason "mounted".

Per https://w3c.github.io/webvr/#window-vrdisplaydeactivate-event:

> **`onvrdisplaydeactivate`** A user agent MAY dispatch this event type to indicate that something has occured which suggests the VRDisplay should exit presentation. For example, if the VRDisplay is capable of detecting when the user has taken it off, this event SHOULD fire when they do so with the reason "unmounted".

À la [`vrdisplaypresentchange`](https://w3c.github.io/webvr/#window-vrdisplaypresentchange-event),  perhaps there should instead be a single event called `vrdisplaymountchange`?

And, in the veins of #109, perhaps `vrdisplaymounterror` as well? Though, I'm not sure when that would be fire, to be honest. Maybe like if there's a VR display connected but it times out on mounting?

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#7
