### ISSUE TITLE
Get video background in Webgl AR session

### ISSUE THREAD

**Issue by devilinthedata** [immersive-web/webxr#1120]
Hi

Is it possible to get hold of the video passthrough layer as a texture map within WebGL, when running an WebXR AR session? This would be useful for lighting / rendering effects, and possibly enhance the lighting effects to make the object 'sit' in the scene more realistically. I can't find anything in the API to do this, but it seems like it ought to be doable. We render into the baselayer, and I wondered if there were other layers we could get hold of somehow?

Thanks for any help, and best regards

Matt

**Comment by devilinthedata** [comment]
Thanks a lot for all the helpful comments. I will keep an eye on the lighting estimation proposal stuff.

**Comment by cabanier** [comment]
> Thanks a lot for all the helpful comments. I will keep an eye on the lighting estimation proposal stuff.

Was that the feature you were looking for? 
If not (or you have other asks), it's really helpful to hear about your use case.

**Comment by devilinthedata** [comment]
Of course, I'm glad to share.  We're doing 3d product visualisation in webgl, and the realism of our 3D rendering is a big selling point for us. We're keen to integrate an AR mode into our presentations, which webXR hopefully allows us to do. However having the lighting of the product be harmonious with the environment it appears in, adds greatly to the realism - grounding the model in the scene, so to speak.

We mostly use environment based lighting - but any info we could get regarding the lighting env. of the scene would be very helpful for us - simple average colour , single light direction, spherical gaussians.

I've a lot of experience in such realtime lighting schemes, and am definitely up for discussing possibilities, if that would be useful.

Cheers

Matt
