### ISSUE TITLE
Input profile name generation and normalization rules incomplete

### ISSUE THREAD

**Issue by aphillips** [immersive-web/webxr#1121]
Input profile name
https://immersive-web.github.io/webxr/#xrinputsource-input-profile-name

> An input profile name is a lowercase DOMString containing no spaces, with separate words concatenated with a hyphen (-) character. A descriptive name should be chosen, using the prefered verbiage of the device vendor when possible. If the platform provides an appropriate identifier, such as a USB vendor and product ID, it MAY be used. Values that uniquely identify a single device, such as serial numbers, MUST NOT be used. The input profile name MUST NOT contain an indication of device handedness. If multiple user agents expose the same device, they SHOULD make an effort to report the same input profile name. The WebXR Input Profiles Registry is the recommended location for managing input profile names.

We have concerns about the assumptions in these requirements. Making the string "lowercase" pulls in the complexity of case fold mapping. The description also assumes that there are words and concatenates them with a hyphen. There appears to be an implicit assumption that vendor names, product names, product IDs, and other product input profile capabilities are ASCII tokens. This might be correct for some or even most vendors. However, there is no reason to expect that this is the case and there are plenty of specifications, protocols, and formats that support a wide range of Unicode to the benefit of all. It should not matter if the string is rarely shown to end users, since the upstream tokens used to generate the value might very well be shown to users and may not have an obvious relationship to ASCII.

Generally speaking, for internal values we tend to recommend "namespacing" or identifier rules that are easier for systems to work with. This includes the use of ASCII-only identifiers, since that allow for normalized comparison using an ASCII casefold mapping and avoids other infelicities associated with large character sets. 

If your intention, however, is to allow international values including non-English (and thus likely non-ASCII) values or to allow naming that is at least somewhat localized for human consumption, we recommend that you not perform case fold mapping or other normalization and depend on normal string equality for matching type operations. It's unclear from your specification what expectations should be applied.

There are multiple ways to resolve this:

1. Convert the `input profile name` to an ASCII only token. Content rules should be clarified. It's likely that multiple hyphens or dangling hyphens are not intended to be allowed but the current specification is quiet on this topic.
2. Modify the `input profile name` to allow non-ASCII characters and remove the lowercase mapping. That is, the name is now just a DOMString with recommendations for what to put into the content.
3. Define a specific case fold mapping without restricting content to ASCII. This is... complicated... and not recommended.

(This is a comment from the I18N WG's horizontal review.)

See here: https://www.w3.org/TR/charmod-norm/#identityMatching
Case folding is discussed here: https://www.w3.org/TR/charmod-norm/#definitionCaseFolding

**Comment by Manishearth** [comment]
Yeah, I think we should just make this ascii lowercase. They are not for human consumption, only programmatic consumption (typically by https://github.com/immersive-web/webxr-input-profiles )

**Comment by Manishearth** [comment]
Also filed https://github.com/immersive-web/webxr-input-profiles/issues/175 (n.b. that repo is not a part of this spec)
