### ISSUE TITLE
Specify behavior when XR compatibility is requested without permissions policy

### ISSUE THREAD

**Issue by patrto** [immersive-web/webxr#1123]
If the 'xr-spatial-tracking' permissions policy is not allowed, the spec doesn't state the behavior when XR compatibility is requested.

Without the permission policy, I think that requesting XR compatibility should be rejected to prevent unnecessary switching to a high power GPU. A reasonable approach could be:
- For makeXRCompatible(), throw a SecurityError, similar to isSessionSupported()
- When requesting an XR compatible WebGL context, return a context with the xrCompatible flag set to false.

**Comment by Manishearth** [comment]
Yeah, we should do this, frames without permissions policy should behave as if there is no XR device.

`makeXRCompatible()` should probably not _throw_, but instead do nothing, as it does in cases where there is no XR device.
