### ISSUE TITLE
Applying the pending render state can't ever be executed

### ISSUE THREAD

**Issue by svillar** [immersive-web/webxr#1127]
The current algorithm for [XR animation frame](https://immersive-web.github.io/webxr/#xr-animation-frame) will always result in an abort on step 5 unless I'm missing something.

Step 5 aborts is the base layer of the active render state is `null` which is the default value. The base layer of the active render state is only set when [the pending state is applied](https://immersive-web.github.io/webxr/#apply-the-pending-render-state). However that step is the last step of the [XR animation frame](https://immersive-web.github.io/webxr/#xr-animation-frame) algorithm, meaning that it won't ever be executed because we're early returning before on step 5.

I've checked for example [Chromium's implementation](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/xr/xr_session.cc;drc=5f0a846a46897e5bb123c7be9baeaef20cf6343d;l=1592?originalUrl=https:%2F%2Fcs.chromium.org%2F) and they're running the apply very early just after receiving frame data.

**Comment by toji** [comment]
Thanks for pointing that out! This was a recent change, so Chromium is still using the older timing.

I'll push out a pull request to fix it soon.

**Comment by Manishearth** [comment]
For reference, we broke this in https://github.com/immersive-web/webxr/pull/1111 , i think we just need to handle the null case properly again
