### ISSUE TITLE
Dose any one know WebXR support ARcore Augmented Faces for web based AR?

### ISSUE THREAD

**Issue by TomDadongHu** [immersive-web/webxr#1150]
i am trying to build a WebAR Project on Android. I know Arkit have the ability to detection and tracking Face using Reality file

in the ARCore documentation, it saiys have the feature Augmented Faces. I think it work on APP, but does this works on browser as well?

I am new to AR tech i want to know if Arcore Augmented Faces works in Web base AR like this example https://blog.mozvr.com/webxr-viewer-2-0-released/ or some one know a successful example?

thanks very much.

**Comment by AdaRoseCannon** [comment]
WebXR currently does not support using faces as tracking markers there has been some discussion around this in some of the other repos but it's not a feature currently being worked on.

Maybe make a new issue in https://github.com/immersive-web/proposals
