### ISSUE TITLE
Read motions controller inputs in inline session

### ISSUE THREAD

**Issue by salvolannister** [immersive-web/webxr#1156]
I would like to read motion controller inputs through an "inline" session but it seems this kind of session doesn't allow me to do it.
I don't want to render anything on the HMD cause I already have a stream of stereo texture being displayed from remote, what I would like to do is just to read the inputs from my controllers and send them to the server that is streaming.

What I have already tried is:
1. Create an "inline" session
2. Use https with a self-signed certificate
3. Get the controller with the method xrSession.inputSources() while using the HMD emulator for Chrome 87.0

From the console I can see that I have two controllers but all their properties are null or "", while opening the same page from the Quest I have no inputsources.
I read [here ](url
![immagine](https://user-images.githubusercontent.com/34481854/104202999-e9eecb80-542b-11eb-80b5-88867f85e91c.png) in this sample **row 241** that is not possible to use controllers while in an inline session... So what can I do? 
)

**Comment by cabanier** [comment]
We don't give access to controller input in non-immersive session because otherwise web pages can infer too much information. For instance, pages could detect what the user types on the keyboard or how they are interacting with iframes.

**Comment by Manishearth** [comment]
Yes, this is intentional

**Comment by salvolannister** [comment]
I didn't think about that, thank you for the answer.. but I believe in the near future someone who is receiving the rendering from a remote server would need to access the controllers without be in an immersive session like I do now. 

How can I see the 360 texture that I am streaming with RTC from remote server and still access my controllers ?

**Comment by cabanier** [comment]
You can stream video directly to a WebGL texture and show that in your immersive session.
Also, if you use WebXR Media layers, you can show it immersively without needed any GL calls.
