### ISSUE TITLE
Image shaking when relaunching a VR immersive session after exiting it

### ISSUE THREAD

**Issue by ortollag** [immersive-web/webxr#1162]
Hello,
I noticed a bug lately.
I'm launching an immersive-vr session which is fluid and working as expected the first time but then I'm ending the session and relaunching it. This second time, the HMD displays a shaking images.
I checked and reproduced this problem on [this sample](https://immersive-web.github.io/webxr-samples/immersive-vr-session.html) with a HTC Vive with SteamVR 1.15.19 and chrome 87.0.4280.141

**Comment by cabanier** [comment]
That sounds more like an HTC or Chrome bug.
You should open up bugs against those products and not the WebXR spec.

**Comment by toji** [comment]
Agreed. Please file a bug on https://crbug.com with the details you've provided here and, if you don't mind, navigate to about:gpu and copy the contents of that page into the bug (or an attachement) as well since that can help with debugging. Thanks!
