### ISSUE TITLE
Unable to load appropriate profile

### ISSUE THREAD

**Issue by agandia** [immersive-web/webxr#1163]
I am creating a VR demo using webxr, and webxr-input-profiles

I am using Oculus Quest 2 as my HMD running on Chrome based browsers with Steam VR.
xrInputSource.profiles is reporting 'oculus-touch' and 'generic-trigger-squeeze-thumbstick' as a fallback instead of 'oculus-touch-v3' as I expected.

**Comment by cabanier** [comment]
That's a bug in Oculus' OpenXR implementation. I'll file an issue.
Meanwhile, this forum is not the right place to file these issue as it's not a spec bug.

**Comment by agandia** [comment]
Thank you @cabanier, I'll close the issue then.

**Comment by cabanier** [comment]
@toji Looking at https://github.com/chromium/chromium/blob/99314be8152e688bafbbf9a615536bdbb289ea87/device/vr/openxr/openxr_interaction_profiles.h#L106, it seems that Chrome is hardcoding this string.
Is there a way to handle the quest 2 touch controllers?

**Comment by toji** [comment]
I actually asked John Kearney about this the other day. The main problem is that the OpenXR input profiles don't differentiate between the Quest controllers, and since that's what we're using to test with they all end up as the same device. It does sound like the `XrSystemProperties.systemName` reports a different value for each generation of headset, though, so we could use that to differentiate the controller models.

**Comment by cabanier** [comment]
Is there a chromium bug on this?
(Sorry to hijack this issue with platform specific problems)

**Comment by toji** [comment]
This is probably the closest thing to the right bug: http://crbug.com/1006072

This issue inspired me to finally go an try to fix this, and I think I've got it worked out. Pending review here: https://chromium-review.googlesource.com/c/chromium/src/+/2725196 Related question that would make the fix more universal. Do you know the systemName OpenXR will report for a Rift S? It's the only Oculus headset I can't test, but if you can get me the exact string I'll make sure it reports a Touch v2 as part of that patch.

**Comment by cabanier** [comment]
I will ask internally

**Comment by cabanier** [comment]
I was told that the [`systemId`](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#getting-system) will be unique per device.

**Comment by toji** [comment]
`systemId` is an opaque identifier and not expected to be stable as far as I know. `systemName` is a human readable string that identifies the hardware SKU. For Quest 1 it's reporting "Quest" and for Quest 2 it's reporting "Mirmar".

**Comment by cabanier** [comment]
> `systemId` is an opaque identifier and not expected to be stable as far as I know. `systemName` is a human readable string that identifies the hardware SKU. For Quest 1 it's reporting "Quest" and for Quest 2 it's reporting "Mirmar".

Did it really say `Mirmar` or something like it?

**Comment by toji** [comment]
Sorry, it was `"Miramar"` (missed an "a" the first time). And yeah, I thought it was a bit odd that you'd flip between public product names and internal code names between hardware generations (I was seriously expecting Quest to be `"Santa Cruz"` after seeing the Quest 2 name) but as long as they've got unique strings per hardware rev who cares? 😁

**Comment by toji** [comment]
FYI: https://chromium-review.googlesource.com/c/chromium/src/+/2725196 has been merged now, so starting in either today or tomorrow's Chrome Canary build Quest and Quest 2 devices (when used with Oculus Link) should start reporting the right input profile. Closing this as fixed, though I'd still appreciate knowing the Rift S system name so I can patch that one it too!

**Comment by cabanier** [comment]
@toji the `Miramar` name will be removed in the near future. Can you also check on `Quest 2`?

**Comment by toji** [comment]
As long as that's the exact string, sure. I'll add a check for that. Any word on what the Rift S string is? I'd like to add that at the same time.

**Comment by cabanier** [comment]
I was told the string is `Oculus Rift S`

**Comment by toji** [comment]
Awesome, thanks!
