### ISSUE TITLE
Produce an WebXR A11y overview doc

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#1167]
One of the last outstanding items for CR is to produce a document detailing known accessibility tools, challenges, and techniques related to WebXR. Request by the TAG: https://github.com/w3ctag/design-reviews/issues/545#issuecomment-697219461

We should at least have the basic structure of such a document in place when we request CR, with the intent to keep it updated as new tools, research, and techniques become available.

**Comment by himorin** [comment]
do we want to flag this as tag-needs-resolution?

**Comment by dontcallmedom** [comment]
it's up to the TAG to decide whether to mark an issue with the -needs-resolution flag, but I've marked it as `tag-tracker`

**Comment by RealJoshue108** [comment]
Any update on this @toji?

**Comment by RealJoshue108** [comment]
Thanks @AdaRoseCannon

**Comment by Manishearth** [comment]
This now exists in https://github.com/immersive-web/webxr/blob/main/accessibility-considerations-explainer.md . Finishing touches are in https://github.com/immersive-web/webxr/issues/1219
