### ISSUE TITLE
Behavior of session.requestAnimationFrame on ended sessions

### ISSUE THREAD

**Issue by MortimerGoro** [immersive-web/webxr#1168]
We shouldn't allow any new frame requests once the session is ended, but I don't see the behavior defined in the spec:
-  Should we return a null handle (0) or throw an InvalidStateError?

**Comment by takahirox** [comment]
I would vote for throwing `InvalidStateError` like `session.updateRenderState` does.

**Comment by cabanier** [comment]
Chrome currently returns a `null` handle: https://github.com/chromium/chromium/blob/99314be8152e688bafbbf9a615536bdbb289ea87/third_party/blink/renderer/modules/xr/xr_session.cc#L762
There might already be some code that doesn't expect an exception so I think we should keep it that way.

**Comment by takahirox** [comment]
> Chrome currently returns a null handle:

Firefox seems to does so, too.

https://hg.mozilla.org/mozilla-central/file/tip/dom/vr/XRSession.cpp#l402

Keeping it that way doesn't break the both. Sounds good.

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/1169
