### ISSUE TITLE
Model deformed when using Web XR AR mode

### ISSUE THREAD

**Issue by Qiweih** [immersive-web/webxr#1176]
### Description

Hi ,

I encounter a problem using Web XR. The problem is the 3d model become broken very often in AR mode.  You can refer to the pictures attached. 
I would like to know if this issue is known ?  And could you give me some tips to solve this problem?  

![Working Image](https://user-images.githubusercontent.com/27771851/109390915-65aac600-794f-11eb-8c39-db0153637ab6.jpg)
![Not Working Image](https://user-images.githubusercontent.com/27771851/109390919-6b081080-794f-11eb-9a6b-9e997b57095f.jpg)

### Browser Affected
- [ 87.0.4280.141] Chrome

### OS
- [ 10] Android 

Thanks in advance.

**Comment by toji** [comment]
This is a known issue in Chrome, and we are actively looking into it. Related Chrome issue is: https://bugs.chromium.org/p/chromium/issues/detail?id=1167450
