### ISSUE TITLE
Enable native keyboard during an immersive session

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#1179]
We would like to provide authors access to the platform's native keyboard.
Experiences end up building their own input controls which results in an inconsistent experience for our users.

I envision an API that brings up the keyboard and sends a blur event to the session. While the keyboard is up, the system renders the controllers and a keyboard and no controller poses are sent to the experience.
When the user dismisses the keyboard, another event is generated and the experience gets controller poses again.

This is similar to #971

**Comment by Manishearth** [comment]
Isn't this https://github.com/immersive-web/proposals/issues/30 ? This is wider than just XR, and also needs to be framed in terms of "I want user input", not "I want a keyboard".

**Comment by cabanier** [comment]
> Isn't this [immersive-web/proposals#30](https://github.com/immersive-web/proposals/issues/30) ? 

Yes, I remembered there was a proposal but I couldn't find it under the WebXR repo.

> This is wider than just XR, and also needs to be framed in terms of "I want user input", not "I want a keyboard".

I'm unsure what you mean. Are there other inputs that should be enabled?
During WebXR, controllers and hands provide input. This proposal would just be a way to get a consistent keyboard experience.

**Comment by Maksims** [comment]
Implementing a virtual keyboard is a complex task. If the solution will not be provided by the WebXR spec and implemented by UA's, then it is expected for libraries for different WebGL engines will emerge. This will lead to different UX between WebXR applications, which is not great for end-user. This is similar to asking for websites to create their own keyboard for mobile touch screens.

Although keyboards are designed for fingers, and perhaps in the future (someday), we will have more convenient text input for VR context than keyboards. A great recent example of such is keyboards on Consoles.

Also, asking UA's to implement a keyboard can be hurt end-user UX if it is implemented poorly. Keyboards on mobiles for example do evolve, with AI prediction, auto-corrections, swipe typing and more. Implementing it as a JS library would be a challenge, and an integrated solution into UA's would be best here.

There is definitely a huge value in WebXR Keyboard.

**Comment by Manishearth** [comment]
> I'm unsure what you mean. Are there other inputs that should be enabled?

Some people may already have a keyboard connected that they wish to use. Others might be using assistive technologies.

Also this API would be useful for fullscreen mobile for similar reasons.

**Comment by cabanier** [comment]
> > I'm unsure what you mean. Are there other inputs that should be enabled?
> 
> Some people may already have a keyboard connected that they wish to use. Others might be using assistive technologies.

This is not an API for connected keyboards because they should just work (and I believe they already do on desktop)

> Also this API would be useful for fullscreen mobile for similar reasons.

Is there are problem with fullscreen mobile? I would expect the virtual keyboard to pop up there using the same mechanism as a regular web page.
Likewise, I don't think this is an issue for DOM Overlay

**Comment by Manishearth** [comment]
> This is not an API for connected keyboards because they should just work (and I believe they already do on desktop)

Correct! But if someone is using a connected keyboard, it probably should not _also_ bring up a physical one.

> Is there are problem with fullscreen mobile? I would expect the virtual keyboard to pop up there using the same mechanism as a regular web page.

Somewhat, in that you need to hack it by focusing a dummy text element.

**Comment by cabanier** [comment]
> > This is not an API for connected keyboards because they should just work (and I believe they already do on desktop)
> 
> Correct! But if someone is using a connected keyboard, it probably should not _also_ bring up a physical one.

I'm unsure. Quest supports bluetooth keyboards but if such a device was connected, I would expect the virtual keyboard to still pop up. 

> > Is there are problem with fullscreen mobile? I would expect the virtual keyboard to pop up there using the same mechanism as a regular web page.
> 
> Somewhat, in that you need to hack it by focusing a dummy text element.

What did you mean by "fullscreen mobile"? Is it regular fullscreen on mobile (ie youtube) or mobile VR?

**Comment by Manishearth** [comment]
> I'm unsure. Quest supports bluetooth keyboards but if such a device was connected, I would expect the virtual keyboard to still pop up.

I think this should be based on UA and user preference. Either way, this is mostly just a matter of framing.

> What did you mean by "fullscreen mobile"? Is it regular fullscreen on mobile (ie youtube) or mobile VR?

Regular fullscreen on mobile.

**Comment by Manishearth** [comment]
We think that immersive-web/proposals#30 is the right place to carry this forward.

If we do proceed with this, it will likely be a module, not a part of the core spec.

**Comment by cabanier** [comment]
I don't understand why this would be a module.
A lot of user want a simple solution to bring up a keyboard (or other input device for a11y) during a session to offer text input.

**Comment by Manishearth** [comment]
> I don't understand why this would be a module.


If it's a new API i'd prefer it be a module because if anything it's a more general API than just for XR, and it has further privacy implications. If it's something like https://github.com/immersive-web/proposals/issues/30#issuecomment-801221235 where we just make it possible to allow the focus hack in XR, that might be okay, but I'm unsure if that's sufficient.
