### ISSUE TITLE
Add clarification on user interaction and permission for installed apps

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#1183]
Currently, the spec allows bypassing of the security prompts and user interaction for installed applications (aka PWAs) because they already asked the user during installation.

@dannysu and I are wondering how this works with the existing security model in the browser.
Let's say that there is a `twitter.com/pwa` application that is an immersive app, would that mean that `twitter.com` doesn't also need a permission prompt?
We suspect that installed apps are different and would trigger this special behavior when the user clicks on the app (instead of navigating to it). If so, it would be good if this was clarified in the spec.

**Comment by cabanier** [comment]
/agenda discuss clarification on user interaction and permission for installed apps

**Comment by Manishearth** [comment]
> Let's say that there is a `twitter.com/pwa` application that is an immersive app, would that mean that `twitter.com` doesn't also need a permission prompt?

No, because the spec encodes the user intent in terms of _launching_ the web application. The act of launching the application is the consent indicator, not "there happens to be an application installed with this domain".

We're deliberately not overspecific here, this is supposed to be up to the user agent.

**Comment by cabanier** [comment]
> > Let's say that there is a `twitter.com/pwa` application that is an immersive app, would that mean that `twitter.com` doesn't also need a permission prompt?
> 
> No, because the spec encodes the user intent in terms of _launching_ the web application. The act of launching the application is the consent indicator, not "there happens to be an application installed with this domain".

It's not the launching that is the consent. According to the spec ([here](https://immersive-web.github.io/webxr/#application-launch) and [here](https://immersive-web.github.io/webxr/#user-consent)), it's that it was indicated during installation that the application is designed to be immersive.

> We're deliberately not overspecific here, this is supposed to be up to the user agent.

True, but I think we should add a note to clarify this.
Also, is this also the case for other parts of the web platform and is this specified somewhere? For instance, if the application shows it will use geolocation during installation, will it no longer prompt the user when it runs?

**Comment by Manishearth** [comment]
> It's not the launching that is the consent. According to the spec ([here](https://immersive-web.github.io/webxr/#application-launch) and [here](https://immersive-web.github.io/webxr/#user-consent)), it's that it was indicated during installation that the application is designed to be immersive.
> 

The exact wording is:

> In that case launching a web application MAY also serve as an indication of user intent.

The consent is indeed granted at install time. But the launching is where the user intent comes from.

---

> Also, is this also the case for other parts of the web platform and is this specified somewhere? For instance, if the application shows it will use geolocation during installation, will it no longer prompt the user when it runs?

The web platform, as a rule, does not tend to specify consent prompts to the detail we do. We're the exception to the norm, which is why I'm wary of being even _more_ normative on this.

**Comment by cabanier** [comment]
> The web platform, as a rule, does not tend to specify consent prompts to the detail we do. We're the exception to the norm, which is why I'm wary of being even _more_ normative on this.

I don't think that's completely true. For instance Geolocation [clearly specifies](https://www.w3.org/TR/geolocation-API/#privacy_for_uas) when the permission prompt should be shown and that there has to be support to revoke it later on.

I agree we don't need to be quite that specific, but one or two notes in the spec would help avoid confusion and clarify that web applications should take a different decision tree inside the UA.

**Comment by Manishearth** [comment]
> I don't think that's completely true. For instance Geolocation [clearly specifies](https://www.w3.org/TR/geolocation-API/#privacy_for_uas) when the permission prompt should be shown and that there has to be support to revoke it later on.

Ah, that's fair.

We could clarify this a little bit yeah.

**Comment by cabanier** [comment]
> We could clarify this a little bit yeah.

PR #1184 adds some clarification.
However, the `xr` permission itself is not handled different from a web application. 

We either need to clarify that installing a web application may grant the permission to the origin or we leave things as-is and then the user will get a prompt when they launch the immersive app for the first time.
Should I ask for clarification from the web apps working group? I checked the issues list on the [permissions API](https://github.com/w3c/permissions/issues) list but I didn't find any mention.

**Comment by Manishearth** [comment]
I believe permissions already work that way.

**Comment by cabanier** [comment]
> I believe permissions already work that way.

The former (grant to web app by installing) or the latter (ask for permission when launched)?

**Comment by Manishearth** [comment]
No, I mean that permissions spec is _deliberately_  not clear on this issue, this is a matter of UA choice. So you can choose _either_.

https://w3c.github.io/permissions/#definitions

**Comment by cabanier** [comment]
hmm, I *think* the permission spec is clear that it's needed. 
However the language in the WebXR spec allows skipping the prompt for features that are passed in `requestSession`.

I think the note clarifies things enough so I will close this issue (unless someone objects).
