### ISSUE TITLE
Add support for a curated list of sites

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#1186]
The Oculus browser provides a list of websites on its landing page that provide people an introduction what WebXR can experience.
These experiences are clearly marked as "immersive experiences from around the web" so when users select them, there is a clear intent that these sites will go immersive.

We've noticed that the need for clicking and accepting the permission, is causing friction and confusion with new users so we'd like to explore if there is some way to carve out support for a workflow that treats this as if launching a web application.

The user agent is in control of this list and can check that the site was activated through the landing page.
Sites from that list wouldn't get additional permissions if a user would navigate to them as usual.

**Comment by avaer** [comment]
This makes a lot of sense. However, instead of thinking about lists which sets a distasteful precedent, perhaps this just needs support for "immersive intents".

Then Oculus browser could signal immersive intent for such cases if it wanted to maintain such a list.

**Comment by cabanier** [comment]
Yes, it doesn't need to be a "list". 
Basically, if the UA clearly indicates that a certain trusted site is an "immersive experience" and the user selects it, it can count as [user intent](https://immersive-web.github.io/webxr/#user-intention).

I believe we would need to expand section [13.2](https://immersive-web.github.io/webxr/#user-intention) of the spec to allow this.

**Comment by Manishearth** [comment]
I'm not sure if the spec needs to explicitly allow this; this is something the user agent has control over. The important part is to recognize this as a signal of user intent, and "user intent" is deliberately underdefined to allow this flexibility.

**Comment by cabanier** [comment]
> I'm not sure if the spec needs to explicitly allow this; this is something the user agent has control over. The important part is to recognize this as a signal of user intent, and "user intent" is deliberately under defined to allow this flexibility.

That's true, but if possible I prefer if [13.2.3](https://immersive-web.github.io/webxr/#user-consent) called out this option, ie:

> "on the install status of a web application, frequency and recency of visits or a user agent defined action where the user clearly signals intent that they want to enter an immersive experience.."

**Comment by Manishearth** [comment]
Sure, that works for me

**Comment by cabanier** [comment]
OK, I'll make a PR.
