### ISSUE TITLE
Clarification on connection/disconnection behavior

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#119]
Here are couple cases I'm curious about:

Case 1:
1. The developer calls getVRDisplays() but does not maintain a reference to the VRDisplays returned
2. The user unplugs one of the VRDisplays
3. The developer calls getVRDisplays again

Is the unplugged VRDisplay in the sequence and marked isConnected==false?  Or is it simply not present?

Case 2:
1. The developer is holding a reference to a VRDisplay
2.  The user unplugs this VRDisplay
3.  The user plugs back in the same VRDisplay

Is a new VRDisplay object created or is the same object now just marked as isConnected==true.  In other words, is VRDisplay.displayId consistent for a specific piece of hardware every time that hardware is attached?

Case 3:
1.  While in the middle of a frame, the user plugs in a new VRDisplay

When does the connected event fire?  After the submitFrame() call but before the next RAF callback?  Does it matter?

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#10
