### ISSUE TITLE
How to detect only vertical plane and disable detect horizontal plane 

### ISSUE THREAD

**Issue by dhaiduk** [immersive-web/webxr#1196]
How to detect only vertical plane and disable detect horizontal plane. 
How option may calculate the angle from **hit.get Pose(reference Space).transform.orientation**?

**Comment by Maksims** [comment]
I believe you can just ignore planes with other than vertical orientations in you application level.

**Comment by Manishearth** [comment]
Yes, you can use geometry to do this.
