### ISSUE TITLE
WebXR threejs corner distortion on camera initialization

### ISSUE THREAD

**Issue by dhaiduk** [immersive-web/webxr#1197]
Why, when the camera is launched not at a right angle in front of the wall PlaneGeometryis placed on the wall with a distortion of the angle?
If the camera is launched perpendicularly in front of the wall, then the PlaneGeometry is placed on the wall correctly.
How can this be eliminated?

![Untitled-1](https://user-images.githubusercontent.com/16472486/118860207-c826b900-b8e3-11eb-9ee7-ae18008fe2b4.jpg)

**Comment by Manishearth** [comment]
This is not the right place for questions about writing WebXR code

**Comment by toji** [comment]
Hi @dhaiduk!

This repro is for issues concerning the spec itself and not implementation or library bugs, sorry. I suggest reaching out on the [Three.js issue tracker](https://github.com/mrdoob/three.js/issues) first, or filing bugs against the specific browser that you are having trouble with if it looks like it's not a Three.js issue.
