### ISSUE TITLE
Clarifcation of depthNear and depthFar behavior

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#120]
The comments on the VRDisplay.depthNear and VRDisplay.depthFar attributes do not state which units they are specified in.  I'm guessing it's meters?

They also aren't included at all in section 2.1.1

And looking at it further, it seems like it might be worth pointing out in the comments for these attributes that the values are used to create the projection matrices in VRFrameData.

Furthermore, it would probably be worth clarifying when changes to these values will be applied.  In other words, should the developer requery the frame data immediately or will the changes be pending until the next frame?

**Comment by toji** [comment]
Hey! I actually wrote up a pull request for this! (Over a year and a half later, but still...) #359
