### ISSUE TITLE
Getting a screenshot 

### ISSUE THREAD

**Issue by MrDChristop** [immersive-web/webxr#1200]
Hi
i can not find a way to create a screenshot of my webXR AR immersive web app.
How do we take screenshots that we can then use as images or send to the user?
I cant find a way to access the context and read from it.

Thanks
Dimi

**Comment by AdaRoseCannon** [comment]
For security reasons there is currently no way to access the camera content in AR from WebXR.

Perhaps suggest to your users to use their device's screenshot shortcut?
We are looking at a way of exposing the camera but it's still early days yet.

**Comment by MrDChristop** [comment]
This is a bummer
since there are custom solutions and sdk out there that provide you access tot he camera.
https://zap.works/universal-ar/ 
https://www.8thwall.com/
Even open source ar.js enables you to get access
They pop up a question box about camera access and thats it. Then you can get the image from the canvas context.

**Comment by michaelvogt** [comment]
Hello Dimi.

Hello Dimi.

Maybe this helps as a starting point to get the camera image.
https://source.chromium.org/chromium/chromium/src/+/master:third_party/webxr_test_pages/webxr-samples/proposals/camera-access-barebones.html;bpv=0

But be aware that the explainer for the camera-access feature changed
recently, but the code from above is still working for me.
https://github.com/immersive-web/raw-camera-access/blob/main/explainer.md

According to Chrome platform status, this feature isn't behind a flag
anymore
https://www.chromestatus.com/features/5759984304390144


Hope this helps,
Michael

**Comment by MrDChristop** [comment]
Thanks
how do you test this? In my phone using chrome this camera-access feature does not exist
I found this site that has these proposed extensions
https://storage.googleapis.com/chromium-webxr-test/r886480/proposals/index.html

**Comment by michaelvogt** [comment]
Hello.

I would take this sample, run it locally to see if it runs correctly - the
camera image is shown as texture on a cube
https://source.chromium.org/chromium/chromium/src/+/master:third_party/webxr_test_pages/webxr-samples/proposals/camera-access-barebones.html;bpv=0

When it doesn't work, I'd active the WebXR incubation flag in chrome://flags



Best,
Michael

**Comment by MrDChristop** [comment]
Come on the omission of a proper way to get the background is not API help. 
It's called serious omission that had to be noted. 
Instead of crudely closing the thread please note this omission. 
Thanks for call your help

**Comment by klausw** [comment]
FYI, there was previous discussion about this topic here: https://github.com/immersive-web/webxr/issues/694 .

There are a few related topics here:

* getting JS/site access to a raw camera image: see https://github.com/immersive-web/raw-camera-access/blob/main/explainer.md . Please use that repository's issue tracker for general issues with that API's design, and crbug.com for Chromium-specific issues.
* locally capturing full screen contents including rendered images and a DOM overlay (if that exists). This is in some cases possible using native platform features, for example Android's screenshot or on-device screen recording capabilities. 
* sharing screen contents as a stream, i.e. by supporting [getCurrentBrowsingContextMedia](https://bugs.chromium.org/p/chromium/issues/detail?id=1200875) for AR sessions. This wouldn't necessarily be part of WebXR.

Please note that some of these concepts may be specific to certain form factors such as smartphone AR. For example, a see-through AR headset may not have any camera view that directly corresponds to what the user is seeing.

@Manishearth - would it help to set up a "new issue" template for this repo which explains the purpose of the issue tracker and links to other resources, for example https://immersiveweb.dev/ and its status table? While I understand your frustration about people asking for general help here, I think we're not doing a great job at directing people to more appropriate venues.

**Comment by Manishearth** [comment]
@klausw Yes, that's a great idea!

**Comment by AdaRoseCannon** [comment]
Speaking of which it might be a good idea to update the status table with
the features that are behind a flag.

Would a Chromie be able to update the table with the features that are
behind the flag?

**Comment by stspanho** [comment]
There is a workaround, you can take a screenshot with the camera access API and combine it with a screenshot of a three.js scene for example. You can test it here https://webxr.be/avatar

**Comment by ezawadzki** [comment]
@stspanho this example is great ! tested and validated. Do you know if the sources are shared somewhere ?

**Comment by stspanho** [comment]
@ezawadzki no don't think it's shared somewhere. But you can look up how you can take a screenshot in three.js and how to get the image from the camera access API. I combined them both on a canvas.

**Comment by Viki-17** [comment]
Hey guys

I have found a work around. I used google https://developers.google.com/ar/develop/scene-viewer#html AR Core API to redirect to the Google App which supports ARCore. From which we can capture photos i.e. Screenshot.

**Comment by AdaRoseCannon** [comment]
/tpac we should talk about creating an API for this based on the web share API.

**Comment by clapierre** [comment]
/tpac we should talk about setting up an accessibility Task Force within this group

**Comment by AdaRoseCannon** [comment]
That sounds like a good idea, could you create an issue for it, rather than in this thread itself? This was just an example, issue. Any issue can be marked for discussion at TPAC sorry for the miscommunication.

Probably under the webxr repo or under administrivia is the best place to create that issue

**Comment by alcooper91** [comment]
Worth noting that we already have: https://github.com/immersive-web/proposals/issues/68 (Where a repo was created with Rik and I as contact people: https://github.com/immersive-web/capture); however, I think we've both had other things that we've been focusing on.

**Comment by AdaRoseCannon** [comment]
Omg how did I miss that the repo existed, i'm going to make an issue in there to have a conversation about it at TPAC, to see if we can raise interest.
