### ISSUE TITLE
dom-overlay not filling screen and offset vertically

### ISSUE THREAD

**Issue by FuzzyWobble** [immersive-web/webxr#1202]
put an issue here, 
https://discourse.threejs.org/t/webxr-ar-dom-overlay-cant-fill-container/27123

but I think this may be a webXR issue as of recent?

just happened in the last month.

thanks!

**Comment by toji** [comment]
Unfortunately this is not a forum for implementation bugs, which this seems to be. Please raise the issue on https://crbug.com
