### ISSUE TITLE
WebXR API Emulator Extension - features not supported

### ISSUE THREAD

**Issue by tlevin1** [immersive-web/webxr#1206]
Hi,
I'm a bit new to WebXR and Babylon JS. I was trying to run the following demos [https://playground.babylonjs.com/#GG06BQ#3](url) and [https://playground.babylonjs.com/#98TM63](url)  in AR mode using the Chrome WebXR API Emulator extension and received the following errors:
"The required feature 'anchors' is not supported" 
"The required feature 'plane-detection' is not supported"
I did enable the incubation flag in Chrome but that didn't seem to help.
If anyone has any suggestions I would greatly appreciate it.

**Comment by toji** [comment]
This sounds like a support request for the WebXR emulator extension, which you can file on their issue tracker: https://github.com/MozillaReality/WebXR-emulator-extension/issues
