### ISSUE TITLE
All the WebAR samples freeze on a moto g10 phone

### ISSUE THREAD

**Issue by DavidLong65** [immersive-web/webxr#1208]
Hi, I recently purchased a Motorola g10 phone to add WebXR features to my website and I checked that phone was ARCore compatible. I was disappointed to find that every WebAR demo I tried just freezes after a couple of frames displaying only the camera view and no 3d objects. ARcore is installed and I'm using Chrome 86. AR apps work ok. Remote debugging shows no console errors.
Using the report page showed that when a session is running the transforms are being updated.
Does anyone know if there is a fix for this issue. As a Dev I'm willing to work with anyone to help resolve the issue. 
Thanks,
David

**Comment by klausw** [comment]
Thanks for the report. Chrome 86 is rather old - can you please update to current stable Chrome (>= 91.0.4472.120) or a beta/dev build for testing? If the issue still happens there, please file an issue at https://crbug.com/ in the Blink>WebXR>AR component. Feel free to tag me (klausw@chromium.org) in that issue.

**Comment by klausw** [comment]
FYI, https://bugs.chromium.org/p/chromium/issues/detail?id=1220069 reported show performance on a Motorola Edge Plus. There may be a Motorola-specific issue with ARCore. (Please still file a separate crbug, it's easy to consolidate them later if they turn out to have the same root cause.)

**Comment by DavidLong65** [comment]
Hi Klaus,
Thanks for the quick reply. I gave you the wrong version number, I had
updated Chrome and was using 91.0.4472.101. I've submitted a bug report:
https://bugs.chromium.org/p/chromium/issues/detail?id=1223712
Thanks,
David Long

**Comment by DavidLong65** [comment]
Hi Klaus,
What's the link for reporting ARCore bugs?
The web app display freezes and never advances another frame. However I
know that the WebXR session is still running and the camera  transform
matrices are being updated as the phone moves around.
This is displayed on the report page (the
https://immersive-web.github.io/webxr-samples/report/).
Android AR apps seem to work okay.
Regards,
David

**Comment by DavidLong65** [comment]
I forgot to mention I tested WebXR on Chrome Beta and Canary. I'll give DEV
a try too.
I also used remote debugging but no console output was shown.
