### ISSUE TITLE
rendering html pages within a webxr scene 

### ISSUE THREAD

**Issue by bbirdy** [immersive-web/webxr#1209]
we need a method to render an html page within a webxr scene, any existing approaches are not ideal and not fully supported when using VR headsets. 

e.g. use of internally hosted page within my webxr enabled webapp

**Comment by cabanier** [comment]
This is the DOM Layers proposal.
It's been discussed over the year and I've been working on it.
I updated the [explainer](https://github.com/cabanier/layers/blob/dom-layers/explainer.md#dom-layers) and the [spec](https://cabanier.github.io/layers/webxrlayers-1.html#domlayer) and posted them on my own github.

@toji , would you like to take a look? It's a work in progress but I would like to know if it's going in the right direction.

**Comment by bbirdy** [comment]
What is the eta for this capability? Sorry, I'm going to ask silly questions as I'm not a software developer by trade.

**Comment by cabanier** [comment]
> What is the eta for this capability? Sorry, I'm going to ask silly questions as I'm not a software developer by trade.

No worries :-)
Once WebXR Layers ships and we made more progress on performance features, it will be my main priority.
