### ISSUE TITLE
Clarification of requestPresent behavior when another requestPresent is pending

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#121]
Is there an expected behavior for requestPresent if the developer calls it a second time before the first promise has been completed/rejected?  Is it queued or rejected?  What about exitPresent?

**Comment by toji** [comment]
Off the top of my head it seems that reasonable behavior is that both the `requestPresent` and the `exitPresent` are rejected if a `requestPresent` is still pending. In the exit case, we shouldn't consider a display to be presenting until the promise has resolved, and calling `exitPresent` on a display which is not presenting is an error. On the repeated `requestPresent` call, we should simply spec it as an error to call `requestPresent` again while a call is still unresolved.

Any potentially interesting use cases this policy would overlook?

**Comment by brianchirls** [comment]
Shouldn't an `exitPresent` succeed even if a `requestPresent` is pending on the same device? It would just immediately cancel the request. I don't see any need to have to wait for a promise to resolve.

**Comment by RafaelCintron** [comment]
We are in favor of having multiple calls to requestPresent get rejected if there are existing ones in flight and having exitPresent always succeed in canceling the requestPresent.

**Comment by SamiraAtMicrosoft** [comment]
Continuing this conversation to also include the pending exitPresent scenario. To be thorough – below are the various cases we are interested in. Let’s assume we are starting from a connected but not presenting state. How do the other browsers handle both pending and new promises for the following scenarios? 
Here is my understanding from our latest discussion:

RP pending + new RP => new RP rejected, pending RP also rejected
RP pending + new EP => new EP rejected, pending RP also rejected
EP pending + new RP => new RP rejected, pending EP completes as expected
EP pending + new EP => new EP rejected, pending EP completes as expected

where RP refers to requestPresent and EP to exitPresent

**Comment by toji** [comment]
No complaints here.

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#11
