### ISSUE TITLE
Screen not centered on Android

### ISSUE THREAD

**Issue by psusset** [immersive-web/webxr#1213]
Hi,

I've noticed that the screen position is not always at the center depending on the Android device used :
![Screenshot_20210723-075521_Chrome](https://user-images.githubusercontent.com/49213097/126741946-3c1e49e5-d114-4ac4-a516-16536e130045.jpg)

In the screenshot, you can see the two eyes are not centered to the screen. Some of the device I use to test has a bigger offset that lead to make it unusable.

Is there a way to solve this issue ?

**Comment by AdaRoseCannon** [comment]
That looks like an issue with the WebXR Polyfill, it doesn't look like the native implementation the repo is here: https://github.com/immersive-web/webxr-polyfill

Your android device should should support it without needing the polyfill check that ARCore is installed. I think that is required to support android headsets.
