### ISSUE TITLE
How to handle the back button?

### ISSUE THREAD

**Issue by adriankulik** [immersive-web/webxr#1214]
Hello there!

I'm struggling with a small issue regarding the use of the back button in my Single Page Application.
I have implemented an exit button, which ends the session. When the user uses the Android navigation though, the canvas child isn't removed and it seems that the session remains active.

I can't find a JS event which could I could listen for, and I can't use the History API, since it's a SPA.

Link to the hosted app: https://adriankulik.github.io/DEFORM_XR/
Link to the AR code: https://github.com/adriankulik/DEFORM_XR/blob/main/index.js

I see, that the Google-made experiments managed to solve this issue: https://experiments.withgoogle.com/collection/webxr
The Bouncing Band experiment however, has a similar problem (3D objects added to the scene remain active on the splash screen when pressing the back button):
https://bouncing.band

I'd love to hear an opinion on tacking this issue.

Have a great day!
- Adrian

**Comment by Manishearth** [comment]
Hi, this is the repository for improving the specification itself, we don't provide help with using the API.
