### ISSUE TITLE
webXR shows "AR session supported" on unsupported device

### ISSUE THREAD

**Issue by optimus007** [immersive-web/webxr#1238]
This phone does not have ar-core support , but the start ar buttons is present
But
 `navigator.xr.isSessionSupported('immersive-ar')` returns true

Full discussion/screenshot and observations on threejs github
https://github.com/mrdoob/three.js/issues/22800

**Comment by Manishearth** [comment]
This should be reported to the relevant browser, not the standard.

**Comment by AdaRoseCannon** [comment]
This is a bug in the browser implementation, this is the issue list for the WebXR specification. It's best to report it directly to Chrome https://bugs.chromium.org/p/chromium/issues/list

**Comment by optimus007** [comment]
@AdaRoseCannon  thanks , reported https://bugs.chromium.org/p/chromium/issues/detail?id=1272785;
