### ISSUE TITLE
metadata in head to enhance webxr indexed content

### ISSUE THREAD

**Issue by HyroVitalyProtago** [immersive-web/webxr#1252]
Hello everyone,

Don't know exactly where to talk about this but I was thinking about a new metadata element to enable a better indexation in web browsers for webxr content. Maybe something like `<meta name="webxr" content="vr ar">` with vr and/or ar in content.

**Comment by toji** [comment]
The usual suggestion is to file feature requests like this as an issue in the Proposals repo, thanks!

https://github.com/immersive-web/proposals
