### ISSUE TITLE
WebXR on Hololens: Record mode shows gray overlay background instead of transparent

### ISSUE THREAD

**Issue by nosy-b** [immersive-web/webxr#1255]
Hi :)

It might me out of topic here, but by any chance if anyone knows why WebXR renders gray background instead of transparent when recording on the Hololens 2 on Edge?
I tried different settings for background in WebGL, couldn't find a way to avoid that. Here is an example (same in AR), I see it transparent but when recording the background gets visible.
Thanks! 
![bugWebXRHololensWhenRecording](https://user-images.githubusercontent.com/158514/156029132-d94ada6e-f130-48a9-84b9-bf97d70f208b.jpg)

**Comment by Yonet** [comment]
Hi @nosy-b, since this is a HoloLens specific issue, you can find help on https://holodevelopers.slack.com/. @fordacious might be able to help you report the issue or debug. Closing the issue here. Thanks!
