### ISSUE TITLE
Surface detection issue. Reticle not showing on the ceiling.

### ISSUE THREAD

**Issue by markonvc** [immersive-web/webxr#1256]
The Surface detection on floor is working fine but I can't get it working when the camera is looking towards the ceiling. Is this a camera performance issue, or can be done something about it ? I am using 'viewer' reference space type.

**Comment by Rishi-Goyal** [comment]
If anyone has a solution, I am facing same issue.

**Comment by himorin** [comment]
This space is for discussion of WebXR specification itself, but not any issue on implementation or libraries.
Submit your questions or support requests to forum for specific device or libraries.
