### ISSUE TITLE
permission-request reference needs to be replaced

### ISSUE THREAD

**Issue by plehegar** [immersive-web/webxr#1262]
The normative dependency on a CG Report [Requesting Permissions](https://wicg.github.io/permissions-request/) is a concern, particularly given https://github.com/WICG/permissions-request/issues/5.

It's used at:
 https://www.w3.org/TR/2022/CR-webxr-20220329/#ref-for-permission-request-algorithm

Not sure why it's referencing it...

**Comment by dontcallmedom** [comment]
I think it means to reference https://www.w3.org/TR/permissions/#dfn-request-permission-to-use instead

**Comment by Manishearth** [comment]
I think things moved around in the past, but yeah, the reference need not exist.

https://github.com/immersive-web/webxr/pull/1263
