### ISSUE TITLE
WebXR bug in Chrome on Samsung Galaxy S22

### ISSUE THREAD

**Issue by fabian-muff** [immersive-web/webxr#1277]
Hello
WebXR in Chrome has a problem on the new Samsung Galaxy S22. When entering an XR session the screen stays black. However, the access on the camera works, since the objects move according to the camera movements. Hit-Test is also working, but the camera stream is not visualized on the screen. 
When trying webxr on the system browser "samsung internet" everything works. Seems to be a bug in the API or in chrome.

**Comment by AdaRoseCannon** [comment]
If you have dark mode turned on it can sometimes cause this.

**Comment by fabian-muff** [comment]
> If you have dark mode turned on it can sometimes cause this.

I haven't enabled the dark mode. 
So this is unfortunately not the proble.

**Comment by fabian-muff** [comment]
@AdaRoseCannon 
Hello, since the last update of samsung internet v 17.0.4.3 the problem occurs also in this browser. Did you merge any chrome features into samsung internet? On chrome the bug is also still there on the galaxy s22. 
![Screenshot_20220615-105308_Samsung Internet](https://user-images.githubusercontent.com/77620758/173786480-80de75a9-d6f5-48cb-9ae8-dd44129531a5.jpg)

**Comment by AdaRoseCannon** [comment]
Since it happens in Chrome and Samsung Internet, i'm not sure it's something we can fix it seems to be a problem in ARCore, is it posible to upgrade that instead?

**Comment by fabian-muff** [comment]
That is strange. First it was only in chrome and not in Samsung Internet. 
ARCore is on the newest version. I tried to downgrade but it didn't help.
Then I downgraded the Samsung Internet to 16.2.5.4 and it works again. I assume, that the same bug from the chrome browser has been merged into the Samsung Internet repository now. 
How is it on other devices. is this only a problem of the S22 with Samsung Internet on v. 17.0.4.3 or does that happen on al devices with that version?

**Comment by fabian-muff** [comment]
@AdaRoseCannon 
Is there any progress on the problem? Am I the only user who reported such a problem?

**Comment by Manishearth** [comment]
This isn't the right venue to report bugs in individual browser implementations, this is the specification.

**Comment by fabian-muff** [comment]
@Manishearth 
well, this isn't browser specific anymore, since there doesn't exist a browser anymore where webxr (only AR sessions) works on a galaxy S22...
Where should I report the bug then? I feare it has to do something with multi camera devices. I think the problem does not come from the browser but from webxr itself, since the problem was first only in chrome and has then be "updated" to the other compatible browsers as well. They always run behind with webxr in relation to chrome

**Comment by AdaRoseCannon** [comment]
Sorry I don't work for Samsung any more emailing browser@samsung.com is best but they will not reply.

**Comment by Manishearth** [comment]
@fabian-muff unfortunately, still not the place for it; we coordinate the specification and don't have context or control over individual implementations, though implementors may also be participating here. I'm not sure where you would report this, seems like a Chrome bug but it's hard to tell.

**Comment by klausw** [comment]
For Chromium bugs, please file an issue at https://crbug.com . To speed up triage, consider using "WebXR" in the summary. 

@Manishearth , I think it would help to set up a new-issue template for this repository that explains its scope, and ideally also a link to a resources page that's editable via pull requests. For example an REPORTING-ISSUES.md file in this repository, or something on https://immersiveweb.dev/ . See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository for more info.

**Comment by toji** [comment]
I tried to set a template earlier today and found I don't have access to the settings for the WebXR repo?

**Comment by Manishearth** [comment]
IIRC issue templates are just files in the repo itself

**Comment by djebel-amila** [comment]
Hi, I am facing the same issue (black screen–no camera feed on AR mode/webXR websites) on my S22 Ultra Exynos. 
— I tried @fabian-muff ’s solution to downgrade Samsung Internet to 16.2.5.4, but even that wouldn’t work for me: AR services become unavailable after I was prompted to grant the app the authorization to map my surroundings. 

— I also tried Chrome Canary >= 107.0.5303.2, as suggested by @klausw in the related issue [here](https://github.com/google/model-viewer/issues/3495), but that didn’t work. Like with Samsung Internet 16, the AR button became inactive after granting the app the right to map the environment. 

— Some people [said](https://stackoverflow.com/questions/72599523/samsung-s22-ultra-show-black-screen-background-with-model-viewer) they fixed the model-viewer example they based their code on by changing
`ar-modes="webxr scene-viewer quick-look"` by
`ar-modes="scene-viewer quick-look webxr"` wonder if that’s any help to identify the issue? 

If anyone has any furhter insight or advice on how to run webXR apps on the s22… I just purchased this phone specifically for testing a webAR app in development, now trying to figure out whether I should write it off :'-(
