### ISSUE TITLE
Varjo VR-3 controllers not working

### ISSUE THREAD

**Issue by tobiasweede** [immersive-web/webxr#1291]
**Description**
Using a Varjo VR-3, the hands / controllers (Valve Index knuckles) are not displayed.

**To Reproduce**
Join any WebXR app with a VR-3 HMD paired with Valve Index knuckles. 
The hands are just not displayed. 
This makes interaction difficult / impossible.

**Hardware**
*Device: Varjo VR-3 HMD with Valve Index knuckles
* OS: Windows 10
* Browser: Chrome

**Additional context**
When I use the controllers with the Index HMD everything works as expected.
Varjo use their own OpenXR provider to interact with SteamVR.
I guess the issue is related to that.

I first thought it would be a Mozilla Hubs problem
https://github.com/mozilla/hubs/issues/5526
but it tuned out that all WeXR apps are affected...

**Comment by Manishearth** [comment]
This is the repository for the specification, we don't handle issues about individual browser implementations.
