### ISSUE TITLE
Hittest offsetRay--origin is not position offset in the self coordinate system based on viewerpose

### ISSUE THREAD

**Issue by DLGL99GL** [immersive-web/webxr#1294]
I used Hittest to implement the location marking function in Hololens;
As shown in the picture
I want to change the origin and direction of offsetRay to get the Hittest result pose likes "I need"
but final result likes "I get",that maked me wonder "the origin is not 3D position offset in viewerpose local system"
why the distance of the two getHitTestResults is getting smaller and smaller;
when the origin is out of ±1，getHitTestResults X /Y direction is the opposite of the theory？
![示意说明](https://user-images.githubusercontent.com/69023459/179717514-5d0ed33d-1705-462a-8a54-9cd0b08e9c99.png)

**Comment by Manishearth** [comment]
(this is not a place for help with the API)
