### ISSUE TITLE
Are XRFrame.active and XRFrame.animationFrame booleans internal slots?

### ISSUE THREAD

**Issue by himorin** [immersive-web/webxr#1297]
(please close if this is something miss-reading of WebIDL...)

XRSession with animation frame [is defined as](https://www.w3.org/TR/webxr/#xrsession-animation-frame) `which is an [XRFrame](https://www.w3.org/TR/webxr/#xrframe) initialized with [active](https://www.w3.org/TR/webxr/#xrframe-active) set to false, [animationFrame](https://www.w3.org/TR/webxr/#xrframe-animationframe) set to true, and [session](https://www.w3.org/TR/webxr/#dom-xrframe-session) set to the [XRSession](https://www.w3.org/TR/webxr/#xrsession).`, with sets three attributes: `active`, `animationFrame` and `session`.

But [XRFrame](https://www.w3.org/TR/webxr/#xrframe-interface) is defined as:
```
[SecureContext, Exposed=Window] interface XRFrame {
  [SameObject] readonly attribute XRSession session;
  readonly attribute DOMHighResTimeStamp predictedDisplayTime;

  XRViewerPose? getViewerPose(XRReferenceSpace referenceSpace);
  XRPose? getPose(XRSpace space, XRSpace baseSpace);
};
```
which does not have `active` nor `animationFrame`.

Note, checking with git blame, there seems no commit to delete these attributes...

**Comment by dontcallmedom** [comment]
I think they're meant as internal slots rather than IDL attributes - if so, they should be defined as such, and use the conventional `[[internalSlot]]` notation

**Comment by himorin** [comment]
mm,, I thought internal slots are also need to be included in WebIDL block with `[[internalSlot]]` for reference, but no need to do so?

**Comment by dontcallmedom** [comment]
internal slots aren't expected to appear in WebIDL blocks (not all internal slots can be described in terms of WebIDL)

**Comment by himorin** [comment]
I see, thank you for letting me that @dontcallmedom !

**Comment by dontcallmedom** [comment]
shouldn't we keep this open to make sure they're defined and referenced as internal slots?

**Comment by himorin** [comment]
ah, yes. also changed title.

**Comment by Manishearth** [comment]
Must we define them as internal slots? They are internal booleans, but it's not clear to me that they _must_ be stored as slots, since slots have a lot more specific implications.

**Comment by himorin** [comment]
Actually, original motivation was how to perform cross reference over these attributes in well coordinate manor, since our modules often extend WebXR Device API with partial interface etc.. 
hrm,,.

**Comment by dontcallmedom** [comment]
@Manishearth what specific implications are associated with internal slots? My (very possibly wrong) understanding is that they're mostly a convention to keep internal state associated with IDL objects.

@himorin to facilitate cross-referencing from other specs, you would simply need to make the relevant `<dfn>` exported (e.g. ` <dfn export for="XRFrame">active</dfn>`)

**Comment by Manishearth** [comment]
@dontcallmedom Hmm, I was under the impression that they sometimes correspond to internal JS slots on the object, but I'm not 100% sure. @toji ?

Either way, I don't think we _have_ to use slots: the cross references work just fine.

**Comment by toji** [comment]
Like @dontcallmedom, I'm not aware of any specific implications of designating something to be an "internal slot". I've always seen and used them as simply a convention for storing non-web-facing information associated with an IDL object.

I'm somewhat agnostic on whether or not we need to update the spec to use that specific formatting. It seems inconsistent to me in other specs I've read, but I'm not really opposed to it either. If there's a preference in the W3C that these things be internal slots I'm happy to update the syntax if for no other reason that to be a good example to authors of future specs (myself included). Otherwise it seems like busywork.

**Comment by Manishearth** [comment]
Overall I see TC39 specs using slots but not W3C ones, as much.

**Comment by dontcallmedom** [comment]
re usage in W3C, based on a cursory check in [webref](https://github.com/w3c/webref/tree/main/ed/dfns), there are 56 W3C/WHATWG specifications that define a total of 674 internal slots.

I personally think their conventional naming helps readability and identify at a glance (in the origin spec or when referenced from another one) that they're not Web exposed names.

But I fully agree this is an editorial choice, so feel free to close the issue if you don't think it has enough value.

**Comment by Manishearth** [comment]
I think I'll close: they may be more prominent but I don't think I've ever actually benefited from their visual prominence since it's basically always obvious from context.
