### ISSUE TITLE
[question] Eye tracking proposal?

### ISSUE THREAD

**Issue by JsMarq96** [immersive-web/webxr#1299]
Since there seems to be quite a few more affordable headsets with eye tracking coming on the next months, I started to look a bit in WebXR support for this feature, and of course, I might have missed it; but I did not found it; neither a proposal.

Is this something that is on the plans, or would help defining a proposal be appreciated?

My research group are looking at WebXR for our next project, and having this sort of functionality would be huge for us!

**Comment by svillar** [comment]
XRInputSource API already supports gaze tracking https://immersive-web.github.io/webxr/#xrinputsource-interface

**Comment by svillar** [comment]
> XRInputSource API already supports gaze tracking https://immersive-web.github.io/webxr/#xrinputsource-interface

Ah you said eye-tracking not gaze tracking, sorry for the confusion

**Comment by rayan-saleh** [comment]
Fairly major privacy implications to consider - but needs to be supported nevertheless.

**Comment by cabanier** [comment]
https://cabanier.github.io/webxr-face-tracking-1/ supports eye tracking and addresses some of the privacy concerns.
