### ISSUE TITLE
removing klausw@

### ISSUE THREAD

**Issue by klausw** [immersive-web/webxr#1304]
I'm changing roles and unfortunately won't be able to actively work on WebXR specifications in the near future. (I'll still be reachable for questions of course.) Are there any administrative steps needed to formalize this?

@bialpio agreed to take over as editor for DOM Overlays and Marker Tracking, I've created PRs for these: [DOM Overlays](https://github.com/immersive-web/dom-overlays/pull/53), [Marker Tracking](https://github.com/immersive-web/marker-tracking/pull/14).

I've edited the About entry for Marker Tracking, but don't have access rights to do so for [DOM Overlays](https://github.com/immersive-web/dom-overlays) where I'm currently listed as feature lead. Can someone update this to refer to @bialpio instead ?

**Comment by alcooper91** [comment]
@cwilso can you help us out here?

**Comment by cwilso** [comment]
Concerningly, I don't have access.  @AdaRoseCannon or @Yonet do you?  Trevor created this, I think, and I think it didn't get properly assigned.

**Comment by himorin** [comment]
mm. DOM Overlays is under IWWG, and repository is configured as the same as other IWWG repositories (incl. this webxr). 
Which kind of access do you mean? It seems for me, write permission (raising PRs or editing issues are under discussion, but anything else?

For any administrative step, I believe noted by chairs and announcement are all???

**Comment by Yonet** [comment]
I'm sorry that we won't get to work with you @klausw and thank you for all your valuable contribution. 
Are you not able to merge the PR or change the description @cwilso. You must be the admin. If not, I'll fix it.

**Comment by Yonet** [comment]
Looks like you are admin on both repos @cwilso. I'm not sure what happened there.

**Comment by Yonet** [comment]
/agenda to announce new repo owner to Marker Tracking and DOM Overlays

**Comment by himorin** [comment]
> I'm sorry that we won't get to work with you @klausw and thank you for all your valuable contribution. Are you not able to merge the PR or change the description @cwilso. You must be the admin. If not, I'll fix it.

I believe privilege configuration among co-chairs are the same, and not sure why..
If @cwilso does not see wheel icon around 'About' area, there could be some serious overlook...

**Comment by cabanier** [comment]
I'm sad that @klausw is leaving :-(
Can we close this issue?

**Comment by cabanier** [comment]
there were no objections to the handoff of @klausw's work. Can this issue be closed?
