### ISSUE TITLE
Duplicated controllers behind trusted UIs

### ISSUE THREAD

**Issue by emmanueljl** [immersive-web/webxr#1311]
If an experience doesn't hide its custom controllers when trusted/system UIs are shown, a duplicate pair of controllers will be displayed. Many experiences don't handle this properly, even when blur visibility-change is fired. It was made more apparent with our soft release of system keyboard support.[[1](https://twitter.com/emmanueljlee/status/1603550385230299136)] Currently this scenario isn't addressed in the spec, e.g. in [the Trusted UI section](https://www.w3.org/TR/webxr/#trustedenvironment-security).

Spit-balling: As with most issues, this could be solved either UA-side or app-side. UA's could hide+show/move custom controllers upon visibility changes? Or perhaps the responsibility should rest on apps, and it becomes a developer education problem? Any other suggestions?

/agenda Duplicated controllers behind trusted UIs

**Comment by AdaRoseCannon** [comment]
Removing label, because it was discussed at the last meeting, if this is in error or more discussion is needed please reuse '/agenda'
