### ISSUE TITLE
Some WebXR Implementations pause the 2D browser page in XR, make this optional?

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/webxr#1317]
Some WebXR Implementations pause the 2D browser page in WebXR, this is a performance improvement and is technically correct since the page isn't visible. Unfortunately it can cause issues if you are tying bits of your WebGL scene to DOM based animations and transitions. The ability to opt out of this behaviour would be handy for developers.

Related #1316 since this would also keep the animations running.

/agenda to discuss.

**Comment by mkeblx** [comment]
Here's a basic example page where a CSS animation value is used to drive a WebXR object's position. 
https://mkeblx.github.io/css2webxr/

This fails to work in WebXR if the WebXR implementation pauses the 2D browser page (e.g. like Meta Browser currently).

**Comment by cabanier** [comment]
@AdaRoseCannon are you interested in this?
If so, feel free to reopen
