### ISSUE TITLE
Stereoscopic effect in an immersive-ar scene

### ISSUE THREAD

**Issue by latifs** [immersive-web/webxr#1322]
Hey Guys,

I'm trying to use a google cardboard like (holokit.io) device for **AR** (immersive-ar).
So I'm trying to accomplish a left eye/right eye effect when I start my session and slide my android phone into the device.
I am using ThreeJs and thought that I could accomplish this. messing around with the renderer but no dice.

I have tried this:
* https://github.com/mrdoob/three.js/blob/master/examples/webgl_effects_stereo.html
* https://github.com/mrdoob/three.js/blob/master/examples/webgl_multiple_views.html

But it seems that the fullscreen **AR** is preventing any of this to happen.
Ideally I'd like to have the option to show 2 camera feeds side by side (one for each eye) with a slight overlap to accomplish the same stereoscopic effect that VR uses.

Am I right to think that threeJS cannot help me here?
how would I go about setting the fullscreen session as 2 half screen sessions side by side?

Thanks

**Comment by AdaRoseCannon** [comment]
This would have to be a mode which your Web browser implements rather than something you could build on top of a handheld 2D "immersive-ar" session

**Comment by AdaRoseCannon** [comment]
This is for discussion of the WebXR spec and no spec change is needed to support that so I am going to close this issue. You may want to request this feature in the bug tracker of your browser.
