### ISSUE TITLE
Android 14 Compatibility 

### ISSUE THREAD

**Issue by weiweiyeh** [immersive-web/webxr#1323]
I updated my Google pixel 6 pro to Android 14, but now I can't request to webxr session at all

**Comment by Manishearth** [comment]
This issue tracker is for the specification, not specific implementations

**Comment by toji** [comment]
For assistance with an issue like this, please file an bug at [https://crbug.com/](https://crbug.com/) and provide some additional details like the version of Chrome you're using, pages you've tried to access WebXR with, etc. Thanks!
