### ISSUE TITLE
WebXR Device API to integrate Haptic Gloves

### ISSUE THREAD

**Issue by addy1997** [immersive-web/webxr#1324]
Hi @toji,

I am looking to integrate my [Haptic Gloves](https://www.bhaptics.com/shop/tactglove) with my Meta Quest 2 using the WebXR Device API. The gloves can be connected to the browser via a dedicated JS-based library - [tact-js](https://github.com/bhaptics/tact-js). I've tested the library and it works successfully. My aim is to write a-frame component to control the gloves (by vibrating the posit). I referred to a couple of documents and repositories but couldn't find the proper documentation to advance further. Any guidance is really appreciated.

Thanks

**Comment by toji** [comment]
Unfortunately I'm not going to be of much help to you. I'm not very familiar with A-Frame's internals, nor was I aware of the gloves until reading this post. This repository is for questions and issues related to the WebXR Device API specification, and we can't provide support for libraries that make use of the API. For that you'd need to [reach out to them directly](https://github.com/aframevr/aframe/issues) or ask on one of the popular [development Q&A sites](https://stackoverflow.com/questions/tagged/aframe) out there.
