### ISSUE TITLE
WebXR is not _____

### ISSUE THREAD

**Issue by KooIaIa** [immersive-web/webxr#1329]
# WebXR is not the Web + XR.

If you say "Imagine the Web in XR" I hope in 10 years that today's WebXR is the last thing you imagine. WebXR's naming is unfortunate because it makes people assume the Web supports XR when in reality it has hardly nothing to do with WWWXR in it's current form. WebXR is a device API - it is not the Web + XR - it's the core of what Web + XR needs to function but it is not that function today.

# WebXR is not Human Friendly.

WebXR is designed for pro engine-engineers, machines, build-tools, AI, framework developers, domain-specific language developers. It is not designed to be friendly for web authors to read and write for websites with web language.

# WebXR is not Innovative.

WebXR got the fundamentals nailed down perfectly with OpenXR. It does not innovate beyond OpenXR.  OpenXR is the bare minimum device API for _console video game manufacturers_.  OpenXR is not designed for the Web or Computing. WebXR does not take advantage of what makes the web browser so uniquely powerful as a virtual internet connected operating system for hyper-information and software. Ground-work has been layed with layers but they haven't yet become ground-breaking or enticing.

# Apologetics:

WebXR did something more important than any one of these things - it made real XR hardware work in browsers in a standard way!  It is constantly innovating and staying up to date with new hardware. And OpenXR and all this stuff wasn't even that long ago - like it hasn't even been 10 years yet! Human-made Browsers and Standards move slow! Carefully designing things to be future proof takes care and time.

I first joined the the W3C five years ago to learn about the Internet, VR, and Websites. Since then I know so much more about the real challenges of the platform, the web's software engineering, and XR's unique software ecosystem. Seeing this group stably move forward year after year and learning about the Web has been a major inspiration in my life. 

People today might say that WebXR combines the worst aspects of the web platform: it isn't cross platform across computers (linux), it isn't supported by major browsers (firefox), it duplicates a standard for no reason while offering nothing (openxr), it is bespoke javascript api with no users or use case (non-native).  Some people don't even like the web... some people don't even like using XR... I would want to show them that WebXR can make both the web and XR amazing!

# 🌲Call to Action 🐕 _*bark bark bark*_

This year and next, we will begin to see the launch of **new XR headsets that can comfortably render the Web in XR for the very first time**. This is due to advances in the most fundamental components of XR headset's ability to display HTML comfortably.

![image](https://github.com/immersive-web/webxr/assets/30942833/c94fad39-38fb-48d8-8e3b-5090023d4893)

This is a big deal because so much stuff that has been impossible in XR for the last 10 years will be possible now. Remember going from Super Nintendo to N64? Smart Phones? DOS to XP? I saw them change and VR can change drastically in its capabilities too just from changes in hardware and thus software design. 

Who wants to work on XR now? 2010-2020 was XR's spotlight. AI will define 2020-2030. There is so much to be said and done. I want to use WebXR in 2033 and help make it even more web-y, innovative, and human friendly.

This essay isn't meant to be an 'issue' or a flame post or cast any blame and it is totally ok for it to be moved or locked. I wanted to share my raw perspective just as a framing to see how WebXR is today and how the immersive web could be tomorrow. And I know these subjects are complex are full of endless challenges but thank you for humoring me :)  I'm very excited about the next 10 years of WebXR!

**Comment by Manishearth** [comment]
I don't really think this is the place for this discussion.
