### ISSUE TITLE
Immersive-ar no longer supported on Edge for HoloLens 2

### ISSUE THREAD

**Issue by HedwigAR** [immersive-web/webxr#1330]
Hello!

I'm a developer working with WebXR, I really love that I'm able to port over my work to different devices and I'm not locked in while devices are still subject to so much change. 
I understand this is not the place for issues with specific browsers, but I've tried all other platforms I can think of to raise this issue, but have had no luck so far. 
Since one of the last Edge updates the `immersive-ar` setting is not available on Edge for the HoloLens 2, here's a screenshot showing that:
<img src="https://github.com/immersive-web/webxr/assets/4737792/649a0761-3f9b-4bc2-a1f3-44a1200dd613" width="400" height="320" />

`immersive-ar` used to be available and is, as I understand it, the preferred method for using WebXR on the HoloLens 2. 

I have checked and I am not the only one experiencing this issue:
* https://www.reddit.com/r/WebXR/comments/1442rmx/issue_with_ms_edge_and_immersivear_session_mode/
* https://stackoverflow.com/questions/76006294/hololens-2-failing-to-provide-immersive-ar-vr-experience-for-webxr
* https://learn.microsoft.com/en-us/answers/questions/1293414/unable-to-use-any-webxr-ar-app-on-ms-edge

I also have raised the issue through the HoloLens 2 feedback center itself, but have not seen improvement yet and I fear that without making some noise it will not get fixed any time soon.

As a workaround I am currently using `immersive-vr` but this excludes some features like anchors that I would like to use. 

While I understand this is not where the implementation of WebXR is happening for Edge specifically, I personally think that this flakiness (this has been broken for at least a month) is a big issue for the perceived maturity of WebXR, so I wanted to raise it here anyway. 

Thanks for your time, and let me know if there's anything else I can help clarify, if I missed something obvious or if there's another place more suited for my concerns.

**Comment by Manishearth** [comment]
This is the tracker for the specification, not implementations, and this issue is not actionable for us.

cc @Yonet though

**Comment by Yonet** [comment]
Hi @HedwigAR, I share your frustration and agree it is a big issue. Maybe @thetuvix might have an insight if there is a plan to fix the issue. Other than that, filing for the issue to Edge is the best action to take.
