### ISSUE TITLE
Using camera-access breaks dom-overlay fullscreen

### ISSUE THREAD

**Issue by frangaren** [immersive-web/webxr#1331]
When requesting `camera-access` and `dom-overlay` the top bar of Android shows over the webpage (see the screenshot below).
![With camera-access](https://github.com/immersive-web/webxr/assets/14963045/de09434a-f250-492b-b478-efb590f708bf)
The expected behavior would be the behavior of using `dom-overlay` without `camera-access`:
![Without camera-access](https://github.com/immersive-web/webxr/assets/14963045/1960a516-b64e-4175-a162-56d40936ff06)
A code fragment that reproduces this can be seen below:
```
<html>
    <head>
        <title>Camera-access + Overlay</title>
        <script type="application/javascript">
            async function start() {
                const overlay = document.querySelector('#webxr-overlay');
                const session = await navigator.xr.requestSession('immersive-ar', {
                    requiredFeatures: ['hit-test', 'dom-overlay', 'camera-access'],
                    domOverlay: { root: document.body }
                });
            }
            window.addEventListener('click', () => start(), { once: true });
        </script>
        <style type="text/css">
            #webxr-overlay .square {
                width: 64px;
                height: 64px;
                background-color: red;
            }
        </style>
    </head>
    <body>
        <div id="webxr-overlay">
            <div class="square">
            </div>
        </div>
    </body>
</html>
```
This is happening on Chrome 114.0.5735.130 running on the operating system Android 10; ONEPLUS A5010 Build/QKQ1.191014.012.

**Comment by Manishearth** [comment]
This is the repo for the specification; not for bugs in individual implementations of the WebXR API

**Comment by frangaren** [comment]
Sorry. If someone else is interested in the outcome of this issue, I've reported it at Chromium https://bugs.chromium.org/p/chromium/issues/detail?id=1456283
