### ISSUE TITLE
Automated testing of WebXR sessions with WebDriver

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/webxr#1335]
I don't think it's possible to perform automated testing of WebXR scenes at the moment. As people build more and more complex experiences they may want automated testing to help with the development process. [WebDriver](https://github.com/w3c/webdriver/) is the standard way to do this and it is developed within the W3C.

/tpac is this work we could do in this group?

**Comment by bialpio** [comment]
Related: https://immersive-web.github.io/webxr-test-api/

**Comment by AdaRoseCannon** [comment]
https://www.w3.org/2023/09/15-immersive-web-minutes.html#t06
