### ISSUE TITLE
Meta presentation on a11y for ARVR devices

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#1342]
People from Meta's ARVR accessibility team can do a presentation on how we're thinking about providing support for people with disabilities.
It would be helpful to have a list of topics that people want to get more information on.

/tpac list of questions for Meta presentation on a11y

**Comment by matthargett** [comment]
I’d love to hear about lessons learned from running focus group testing for low/no vision people on the Quest FTUX. I learned a lot from a similar presentation by Microsoft about FTUX on Windows.

**Comment by clapierre** [comment]
Same here, looking forward to hearing all about this.  As a low vision user myself I have been experimenting with some VR headsets and various environments and how accessible they are for me especially having to do with menus, and text interactions which can be difficult to see and enlarge and place at a location I can interact with.

**Comment by svillar** [comment]
Did the presentation finally happened? Is there any documentation available?

**Comment by AdaRoseCannon** [comment]
No, I am just closing the TPAC issues for now. We will try again to have this presentation at a future time.
