### ISSUE TITLE
Webxr fails to start on android 14

### ISSUE THREAD

**Issue by jonlo** [immersive-web/webxr#1351]
Hello

I updated my pixel 6a to android 14 and every webxr app stopped working. (google ar apps like the animal  apps still works)
The system asks you to update the android ar services, but it won't download them.

I'ts this a known issue? 
Is there any work around?

Thank you in advance.

**Comment by bialpio** [comment]
Are you using Chrome? If yes, can you please file a bug on crbug.com?

**Comment by jonlo** [comment]
Yes I am, v 118.0.5993.111 , I will add the bug to crbug, thank you

**Comment by gydence** [comment]
I am also experiencing this.  If a user doesn't have Google Play Services for AR installed, entering an immersive AR session (even on basic samples like https://immersive-web.github.io/webxr-samples/immersive-ar-session.html) will trigger a popup at the top to install the framework, but clicking install will crash Chrome.

**Comment by jonlo** [comment]
I have already notified this bug in chromium and it has been already assigned : [chromium bugs](https://bugs.chromium.org/p/chromium/issues/detail?id=1496921#c3)

**Comment by AdaRoseCannon** [comment]
Glad to see, it’s been assigned in the appropriate bug tracker.

This for the WebXR specification bugs so I am going to close this issue.
