### ISSUE TITLE
requiredFeatures: camera-access on hololens2

### ISSUE THREAD

**Issue by jonlo** [immersive-web/webxr#1353]
I'm not sure if this is the right forum to ask this question, if it's not, if it's not, I would appreciate it if you could direct me to the right place.

I'm having issues while trying to get camera raw image in the hololens 2 device. I tried using the camera-access requiredFeature but it seems like it's not allowed, as the application won't start (everything works fine in a mobile device).
However, I'm being able to display video from hololens in my webapp using navigator.mediaDevices.getUserMedia().  Am I missing something else about camera-access constraints.

Thank you in advance.

**Comment by toji** [comment]
Unfortunately this isn't the right place for help with specific implementations of WebXR. You'd need to reach out to the browser vendor themselves (Microsoft Edge, in this case.)

I don't know what the right venue is for that, but it seems to me like you could as at https://techcommunity.microsoft.com/t5/discussions/bd-p/EdgeInsiderDiscussions and if that's not the correct place then they could at least point you towards it.

Good luck!

**Comment by jonlo** [comment]
Thank you, I will try there!
