### ISSUE TITLE
Use of FrozenArray<>s in dictionaries is unnecessary and bad

### ISSUE THREAD

**Issue by domenic** [immersive-web/webxr#1368]
The spec has one "init" dictionary which accepts `FrozenArray<XRInputSource>`.

It's not clear what was intended here. But [per the Web IDL spec](https://webidl.spec.whatwg.org/#js-frozen-array), almost the exact same set of values are accepted compared to accepting the more conventional `sequence<XRInputSource>`.

(The difference is that certain proxies for arrays, which define throwing `getOwnPropertyDescriptor()` traps, would be rejected, because in theory the implementation is supposed to freeze the incoming array.)

We'd like to prohibit the usage of `FrozenArray<T>` as a dictionary member in Web IDL, per https://github.com/whatwg/webidl/issues/1399. It would be lovely if you could move to using `sequence<>`s.

**Comment by Maksims** [comment]
Is it frozen to avoid any modifications of it by the application? Which allows implementers to provide the same array and know that it only gets modified by them. Which eliminates a need to return a new array each time, which is beneficial for GC as many of these arrays can be referenced many-many times each frame.

**Comment by AdaRoseCannon** [comment]
/agenda Bringing it up at the next teleconference call.

**Comment by toji** [comment]
This appears to be a simple copy-paste error, where the attributes from the event were brought over to the associated init dictionary too literally. There's no reason I'm aware of why this needs to be a FrozenArray on the dictionary, though as @petervanderbeken points out it can and should continue to be a FrozenArray on the event itself.

**Comment by toji** [comment]
Put up a pull request to fix this. We can bring it up at the next call, but I think it'll be more of an advisory "Hey, this is a change that's gonna land" rather than something anyone will actually be concerned about.

**Comment by domenic** [comment]
I'm not sure who here is involved in the WebXR hit testing spec, but I have a similar issue over there which could use some attention, if there is any overlap: https://github.com/immersive-web/hit-test/issues/116

**Comment by toji** [comment]
It still falls broadly under this group. I can fix them.
