### ISSUE TITLE
Spec is unclear how a reference space event is handled

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#1377]
A reference space even is supposed to have a event that fires if it is reset (ie by holding down the meta button on quest).
This event has a transform that indicates the delta pose between the previous space.

The spec allows that pose to be null likely for cases where the system can't determine the delta but there's no spec text to indicate this. Should we add it?

/agenda how to handle unknown space resets?

**Comment by toji** [comment]
You're right, this needs some additional text.

I did some searching for any reference is previous issues to concretely state that the reason this is made nullable if for scenarios where the transform between the new space and the previous space can't be determined, but haven't found any. Nevertheless, it seems pretty clear to me that was the original intention and we should make that explicit in the attribute definition.

While we're updating this text, it would be nice to add a non-normative note explaining at least one scenario where this transform may be useful.
