### ISSUE TITLE
WebGPU+WebXR bindings?

### ISSUE THREAD

**Issue by mwyrzykowski** [immersive-web/webxr#1378]
With WebGPU being adopted or already adopted by several browsers, it would be great to allow WebXR to target WebGPU as well.

There is a great explainer doc here https://github.com/immersive-web/WebXR-WebGPU-Binding/blob/main/explainer.md from @toji  on WebGPU+WebXR bindings.

I would like to add an agenda item to the next meeting to discuss if we have any additional feedback to @toji 's document or if we can move that into a working draft specification.

/agenda proposal to discuss WebGPU+WebXR bindings

**Comment by cabanier** [comment]
@toji and you presented this at TPAC and got agreement from the group on this.
Is it ok if I close this issue? Feel free to reopen if not.
