### ISSUE TITLE
AR session recording and playback for WebXR

### ISSUE THREAD

**Issue by jamesjackson** [immersive-web/webxr#1384]
Hi, I'm affiliated with Open AR Cloud and the Metaverse Standards Forum, non-profits promoting open/interoperable spatial computing. We are big fans of using WebXR in our prototype development. Recently we have been trying to build location-based AR experiences without being in the physical location. This is proving to be extremely challenging. ARCore provides a recording and playback API but this can only be used with native applications. Does anyone have experience developing location-based AR experiences remotely with WebXR ? Would it be feasible to modify Chromium to use ARCore MP4 recordings ? Any pointers would be much appreciated !

**Comment by cabanier** [comment]
I'm unsure if this is a question for the Immersive WG. Maybe you can take this to the WebXR discord?
