### ISSUE TITLE
Supported Session Features Table and requestSession with promises

### ISSUE THREAD

**Issue by TiborUdvari** [immersive-web/webxr#1385]
I'm creating a page where one can see which features of immersive sessions are available. Does this already exist somewhere? I would prefer to link to it.

I'm trying to cycle through creating an `immersive-ar` and `immersive-vr` session with one session feature each time, as listed in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/XRSystem/requestSession). If the session creation is successful, the feature is supported. Is there a more straightforward way of achieving this?

I'm trying to use Promises and async-await, which works well in the simulator. However, on the Meta Quest 3 device I own, whenever any promise seems to be involved with `requestSession,` it just hangs and never returns. I wanted to document this here in case anyone else runs into this behavior. Please redirect me anywhere else if there is a more appropriate place to ask this question.

Context: I'm working on p5.xr, and I think it's a little tricky ATM for people to be able to query what capabilities their devices have

Here is a snippet I tried to wrap, which never returns either a session or an error:
```js
function requestSessionPromise(mode, feature) {
  return new Promise((resolve, reject) => {
    if (!navigator.xr) {
      reject(new Error('navigator.xr non existent'));
    }
    navigator.xr
      .requestSession(mode, { requiredFeatures: [feature] })
      .then(
        (session) => {
          resolve(session);
        },
        (error) => {
          reject(error);
        },
      );
  });
}
```

<img width="797" alt="Screenshot 2024-09-09 at 15 04 48" src="https://github.com/user-attachments/assets/173e5245-9d01-4008-845c-e40fa50abb66">

**Comment by Maksims** [comment]
I think you can make a single request with all features as optionalFueatures array, and then check a session's enabledFeatures list of what is supported.

**Comment by AdaRoseCannon** [comment]
https://immersiveweb.dev/#supporttable should be an up to date table. If you find mistakes please make a pull request.
