### ISSUE TITLE
User consent for spatial computing

### ISSUE THREAD

**Issue by rinchen** [immersive-web/webxr#1386]
This issue is generated from my review of https://github.com/w3cping/privacy-request/issues/142 

----
Hi,

When reviewing the spec, it was unclear to me how the spec ensures that a user appreciates and understands the power they are consenting to, and the permissions they are approving, with specific regards to facial mapping (e.g. taking a picture of your face used for avatar generation or to replicate facial expressions such as smiling and frowning) as well as overall spacial awareness. 

Especially with face mapping, the potential risks for privacy issues arising from sharing this data are rather high. I wanted to inquire with the spec authors whether additional normative clarity could be provided or if non-normative suggestions might be more appropriate. Alternatively, I might have overlooked something during my review.

**Comment by toji** [comment]
Hi @rinchen!

The WebXR Device API does not have any mechanism for facial tracking of the type that you describe, and no modules are in development to add it as of yet. The closest we have in terms of sensitivity of data to date is hand input, which is developed in a [separate module](https://immersive-web.github.io/webxr-hand-input/).

We can anticipate that the group may develop such facial tracking features someday, and if we do we will treat the privacy aspect of it with the gravity that such a sensitive data set deserves. Until then the spec represents what the group feels is an appropriate approach for the level of data being exposed: individually tracked devices, such as headsets, controllers, or mobile phones.

**Comment by rinchen** [comment]
Thanks @toji for the feedback and for confirming no modules are in development.

I was thinking ahead with the full spatial computing environment in mind, thinking that having some initial guidance before module development would be useful. This was influenced by another issue I filed on more precision around normative compliance. I'm happy to close this ticket with your answer as above.

**Comment by toji** [comment]
Thanks! And rest assured that if/when any sensitive features like that are under discussion we will reach out for the PING's input!

**Comment by rinchen** [comment]
@toji And in the news today [we see this](https://www.wired.com/story/apple-vision-pro-persona-eye-tracking-spy-typing/).  Just for background when you get to this.
