### ISSUE TITLE
Extending GamepadMappingType for WebVr

### ISSUE THREAD

**Issue by memmottse** [immersive-web/webxr#154]
Are there plans for extending the list of these types for WebVR?

**Comment by RafaelCintron** [comment]
@toji @kearwood , what GamepadMappingType is Chrome and Firefox using today? On the physical controllers, which physical buttons map to which index in the button array?  

We should be consistent about choosing the indices across all hardware form factors.  For instance, the suggested "select" button should always map to the same index.

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#13
