### ISSUE TITLE
UA-driven presentation without user gesture.

### ISSUE THREAD

**Issue by mthiesse** [immersive-web/webxr#165]
It would be really nice to specify something like a delayed present request (not requiring a user-gesture), where the UA decides when to respond and trigger presentation. The expectation is that the UA would not immediately grant or deny the request, but wait for some platform-specific event to respond.

Generally this is useful for reducing round-trips where the UA fires onvrdisplayactivate, and sites call requestPresent in response (instead of requesting, they would immediately begin presenting). In chromium for Daydream platforms in particular, the UA would like to know when the chromium app resumes whether or not it can display VR content, or whether it should tell the user to take off their headset. If the current site has registered this delayed present request, the UA would know that it can tell the page to start displaying VR content at will. Other platforms might benefit similarly.

**Comment by cvan** [comment]
Thanks for filing. This is covered in #30, #164, and other issues. I have a few interface changes to propose; I'll open a PR soonish. There's also #152 (which @toji started initially in #116).

**Comment by cvan** [comment]
@toji: is this handled by the proposed WebXR Input model?

**Comment by NellWaliczek** [comment]
Closing old WebVR issue.  Could potentially still be an issue with WebXR, but we believe this is probably mitigated by XRInput being a user gesture.
