### ISSUE TITLE
Proposal: Remove vrDisplay.submitFrame(), vrDisplay.requestAnimationFrame and use OffscreenCanvas & commit() by default.

### ISSUE THREAD

**Issue by bfgeek** [immersive-web/webxr#174]
```js
const canvas = new OffscreenCanvas(1000, 1000);
const layer = new CanvasVRLayer(canvas);
const display = ...;
display.appendLayer(layer);

async function drawLoop() {
  do {
  
  } while (await ctx.commit());
}
```

As discussed at Seattle F2F.

This is on the _main_ thread.

One point of debate is not requiring OffscreenCanvas by default and also allowing HTMLCanvasElement
 - My personal opinion of this is that we'd need to sort out what happens when you append the HTMLCanvasElement to the DOM which has strange consequences.

**Comment by RafaelCintron** [comment]
#170

**Comment by RafaelCintron** [comment]
See #170 for similar issue raised by @travisleithead

**Comment by cvan** [comment]
@toji: this can be closed, yes, per the proposed WebXR presentation model?

**Comment by toji** [comment]
Correct, thanks for pointing that out.
