### ISSUE TITLE
Add a bikeshed watcher / Webhook

### ISSUE THREAD

**Issue by cvan** [immersive-web/webxr#18]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Saturday Feb 20, 2016 at 00:41 GMT_
_Originally opened as https://github.com/MozVR/webvr-spec/issues/10_

---

Can borrow [this script](https://github.com/whatwg/loader/blob/master/local-watch.js) from https://github.com/whatwg/loader.

**Comment by toji** [comment]
What's the state of this issue? Trying to clear out older issues in favor or focusing on immediate priorities.

**Comment by cvan** [comment]
see PR #168

**Comment by toji** [comment]
This should actually be fixed now. Key was updating to Travis' built-in deploy function and ensuring it deployed to gh-pages rather than master.
