### ISSUE TITLE
Prepare explainer for TAG review

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#200]
After consulting with Chrome's ergonomics people they feel that [the 2.0 explainer](https://github.com/w3c/webvr/blob/master/explainer.md) in a reasonably good state and we should consider submitting it for a TAG review. I would like that as well, and feel like we're in a good place, but want to cast out one more broad request for comment before we submit it.

To make sure we're all on the same page, I don't expect that the API represented in the explainer is fully representative of the final product. There will undoubtedly be some tweaks that we'll want to make in response to the TAG review, and then ongoing adjustments as we write out the formal spec language and encounter edge cases during our respective implementations. What I want to make sure of, however, is that the functionality described by the explainer is covering everything we feel is necessary for the initial release and doing so in a way that we're broadly comfortable with.

So please take some time to review both the explainer and the [open 2.0 issues](https://github.com/w3c/webvr/milestone/3). Unless there's major concerns I plan on requesting a new TAG review sometime next week, after which the actual review will likely happen within a couple of weeks.

**Comment by newtoncalegari** [comment]
+1
I think it's really good!
@toji, I opened a PR (#201) fixing some small typos I found when reading.
