### ISSUE TITLE
Need for Asynchronous VRFrameOfReference creation

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#215]
Ties into PR #214 

During an Ergonomics review of the API at Google the question was raised "Why is CreateFrameOfReference a promise? Does it need to be async?" I think that for Chrome and all the backends that I'm familiar with the answer will be no. @NellWaliczek pointed out on a call, however, that keeping the API async would allow for things like guiding the user through the room setup process if they request a "stage" FoR and have not done the appropriate configuration yet. I can see the usefulness of that, but also worry that it may be overly disruptive? In any case, deserves a GH issue so that we can discuss it further! From what I can see the basic arguments for each approach are:

Async Frame of Reference creation:
- What is in the explainer today.
- If we keep it this way suggest renaming to `RequestFrameOfReference` to match the verbiage of `RequestSession`
- Promise rejects to indicate unsupported type.
- If the stage configuration flow mentioned above is to be a supported use case may also need to introduce a `SupportsFrameOfReference` to test for support without kicking off a heavyweight process like room calibration.

Sync Frame of Reference creation:
- Suggested syntax of `new VRFrameOfReference(session, options)` to match layer creation.
- Easier for developers to work with, less callbacks.
- Constructor would throw exception to indicate unsupported type. (This feels weird to me but there's precedent for it elsewhere on the web platform, such as the WebAudio API.)

**Comment by NellWaliczek** [comment]
For reference, the documentation I was referring to can be found [here](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.spatialstageframeofreference).

- SpatialStageFrameOfReference.Current will synchronously return the stage if one has been established and return null otherwise.  
- SpatialStageFrameOfReference.RequestNewStageAsync() will show system UI to guide the user in defining a new stage.

**Comment by toji** [comment]
Gave this some further thought over the weekend. I'm fairly concerned about the idea of the page kicking off system configuration UI, especially if it's semi-random. It's probably fairly surprising for the user and may lead to a mild spamming vector for pages that want to be annoying. If we were to allow for that type of workflow I'd think we'd need to place a few restrictions in place:

- If a stage FoR is requested in a non-exclusive session and isn't immediately available the promise should reject. This is to prevent pages from spawning one of these UIs immediately upon navigation with the user being unaware of why.
- Furthermore it might need to be limited to a user gesture or similar timing limitation so that you're not 30 minutes into a VR experience and for no good reason whatsoever *Bam!* Configure your Room!
- We'd need to ensure that canceling the dialog is something that persists at LEAST for the page lifetime, and probably better yet for the browsing session or something equally long. Otherwise I can just request a stage FoR in a loop upon reject and the user sees the config dialog over and over again.
- I do think we would need a way to test for FoR support without kicking off configs like that for the sake of lightweight feature detection, but I worry that if this is something that only happens on one platform developers wouldn't bother using that mechanism because they never see the need for it on their dev platform(s) and then are surprised by the behavior in the wild.

I appreciate the intent behind `RequestNewStageAsync()`, but it seems like a difficult thing to get right when wrapped away behind a WebAPI and increases platform complexity for the sake of a single implementation. I'm not totally against it, but I think I'm still slightly in favor of going with the simpler sync version of the API. Curious what other implementors think?

**Comment by toji** [comment]
Keeping RequestFrameOfReference async hasn't appeared to be problematic as we've been developing the spec/samples. Closing.
