### ISSUE TITLE
Add fingerprinting to Security Considerations

### ISSUE THREAD

**Issue by tomrittervg** [immersive-web/webxr#217]
WebVR exposes additional information about a user's computer and configuration. This includes detailed information about VR Displays that will certainly allow fingerprinting which exact model of display the user has. 

Additionally the VRPose interface gives detailed information about the physical movement of the user wearing the display. There's evidence that hardware manufacturing imperfections can lead to sensors creating a unique fingerprint (http://www.ece.illinois.edu/newsroom/article/7897 and http://www.mdpi.com/1424-8220/16/6/818/htm) and that user's behavior exposed by sensors like this can also uniquely identify them (https://arxiv.org/pdf/1309.0073.pdf). Even if these hardware imperfections or behaviors can't *uniquely* identify a user, they will certainly add to the *uniqueness* of a user and when combined with other active or passive measurements can be used to more uniquely identify a user than previously possible.

As mentioned in https://www.w3.org/2001/tag/doc/unsanctioned-tracking/ :

> [the TAG b]elieves that, because combatting fingerprinting is difficult, new Web specifications should take reasonable measures to avoid adding unneeded fingerprinting surface area. However, added surface area should not be a primary factor in determining whether to add a new feature.
> Asserts that when a new feature does add fingerprinting surface area, it should be documented as such.

Therefore I believe that these concerns should be documented in the spec.

**Comment by toji** [comment]
A very valid concern. This is actually something that we talk about a fair amount, but somehow never got around to discussing in the spec language. I'll make sure that we add some text to point out the issue and describe the mitigations.

**Comment by cvan** [comment]
Good call on filing! I swore these issues were covered in its own issue, but I can't find one. I do recall this related issue about security with `<iframe>`s: issue #77. That aside, to what Brandon said, we have discussed this quite a bit, but the discussions have been mostly on the WebVR discussion mailing list and meetings. Besides documenting the known attack vectors, besides enumerating them here for discussion and eventual spec language, are there any exceptionally dangerous patterns or API surface area that need to be addressed and/or mitigated in the previous revisions (i.e., ["v1.1"](https://w3c.github.io/webvr/spec/1.1/)) of the spec (and vendors' respective implementations)?

**Comment by NellWaliczek** [comment]
Privacy, fingerprinting, security, and user permissions issues are now being tracked in the privacy-and-security repo.  An initial explainer will be published in that repo shortly.
https://github.com/immersive-web/privacy-and-security
