### ISSUE TITLE
Support polygonal stage bounds

### ISSUE THREAD

**Issue by huningxin** [immersive-web/webxr#228]
**Problem Statement**
Current [VRStageBounds](https://w3c.github.io/webvr/spec/latest/#vrstagebounds-interface) interface only supports rectangular stage bounds.

```
interface VRStageBounds {
  readonly attribute double minX;
  readonly attribute double maxX;
  readonly attribute double minZ;
  readonly attribute double maxZ;
};
```

It can't support VR/MR devices/systems which can provide polygonal bounds defined by end users. 

With the polygonal bounds information, app is able to align the scene more precisely and create visual warning when user moves close to the bounds. 

Examples of native VR/MR systems provide polygonal bounds:

* [Oculus Guardian System](https://developer3.oculus.com/documentation/pcsdk/latest/concepts/dg-guardian-system/)

When boundary type is `ovrBoundary_Outer`, the `ovr_GetBoundaryGeometry` returns all of the points (in `ovrVector3f *`) that define the outer boundary.

* [Windows Mixed Reality](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.spatialstageframeofreference)

`TryGetMovementBounds` of `Spatial​Stage​Frame​Of​Reference` class returns the boundary vertices (in `Vector3[]`) of the open area defined by the user where they intend to move while using their headset.

* [OpenVR Chaperone](https://github.com/ValveSoftware/openvr/wiki/IVRChaperone_Overview)

`GetPlayAreaRect` returns the 4 corner positions of the PlayArea. It is rectangle which can be treated as a kind of polygon. 

**Proposal**

Remove `VRStageBounds` interface. Change `bounds` of `VRFrameOfReference` to a `Float32Array`. It supports the polygonal stage bounds, including the rectangular stage bounds.

```
interface VRFrameOfReference : VRCoordinateSystem {
  readonly attribute Float32Array? bounds;
};
```
The `bounds` is the array of all 3D points that define the bounds (in clockwise). Each 3D point is defined by 3 `float32`. 

When the bounds is rectangle, it contains 4 3D points.

**Comment by kearwood** [comment]
This sounds reasonable to me.

Would a helper-function be appropriate to add to the spec, which calculates the largest rectangular play area within the polygonal bounds?  Or should this be left to content to calculate?

Also, while we are at it, would it be beneficial expose an additional value for the height of the boundary area?

I propose that a simple float value representing the height be added to VRFrameOfReference if that is useful.

**Comment by toji** [comment]
This was something that was discussed when the stage bounds was initially defined. There's a desire to keep the scope of the spec limited at first to allow for a more realistic release timeframe. As a result, several "obvious" items like this have been earmarked for inclusion at a later date. The idea being that a simple rectangular bounds was easy to expose and offered the simplest way for apps to appropriately scale their content while the polygonal bounds were more expressive but a bit harder to use. They could easily be added on in a follow up version of the spec without breaking backwards compatibility, though.

I'd be interested to know if the other implementors were in favor of jumping to this step first without the intermediate bounding rect. (Mozilla at least seems open to it.) I think it's worth collecting this and a few other similar API additions and having the implementors vote on what they'd like to have included in the first pass of the 2.0 spec.

**Comment by NellWaliczek** [comment]
I'm a big fan of polygonal bounds and leaving it up to libraries like three.js or Babylon.js to provide specific implementations of rectangular bounds algorithms.  It's a somewhat non-trivial problem that has many different solutions; the right choice may well depend on the experience being authored.

The packing of the array like that seems a bit strange to me though.  Is there a reason we couldn't use an array of point type objects?

Also, it might be worth adding an event to the VRFrameOfReference to notify developers of bounds changes?  Though that might be a good candidate for waiting until 2.x...

**Comment by huningxin** [comment]
@kearwood 
> Would a helper-function be appropriate to add to the spec, which calculates the largest rectangular play area within the polygonal bounds? Or should this be left to content to calculate?

I would agree with @NellWaliczek to leave this to web apps or libraries as it quite depends on experiences being built.

> Also, while we are at it, would it be beneficial expose an additional value for the height of the boundary area?

As it is a 3D point array, each point has `Y` component.  Is it good to describe the height?

@NellWaliczek 
> The packing of the array like that seems a bit strange to me though. Is there a reason we couldn't use an array of point type objects?

Reasons of packing 3D points into `Float32Array`: 1) it aligns to Oculus SDK, WinMR and OpenVR which all expose float array of 3D points. 2) it is easy to upload to WebVR as vertices buffer. 3) `Y` component might be used as boundary height.

> Also, it might be worth adding an event to the VRFrameOfReference to notify developers of bounds changes? Though that might be a good candidate for waiting until 2.x...

+1 for adding `onboundschange` event to `VRFrameOfReference`.

**Comment by fernandojsg** [comment]
So far I didn't see much experiences (native or webvr) that uses the polygonal shape of the room setup to adapt nicely the experience to it, most of them uses just the maximum rect available in there. 
So I still believe it's nice to provide that largest rect play area for most common use cases.

**Comment by kearwood** [comment]
> I'm a big fan of polygonal bounds and leaving it up to libraries like three.js or Babylon.js to provide specific implementations of rectangular bounds algorithms. It's a somewhat non-trivial problem that has many different solutions; the right choice may well depend on the experience being authored.

If we don't provide this directly with the WebVR API, I think it would be acceptable to provide a reference function.  I would be glad to write this if it could be included along-side the spec.

> As it is a 3D point array, each point has Y component. Is it good to describe the height?

If the height is included in each point, then the question should be raised about how this height would be interpolated across the top surface of the play volume.  It would also raise questions about if the bottom of the play volume would also vary across the area.

We could require the Y components to have the same value.

> Also, it might be worth adding an event to the VRFrameOfReference to notify developers of bounds changes?
+1, This is a good idea, IMHO

**Comment by kearwood** [comment]
If we allow the height to be reported in the play volume, we should also define what happens when no height is reported by the underlying API.

Perhaps we could either return "0" for the height in these cases, or return a reasonable default (3 meters?)

**Comment by toji** [comment]
Update: We had a vote on features that should be in scope for WebVR 2.0 today and polygonal stage bounds was voted in. We still need to decide whether or not it should be in addition to a rectangular play area bounds or in place of it. I'll put together a pull request proposal for support in the next couple of days.

**Comment by huningxin** [comment]
I am glad to hear this is in.

I can try to make a pull request proposal and invite you guys review. @toji, does it sound to you?

**Comment by toji** [comment]
A `boundschange` event seems logical. :+1: 

One thing I feel I should push back on is the idea of these being 3D points. The explainer doesn't spell it out very well at this point, but the idea of a "stage" is that it's a bounded, flat, safe area to be walking around blindfolded in. Stages **should not** have varying floor heights (that sounds horrifically dangerous with non-see-through headsets), and should be in an area where the ceiling height is generally considered safe. (Yes, fans and such are hard to account for.) As a result, the bounds should be a 2D polygon that describes an "infinitely tall" volume from Y=0 up.

Future hardware will probably introduce capabilities to do more than that, sure, but I would argue that once you've reached a place where you can handle floors of varying heights and random ceiling outcroppings safely you've moved beyond the concept of a "stage" and into full-on world scale tracking, which will need a very different model of working with coordinate systems.

**Comment by huningxin** [comment]
> As a result, the bounds should be a 2D polygon that describes an "infinitely tall" volume from Y=0 up.

It makes sense to me given these points actually are **floor points** (with Y is "0"). I originally added the 3D points as it might be easy for WebGL visualization (BTW, do we need a sample for this usage?) and future hardware usage. 

But I would agree with @toji that we need to stick to the "stage" concept and 2D polygon bounds for WebVR 2.0.

By incorporating the feedbacks, I am updating the proposal to **v2**. Please take another look. Thanks!

```
interface VRCoordinateSystem : EventTarget {
  Float32Array? getTransformTo(VRCoordinateSystem other);
};

interface VRFrameOfReference : VRCoordinateSystem {
  readonly attribute sequence<VRFloorPoint>? bounds;
  attribute EventHandler onboundschange;
};

interface VRFloorPoint {
  readonly attribute double x;
  readonly attribute double z;
};
```
`bounds` contains the floor points in clockwise order. When `bounds` defines a rectangular play area, the first floor point (`bounds[0]`) is the top left corner (with minimum x and z) and third floor point (`bounds[2]`) is the bottom right corner (with maximum x and z).

```js
function isRectangle(bounds) {
  if (bounds.length == 4 && 
      bounds[0].x == bounds[3].x &&
      bounds[0].z == bounds[1].z &&
      bounds[2].x == bounds[1].x &&
      bounds[2].z == bounds[3].z)
    return true;
  return false;
}

if(frameOfRef.bounds) {
  // Reposition the scene to match the reported bounds. Assumes a scene with a
  // floor whose left back corner is at (0, 0, 0) and is 1 meter square.
  let bounds = frameOfRef.bounds;
  if (isRectangle(bounds)) {
    scene.translateX(bounds[0].x);
    scene.translateZ(bounds[0].z);
    scene.scaleX(bounds[2].x - bounds[0].x);
    scene.scaleZ(bounds[2].z - bounds[0].z);
  } else {
    // handle the polygon bounds;
  }
} else {
  // Use default bounds. (2 meters square, centered at the origin)
  scene.translateX(-1.0);
  scene.translateZ(-1.0);
  scene.scaleX(2.0);
  scene.scaleZ(2.0);
}
```

**Comment by huningxin** [comment]
> If we don't provide this directly with the WebVR API, I think it would be acceptable to provide a reference function.

There is [an approximation algorithm for finding the largest rectangle inside a non-convex polygon](https://d3plus.org/blog/behind-the-scenes/2014/07/08/largest-rect/) of [d3plus](https://github.com/alexandersimoes/d3plus).

Based on the algorithm, I put together a simple sample to showcase the usage of polygon bounds: https://huningxin.github.io/bounds/.

![image](https://cloud.githubusercontent.com/assets/1005673/26820326/0dd565ae-4ad5-11e7-9cd8-27534548df5c.png)

The sample render outer polygon bounds in yellow and largest rectangle within the polygon in white. You can change the bounds shape (Polygon or Rectangle) in control to see the result.

The sample uses `bounds` directly if it is a rectangle, otherwise it leverages `d3plus.geom.largestRect` to calculate the largest rectangle as:

```js
function getLargestRectFromBounds(bounds) {
  if(isRectangle(bounds)) {
    return bounds;
  } else {
    let poly = [];
    for (let i = 0; i < bounds.length; ++i) {
      poly.push([bounds[i].x, bounds[i].z]);
    }
    let lr = d3plus.geom.largestRect(poly, {angle: [0, 90], nTries: 1000})[0];
    if (lr.angle === 0) {
      return [{x: lr.cx - lr.width/2, z: lr.cy - lr.height/2},
              {x: lr.cx + lr.width/2, z: lr.cy - lr.height/2},
              {x: lr.cx + lr.width/2, z: lr.cy + lr.height/2},
              {x: lr.cx - lr.width/2, z: lr.cy + lr.height/2}];
    } else if (lr.angle === 90) {
      return [{x: lr.cx - lr.height/2, z: lr.cy - lr.width/2},
              {x: lr.cx + lr.height/2, z: lr.cy - lr.width/2},
              {x: lr.cx + lr.height/2, z: lr.cy + lr.width/2},
              {x: lr.cx - lr.height/2, z: lr.cy + lr.width/2}];
    }
  }
}
```
For the test data, the polygon is captured from [Oculus guardian system](https://developer.oculus.com/documentation/pcsdk/latest/concepts/dg-guardian-system/) by `ovr_GetBoundaryGeometry` with `ovrBoundary_Outer`. While the rectangle is from `ovr_GetBoundaryGeometry` wtih `ovrBoundary_PlayArea`.

**Comment by huningxin** [comment]
## Option 1: replace rectangle bounds with polygonal bounds

### Proposed IDL
```js
interface VRCoordinateSystem : EventTarget {
  Float32Array? getTransformTo(VRCoordinateSystem other);
};

interface VRFrameOfReference : VRCoordinateSystem {
  readonly attribute sequence<VRStagePoint>? bounds;
  attribute EventHandler onboundschange;
};

interface VRStagePoint {
  readonly attribute double x;
  readonly attribute double z;
};
```

### For implementation

| attribute | WinMR | OVR | OpenVR |
|-----------|---------|-------|----------|
| `bounds` | `TryGetMovementBounds` | `ovr_GetBoundaryGeometry` with `ovrBoundary_Outer` or with `ovrBoundary_PlayArea` | `GetPlayAreaRect` |

### For content

Content needs to calculate the rectangle if the bounds is not a rectangle. As investigation of  https://github.com/w3c/webvr/issues/228#issuecomment-306419396, the implementation is not trivial and not widely available on web community. 

## Option 2: add polygonal bounds while keep rectangular bounds

### Proposed IDL
```js
interface VRCoordinateSystem : EventTarget {
  Float32Array? getTransformTo(VRCoordinateSystem other);
};

interface VRFrameOfReference : VRCoordinateSystem {
  readonly attribute VRStageBounds? bounds;
  attribute EventHandler onboundschange;
};

interface VRStageBounds {
  readonly attribute VRStageRect rect;
  readonly attribute sequence<VRStagePoint>? polygon;
};

interface VRStageRect {
  readonly attribute double minX;
  readonly attribute double maxX;
  readonly attribute double minZ;
  readonly attribute double maxZ;
};

interface VRStagePoint {
  readonly attribute double x;
  readonly attribute double z;
};
```

### For implementation

| attribute | WinMR | OVR | OpenVR |
|-----------|---------|-------|----------|
| `bounds.rect` | calculated from `TryGetMovementBounds` | `ovr_GetBoundaryGeometry` with `ovrBoundary_PlayArea` | `GetPlayAreaRect` |
| `bounds.polygon` | `TryGetMovementBounds` | `ovr_GetBoundaryGeometry` with `ovrBoundary_Outer` | unavailable |

### For content

For simple usage, content can use `bounds.rect`. The `bounds.polygon` can be used for advanced usage if it is available, like visualize the bounds in the scene.

## Summary
According to native capability mapping, option 2 seems to have better coverage. For content, option 2 looks better to support both simple and advanced usages. And option 2 has better WebVR 1.1 back compatibility. 

After comparing the two options, I feel option 2 might be better.

@toji @kearwood @NellWaliczek , what do you think?

**Comment by toji** [comment]
Just pushed a pull request (#241) for this before I saw the latest comment, but happily we seem to be in agreement. The IDL I proposed is a bit different, but ultimately I came to the same conclusion as you that the Option 2 you list is a better route.

**Comment by huningxin** [comment]
I am happy that Option 2 of https://github.com/w3c/webvr/issues/228#issuecomment-307338737 aligns to #241. Will provide inputs there. Thanks!

**Comment by huningxin** [comment]
Close with #241 merged. Thanks!

**Comment by NellWaliczek** [comment]
During the course of finishing #409, a comment was filed to change the `boundsGeometry` attribute from being an arbitrary array of points to instead be an axis-aligned XZ rectangle.  The reasoning was that on systems with arbitrary geometry, developers have been saying that they would prefer the rectangle rather than having to compute a rectangle themselves.

Rather than removing `boundsGeometry`, I’d recommend adding an additional property  `boundsRectangle` so that we preserve providing the raw boundary data if developers want it.

Does anyone object to this?  This may put more of a burden on some UA to compute the boundary rectangle on top of the raw data available.

**Comment by cwilso** [comment]
Resolved at FTF: Nell will put together a PR to leave the existing bounds and also add a new attribute to XRBoundedFrameOfReference.
