### ISSUE TITLE
auto-commit script to update html based on .bs files doesn't appear to be functional

### ISSUE THREAD

**Issue by dlibby-** [immersive-web/webxr#239]
The last few commits to touch the 1.1 spec haven't resulted in updated html (https://github.com/w3c/webvr/commits/master/spec/1.1/index.bs). I've created a PR to update the html in the meantime:

**Comment by dlibby-** [comment]
https://github.com/w3c/webvr/pull/238

**Comment by toji** [comment]
Doing some investigation on this, it appeared one of the problems was that it was trying to push to a gh-pages branch that didn't exist at the time. (We are currently serving the page from master.) That makes sense, can't have the script pushing to the master branch on every push to master. ;)

I re-added that branch (but hadn't redirect the GitHub page to it yet) and sent through e2e3e17e5858d88fdf32e5d8a297fe22721bb8c8 to test it, but while the travis script appears to have run without error the branch was not updated. Unsure if it's a permissions issue, script issue, or something else. Curious is @cvan has any insight, and in the meantime I'll keep looking.

**Comment by anssiko** [comment]
Recently, Travis CI deploy to GitHub Pages has been failing elsewhere too, felt it myself in https://github.com/w3c/permissions/pull/146#issuecomment-306129351.

Looping in @mounirlamouri if he finds the common denominator between https://github.com/w3c/permissions/blob/master/deploy.sh and https://github.com/w3c/webvr/blob/master/scripts/deploy.sh that causes both to fail. 

@mounirlamouri is the script you use for w3c/permissions a custom one or borrowed from somewhere? If the latter, would like to understand if deploy is working on any other repo using it under the w3c GitHub org.

**Comment by mounirlamouri** [comment]
As it happen, the CI was doing its job and there was an issue in `index.bs` ;) I've sent a commit to fix it.
w3c/permissions is back green: https://travis-ci.org/w3c/permissions 

/CC @marcoscaceres who wanted me to fix this too.

**Comment by anssiko** [comment]
@mounirlamouri, thanks! I'll owe you (and @marcoscaceres) a :beer: at TPAC, if you're around :-)

@cvan, bikeshed builds https://github.com/w3c/webvr/commits/master/spec/1.1/index.bs without errors or warnings, so this was not related to the w3c/permissions deploy issue after all.

**Comment by marcoscaceres** [comment]
@mounirlamouri, awesome! TY!

**Comment by toji** [comment]
I've got this fixed now. Preferred pattern will be that the HTML doesn't exist at all in the master branch, and is built and deployed automatically to gh-pages. Probably want to put some check in place that fails pull requests if they include a pre-build HTML file.
