### ISSUE TITLE
Standardise with W3C

### ISSUE THREAD

**Issue by cvan** [immersive-web/webxr#24]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Monday Feb 29, 2016 at 13:25 GMT_
_Originally opened as https://github.com/MozVR/webvr-spec/issues/16_

---

**Comment by cvan** [comment]
<a href="https://github.com/toji"><img src="https://avatars.githubusercontent.com/u/805273?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toji](https://github.com/toji)**
_Monday Feb 29, 2016 at 17:47 GMT_

----

Speaking to Alex Russell and Chris Wilson at Google, it sounds like a good route to go may be setting up a W3C community group. It's supposed to be a pretty lightweight process that provides some basic IP protections. Worth looking into IMO.

**Comment by cvan** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Monday Feb 29, 2016 at 22:21 GMT_

----

Not sure this is the right place, but I proposed a Community Group here: https://www.w3.org/community/groups/proposed/#webvr

We're talking to David Baron here at Mozilla to see if there's anything special we should do too.

**Comment by cvan** [comment]
<a href="https://github.com/toji"><img src="https://avatars.githubusercontent.com/u/805273?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toji](https://github.com/toji)**
_Monday Feb 29, 2016 at 22:33 GMT_

----

Looks like the right place to me! Registered my support for the API on there.

**Comment by cvan** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Wednesday Mar 02, 2016 at 12:03 GMT_

----

[We have a community group!](https://www.w3.org/community/webvr/)

**Comment by cvan** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Thursday Mar 03, 2016 at 19:12 GMT_

----

@toji: could you join the community group as a participant?

**Comment by cvan** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Thursday Mar 03, 2016 at 19:19 GMT_

----

@toji To move things forward you have to join the community group as a participant. Basically you have to show up in this page: https://www.w3.org/2000/09/dbwg/details?group=87846&public=1&order=org
Someone with w3c super powers have to manually accept you as participant. Alex Russell might be able to do it for you.

**Comment by cvan** [comment]
<a href="https://github.com/toji"><img src="https://avatars.githubusercontent.com/u/805273?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toji](https://github.com/toji)**
_Thursday Mar 03, 2016 at 21:05 GMT_

----

I'm working on joining, there's some (minor) hoops to jump through on the Google side. I'll let you know when I know more.

**Comment by cvan** [comment]
<a href="https://github.com/gombos"><img src="https://avatars.githubusercontent.com/u/1522773?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gombos](https://github.com/gombos)**
_Thursday Mar 03, 2016 at 21:35 GMT_

----

Mike Blix and me are working on joining the CG as well from Samsung.

**Comment by cvan** [comment]
<a href="https://github.com/toji"><img src="https://avatars.githubusercontent.com/u/805273?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toji](https://github.com/toji)**
_Friday Mar 04, 2016 at 21:02 GMT_

----

Hoops have been jumped! I'm now a participant in the group. :D

**Comment by cvan** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Friday Mar 04, 2016 at 21:08 GMT_

----

@toji Welcome

**Comment by cvan** [comment]
<a href="https://github.com/louaybassbouss"><img src="https://avatars.githubusercontent.com/u/1138409?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [louaybassbouss](https://github.com/louaybassbouss)**
_Wednesday Apr 06, 2016 at 12:09 GMT_

----

I will also join the CG from [Fraunhofer FOKUS](https://www.fokus.fraunhofer.de/en)

**Comment by NellWaliczek** [comment]
Community group has existed for quite some time.  Working Group creation is being tracked separately
