### ISSUE TITLE
Gamepad API for WebVR button/axis input

### ISSUE THREAD

**Issue by nondebug** [immersive-web/webxr#298]
There are good reasons for not trying to extend Gamepad to support the full range of VR input device functionality, but it would be great if VR controllers were also exposed as Gamepads so they could be used more easily with non-VR applications. Here's a proposal for how that might be accomplished, based off the IDL in the latest WebVR input explainer.

[Gamepad API for WebVR input](https://docs.google.com/document/d/1nr7AdK3KcS3k5usvUU2W6R_feSlSGVFMYHqqzI2pC0c)

**Comment by NellWaliczek** [comment]
Closed in favor of #392
