### ISSUE TITLE
Presentation API with VR capable displays

### ISSUE THREAD

**Issue by anssiko** [immersive-web/webxr#304]
The [Second Screen Working Group](https://www.w3.org/2014/secondscreen/) identified the following use cases for [Presentation API](https://w3c.github.io/presentation-api/) with VR capable displays, discussed in https://github.com/w3c/presentation-api/issues/444:

>* Attaching a wired VR headset to a [controlling user agent](https://w3c.github.io/presentation-api/#dfn-controlling-user-agent) (e.g., PC) and launching a presentation of WebVR content to the headset from that PC.
>* Initiation of [presentation](https://w3c.github.io/presentation-api/#dfn-receiving-browsing-context) on another display/device while viewing WebVR content with a headset.  The other display could support VR content or be a traditional flat screen.
>* Automatically starting [presentation](https://w3c.github.io/presentation-api/#dfn-receiving-browsing-context) when an external VR headset is attached to PC.

We already received feedback from @toji (thanks!) and discussed the topic at the Second Screen TPAC F2F meeting ([minutes](https://www.w3.org/2017/11/06-webscreens-minutes.html#x18)) two weeks ago.

**Proposed resolution:** no Presentation API spec changes needed, required changes are implementation details. Capability detection for VR displays (for Presentation API) is a nice-to-have feature, currently not prioritized (tracked in https://github.com/w3c/presentation-api/issues/348).

All - If you have further feedback, please chime in on the related Presentation API issue https://github.com/w3c/presentation-api/issues/444

@toji @cvan, feel free to close this issue when you think the wider WebVR Community Group has had adequate time to review the proposal and provide feedback. We'll close the upstream issue when you acknowledge all feedback from this community has been received.

**Comment by mfoltzgoogle** [comment]
Gentle ping @toji @cvan, if the proposed resolution above looks good then you can close this out.

We are considering [additional modes of use](https://github.com/w3c/presentation-api/issues/347) for the Presentation API that don't require a full navigation/reload; that seems to address the concern with the first use case.

But I think it would make sense to start a new thread of discussion when those plans are more concrete.

**Comment by toji** [comment]
Proposed resolution looks good to me.
