### ISSUE TITLE
Multiview rendering: is explicit requesting of WEBGL_multiview required?

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/webxr#312]
I think we should clarify in the spec and explainer whether getExtension("WEBGL_multiview") is required for multiview to work or not. I think, it should be required, even though, in the case of "opaque multiview framebuffer" the dev doesn't directly deal with the WebGL extension.

**Comment by toji** [comment]
This is a good point. I agree that the extension should be explicitly requested prior to the creation of the `XRWebGLLayer`. I'll put together a quick explainer fix for it.
