### ISSUE TITLE
Define behaviour and document `devicechange` event emitted on `navigator.xr`; update spec Example 1 to include `onXRAvailable`

### ISSUE THREAD

**Issue by cvan** [immersive-web/webxr#322]
Currently, only this [`Example 1`]( https://immersive-web.github.io/webxr/spec/latest/#dom-xr-ondevicechange) is shown in the latest spec:

```js
navigator.xr.requestDevice().then(device => {
  // Resolves to an XRDevice if one is available, or to null otherwise.
  if (device) {
    onXRAvailable(device);
  }
}).catch(error => {
  // An error occurred while requesting an XRDevice.
  console.error('Unable to request an XR device: ', error);
});
```

We ought to have an additional example (especially at the `dom-xr-ondevicechange` anchor) that shows how to listen for `devicechange`.

I'll make a PR, but I'll brainstorm here first (adapted from code snippets in the [Explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md#lifetime-of-a-vr-web-app)):

```js
navigator.xr.addEventListener('devicechange', checkForXR);

function checkForXR () {
  return navigator.xr.requestDevice().then(device => {
    onXRAvailable(device);
  }, err => {
    if (err.name === 'NotFoundError') {
      // No XRDevices available.
      console.error('No XR devices available:', err);
    } else {
      // An error occurred while requesting an XRDevice.
      console.error('Requesting XR device failed:', err);
    }
  });
}
```

From the latest [WebXR Explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md#acquiring-a-device):

> Pages can listen to the `devicechange` event emitted on `navigator.xr` to respond to changes in device availability after the page loads. (XR devices already available when the page loads will not cause a `devicechange` event to be fired.)

Some open questions from me:

1. **Should the event emitted include additional properties (e.g., `device` and `reason`) or data in the event's `detail` object?** Personally, I'd opt for the addition of properties (à la the Gamepad API's [`gamepad` property](https://w3c.github.io/gamepad/#gamepadevent-interface)). Alternatively, we could keep things as is and recommend developers use the `devicechange` event as a signal that the device is changed, requiring developers to refer to the original `XRDevice` itself (à la the Sensor API's [`reading` event](https://w3c.github.io/sensors/#sensor-onreading).
2. **During a page navigation, if a XR session is still active, should the page still be required to call `navigator.xr.requestDevice` to know that a VR session is active and a device is presenting?** (See [this](https://github.com/immersive-web/webxr/blob/master/explainer.md#detecting-and-advertising-xr-mode) and [this](https://github.com/immersive-web/webxr/blob/master/explainer.md#non-exclusive-sessions-magic-windows), which both seem to imply that `navigator.xr.requestDevice` still needs to be called in the document lifecycle.)

**Comment by toji** [comment]
This issue appears to be resolved by #405. Closing,
