### ISSUE TITLE
Move/Remove `XRDevice.external`

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#326]
@ddorwin asked me what the purpose of `external` was on the `XRDevice`, and in the process of explaining it to him I realized that our reasoning for having this particular property exposed so early on is no longer applicable.

In WebVR (and early WebVR 2.0) exposing this property as early as possible was necessary because to enable simple mirroring the developer had to create a WebGL context with `preserveDrawingBuffer: true`. Since we've moved away from using the context default backbuffer directly, though, developers no longer need to make these type of initialization decisions prior to `XRSession` creation. As a result, I think that this value should be moved to the `XRSession` to reduce the minor amount of fingerprinting it would provide (and because it feels more sensible on the session anyway).

And while we're here, it seems like "external" maybe doesn't communicate what we want it to any more? Specifically, now that the initialization concerns are moot, what the developer really wants to know is "Is the 2D page still visible while this session is active?" That would allow them to make intelligent choices about whether or not to render 3rd person views of the scene or expose demo driver controls. And the answer to that question isn't actually dictated by the way the hardware is configured. Simple example: If I have a desktop HMD with a completely in-VR browser (say MS Edge?) then the page will be obscured during exclusive sessions even though the hardware is technically external to the main screen. AS such we probably want to reconsider the name.

I don't have any great suggestions there. `pageObscured`? 😒

**Comment by kearwood** [comment]
Good points, @toji 

I'm also not sure "external" is the best way to express this.

I'm in favor of something like "pageObscured"; however, we should be considering the possibility that the page may be initially obscured and later become visible (eg, when using Windows MR which hides your desktop until you unlock it.).

Another option..  Would we serve our users well if we required pages to explicitly request a context that is mirrored on the 2d display automatically or to keep the 2d view visible instead?

**Comment by blairmacintyre** [comment]
Part of the issue might be "external to what?"

In the discussions we've had in the context of expanding to AR (that haven't shown up here yet, I don't think) there was discussion about making the various kinds of display setups more clear:  immersive (AR and VR on head-worn displays, although this might also apply to CAVEs or projection AR someday), portal (aka magic window) and some notion of a regular flat page (we called this "flat", non-surprisingly, in our polyfill).

As part of this, if there are multiple displays, including the desktop monitor (in the current case being discussed above), and it was possible to know which display the page is currently displayed on, then the programmer knows if the page is still visible when they go into immersive display mode.

In Windows MR, the web page is on the same display that is used for immersive display.  In Vive/Rift, with a desktop browser, it isn't.  On Daydream/GearVR, it's the same display.  On a hypothetical device that plugs into your phone and leaves it's display visible, it isn't on the same display either.

**Comment by toji** [comment]
> Would we serve our users well if we required pages to explicitly request a context that is mirrored on the 2d display automatically or to keep the 2d view visible instead?

Maybe I'm misreading this, but that was the intention behind mirroring by passing an `outputContext` to an exclusive session. That way the developer can specify where a mirrored view should show up, but the user agent can make intelligent decisions about whether or not it's visible and needs mirroring. So in my opinion the mirror case is well handled.

The more problematic case is when developers want to have either "demo driver" or "asymetric gameplay" modes where an external user is using the page to interact with the user in the headset. This may or may not include a non-mirrored view of the same scene the in-headset user is seeing. (Also useful for gameplay streaming.) Developers would achieve that by attaching the canvas for the WebGL context used to instantiate the XRWebGLLayer to the page like a normal WebGL app and drawing a separate view of the scene to it. (Yes, that'll soak up a fair amount of rending power, but since this technique is currently only applicable on PCs that somewhat mitigates itself.)

Actually, now that I'm thinking about it maybe we don't actually need a property for that at all? Maybe all we need is a best practice that says "Don't just render a 3rd person view by default. Put a button on the page once an exclusive session has started that toggles it on and off." That way you only get that mode if you can see the button and click it without exiting the session, which implicitly means that you have access to both the XR content *and* the 2D page simultaneously. Tada! Now we don't have to care about the hardware configuration (which is problematic for all the reasons Blair points out), and instead we have a feature who's use is self-selecting in the right environments.

**Comment by toji** [comment]
Put up a pull request to remove the attribute. Please review!

**Comment by toji** [comment]
Closed by merging #328. Per the CG call, there's some larger issues that need addressing around how we communicate device shape and functionality, and those should be handled more holistically than a simple boolean like this would allow.
