### ISSUE TITLE
Suggest additional use case: "encapsulated XR apps"

### ISSUE THREAD

**Issue by JeroMiya** [immersive-web/webxr#327]
One very compelling use case I haven't seen featured in the WebXR materials I've browsed so far is any kind of standardization of what I'll call, for lack of a better term, "encapsulated XR apps". These are AR or VR apps which may be embedded into another environment. They are either pinned to the real world in the case of an AR headset like the Hololens, or pinned to a virtual world as is done with Windows Mixed Reality or the web-based enclosures supported in AltSpaceVR. Multiple encapsulated apps may be "pinned" simultaneously into the same environment.

Open question: What would be the requirements of such apps beyond typical WebXR applications? Enclosures? Additional coordinate spaces? Negotiating access to shared devices between multiple apps? Support for pinning enclosures into another web app?

**Comment by speigg** [comment]
This is one of the questions we have been exploring in the Argon platform (https://www.argonjs.io). In brief, I see such apps as being AR apps, which can augment any type of “reality”, whether that is “physical reality” or “virtual reality”. The basic requirement for such apps is that the platform provide the pose of the device within a meaningful coordinate system (along with projection matrices, etc.). In order for a VR app to be “augmentable”, it must expose it’s  own internal coordinate system, and make it available to AR apps.

**Comment by JeroMiya** [comment]
Yeah, if the existing XR spec and API for AR apps serves this use case, that would be great. If so, I'd still like to get this use case added to the existing lists where use cases for WebXR are stated in the spec and other docs. Then, when changes to the spec are proposed, they can be evaluated to ensure it's suitable for this particular use case. This, as opposed to only supporting the use case where only one AR app is open at a time, either on a mobile device via ARCore/ARKit style AR or on a pass-through AR device, like hololens.

**Comment by blairmacintyre** [comment]
I think this is going to be beyond the scope of the initial WebXR Device API.  However, the concept of being able to display multiple bits of content at once is something that keeps coming up, and many folks are interested in.

There is a tension, though, about how best to do it, and what kinds of restrictions to impose.  Some folks, for example, are suggesting that a new declarative framework be defined that limits the kind of content, and thus allows more control over performance, etc.

I'd suggest tossing this question over in the https://github.com/immersive-web/proposals repository (the idea is that folks create issues there for things they'd like to see happen, and when there's enough interest in tackling one, people break off and work on them.)

**Comment by NellWaliczek** [comment]
This issue was moved to immersive-web/proposals#26
