### ISSUE TITLE
What are the expectations about user-permission?

### ISSUE THREAD

**Issue by blairmacintyre** [immersive-web/webxr#331]
I would like to clarify in the proposal what, if any, expectations there are about what a UA should do regarding obtaining user permission.

The current WebVR spec just specifies user-gesture, which is inadequate.  

Given the discussions surround the `devicemotion` API (not here, elsewhere), I would anticipate that any access to XR device sensors will absolutely require some form of explicit user permission.  We should make this clear.

**Comment by cvan** [comment]
I think this is a dupe of #249. @blairmacintyre want to check and confirm that that issue covers your questions?

**Comment by cvan** [comment]
I'm closing this; feel free to reopen if I improperly closed this and it's not covered by #249 (sorry! thanks!)
