### ISSUE TITLE
Trying to avoid additional canvas when mirroring

### ISSUE THREAD

**Issue by TrevorDev** [immersive-web/webxr#341]
I'm on the BabylonJS team and we are working on adding WebXR support. When prototyping I ran into an issue when trying to avoid the use of multiple canvases.

I managed to modify Babylon to get prototypes working 🙏 in chrome canary by following these samples:
https://github.com/immersive-web/webxr-samples/blob/master/magic-window.html 
https://github.com/immersive-web/webxr-samples/blob/master/mirroring.html
but am wondering if there is a way to reuse an existing canvas for mirroring/magic window scenarios instead of overlaying canvases like in the samples.

Currently most Babylon projects start with a single canvas and a webGL context to render a scene. When starting to displaying on the hmd in XR I can set the xr device on the existing webGL context to render to the headset with. However, based on the samples, to mirror the display another canvas is needed to be created with a context of xrpresent. Since the original canvas is no longer used for displaying is there any method to use it as the mirroring canvas to avoid the additional complexity of managing multiple canvas/contexts or is there something I'm missing?

**Comment by brianchirls** [comment]
I'm with @TrevorDev on this one. I'm in the process of porting my business/enterprise data viz applications over to XR and am finding this aspect of it extremely cumbersome, particularly when it comes to "spectator" mode. There are *very* few examples out there that do mirroring, much less a third-person spectator view. Three.js (and by extension, A-Frame) doesn't support it in core, and @toji's [samples](https://github.com/immersive-web/webxr-samples) are good but artificial. So it doesn't seem like the use case has been well tested in practice.

For non-entertainment, non-gaming applications, assume that XR is not the primary concern. Most users will want a screen view first and only optionally enter XR later. They will almost always want a spectator view if the device supports it. Further, almost all WebVR/WebXR work in the wild has a full-window canvas. For business applications, the canvas is likely to be part of a greater page layout, so it's not as simple as just setting everything to `window.innerWidth` by `window.innerHeight`. Layout becomes difficult to reason about, and keeping track of multiple canvases only makes it worse.

I'm sorry I haven't had time to be involved in these discussions the past several months. I should be more available now, if someone wants to talk through these use cases in more detail.

**Comment by toji** [comment]
FWIW this is an issue that may be made significantly easier with an upcoming proposal for allowing a single session to transition between inline and immersive modes. (Wouldn't solve the issue entirely but I do think it would make it more tractable.)
