### ISSUE TITLE
resetpose event timing requirements

### ISSUE THREAD

**Issue by paezagon** [immersive-web/webxr#354]
Should the spec require that the resetpose event listeners be triggered before any frame with the new pose data is available for use?

https://immersive-web.github.io/webxr/#eventdef-xrsession-resetpose

**Comment by toji** [comment]
That sounds very logical to me. I'll put together a PR to add language around that and see if anyone is aware of issues with doing so, but I have a hard time seeing why it would be problematic.

**Comment by toji** [comment]
Pull request is up to make this explicit.

**Comment by paezagon** [comment]
Cool, thanks!
