### ISSUE TITLE
Getting button data from Input API

### ISSUE THREAD

**Issue by AlbertoElias** [immersive-web/webxr#362]
I'm a big fan of the new Input API and how it simplifies the most common use cases for interacting with XR controllers, but for Oculus, Vive and knuckle controllers, many applications will want to render a hand model with different poses depending on the buttons being touched or pressed. Even the Vive controller is used for this, showing a fist when the grip buttons are pressed.

I think it's very important for WebXR site to be able to give the user hand presence, and I need it for the kind of interactions I'm working on. It's something that can be accomplished with the current Gamepad API method and I wouldn't like to lose it when moving to WebXR.

What are the concerns over giving developers that information with the current Input proposal?

**Comment by toji** [comment]
The primary concern is that we're not confident we can actually deliver it. Case in point: It's not clear if OpenXR is going to provide button data in a way that allowed hand poses to be inferred, and as such providing enough data to render well posed hands is likely to be an extension in that API. Given that we don't have a good answer for how that will play out on the native side, it's safest for WebXR to stick to a known-good subset of features.

When we see the native side of things settle down expect the web APIs to work aggressively to catch up.

**Comment by machenmusik** [comment]
Will there be sufficient information to use the gamepad API in conjunction with WebXR Input API to accomplish this until the lower layers settle down?

**Comment by AlbertoElias** [comment]
I would also like to know if we'll be able to continue using the gamepad API to expose these behaviours as being able to give our users hand presence is very important for many VR experiences.

I thought WebXR didn't depend upon OpenXR, as seems to be mentioned in the explainer and in #199 and that it actually depended on the different runtimes (Oculus, SteamVR, WMR..) which do expose button information. Would you mind clearing this up?

Thanks for the explanations!

**Comment by toji** [comment]
WebXR does not depend on OpenXR, but we DO have to be aware of it's structure and limitations, and design our API in a way that doesn't inadvertently exclude it, given that we anticipate that at some point it will drive a non-trivial amount of hardware.

This is similar to how the web as a platform does not have a "dependency" on iOS devices, per-say, but if we know that for one reason or another a specific feature was likely to never be implemented on iOS hardware everyone is generally rather reluctant to introduce said feature to the web because it automatically excludes a large number of potential users.

**Comment by AlbertoElias** [comment]
Yeah, that makes sense, thanks.

And what about continuing to expose current gamepad api behaviour?

**Comment by dmarcos** [comment]
I've been quietly following the input API discussion. Thanks all for the good work. Happy to see things coming along.

I'd like to make sure we don't lose capabilities in the transition to the new API, and existing content can be ported over WebXR. Popular and great experiences like [Mozilla Hubs](https://hubs.mozilla.com),  [Sketchfab](https://sketchfab.com/models/69be107ca5234ca8a9fcff6ba6851e9e), [A-Painter](https://aframe.io/a-painter/), [Supercraft](https://supermedium.com/supercraft/) or [Supermedium](https://www.supermedium.com/) rely on multiple buttons and axis for their input models.

There are also young startups like [Panomoments](https://www.panomoments.com/) or [3Data](https://3data.io/) choosing the Web as the platform and breaking new ground in interactive media. We want to make sure that the new API keeps enabling them.

The [A-Frame community](https://aframe.io/blog/) is experimenting with novel interaction techniques. It's awesome to see this happening on the Web. 

No preference for a particular solution as soon as there's a way to preserve existing functionality:

1. Buttons and axis are incorporated into [XRInputSource](https://immersive-web.github.io/webxr-reference/webxr-device-api/xrinputpose.html)
2. We rely on the Gamepad API for buttons and axis (no pose) and there's a mechanism to match a Gamepad and XRInputSource
3. We keep the current Gamepad API extensions as an interim solution until XRInput matches capabilities.

**Comment by AlbertoElias** [comment]
Another point I'd like to make is that the new XR Input API seems to be rather high level. It's a very nice API for the most common use cases, but there is no underlying API that could express it, so I wouldn't say it follows the Extensible Web Manifesto.

I understand that, specially for a lower level API, it´s important to get it right and get something that makes sense as it would be harder to change later on. 

With that, and understanding that the different stakeholders want to get the WebXR API out as soon as possible, I think the third suggestion made by @dmarcos would be the best, and prioritise a better API that works nicer with XR Input even if it doesn't make it to the initial WebXR stable release

**Comment by jonobr1** [comment]
Echoing @dmarcos. At https://www.with.in and https://vr.with.in this high level API will simplify many things for us — which is great!

However, in addition to displaying a corresponding branded VR controller to the one you're holding we have use cases and motivations for accessing the other buttons. I know this isn't the majority of circumstances, but in our case creating parity with other high-fidelity native VR applications is important and a deciding factor for continued development.

**Comment by NellWaliczek** [comment]
Consolidating discussion into #392
