### ISSUE TITLE
Clarification of mouse behavior when in an exclusive view

### ISSUE THREAD

**Issue by leweaver** [immersive-web/webxr#363]
There is currently no explicit mention in the explainer of how the user agent should treat the mouse when an exclusive view is active on desktop machines. The basic question is: should the mouse be hidden from the desktop when a user is wearing the headset? The main argument for this is user safety; it would prevent accidental mouse clicks outside of the page content while wearing the headset.

In WebVR there was some inconsistency in how different platforms handle this. In WMR, the mouse cursor is disabled when input is routed to the headset; Edge signals this to the page via the `VRDisplayPointerRestricted` and `VRDisplayPointerUnrestricted` events (as Nell mentioned in #299). The page had the option of taking pointerlock in response to a `VRDisplayPointerRestricted` event if it required position delta's/button press information.

In WebXR, we now have the option of treating the mouse as an `XRInputSource` with `targetRayMode=gazing`, which will alleviate the need for pages to take pointerlock if they just want to receive mouse clicks. It may make sense to only enable this source if the mouse is hidden, and the page has not taken pointerlock.

**Comment by Manishearth** [comment]
I think there's content on the web (e.g threejs) which allows you to interact with the page (mostly, the "exit VR" button) even when the headset is worn.

I don't think user agents can actually tell if the headset is currently actively being worn so it seems like we should not do anything here?

**Comment by cabanier** [comment]
FWIW both Oculus Quest and Magic Leap know when a headset is worn. I'm unaware of any desktop solutions that do this.

**Comment by Manishearth** [comment]
Thanks. Yeah, this only really applies to tethered headsets. I'm wary of speccing anything that can't be uniformly implemented where applicable.

**Comment by Manishearth** [comment]
This should probably be done as a line in the spec saying that immersive mode doesn't restrict pointers, with a note saying that folks should use the pointerlock API if they want to do so.
