### ISSUE TITLE
hasOrientation (& hasPosition) flags

### ISSUE THREAD

**Issue by cvan** [immersive-web/webxr#38]
<a href="https://github.com/mkeblx"><img src="https://avatars.githubusercontent.com/u/293795?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mkeblx](https://github.com/mkeblx)**
_Wednesday Apr 06, 2016 at 21:39 GMT_
_Originally opened as https://github.com/MozVR/webvr-spec/issues/30_

---

What is the use case of these `VRDisplayCapabilities` flags on `VRDisplay`? Especially `hasOrientation` as hard to imagine HMD not having orientation tracking.

Also note specifically renamed from `VRDevice` to `VRDisplay` to focus spec on covering use case of HMDs (mainly) and not generic tracked VR devices.

Additionally can be figured out by null or not state of orientation and position data.

**Comment by cvan** [comment]
<a href="https://github.com/toji"><img src="https://avatars.githubusercontent.com/u/805273?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toji](https://github.com/toji)**
_Wednesday Apr 06, 2016 at 22:27 GMT_

----

The difference between a `null` position and `hasPosition`has been explained by @kearwood in the past with the "Cat scenario". If a cat walks in front of my tracking camera/laser box and tracking drops, it may appear that the device has no position tracking at all if all you are looking at is the pose data. `hasPosition == true && pose.position == null` says "I have the ability to track your position, I'm just not able to do it right now."

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#2
