### ISSUE TITLE
XRFrameOfReferenceTypes underdefined in XR spec

### ISSUE THREAD

**Issue by mprafson** [immersive-web/webxr#380]
There are references to "head-model", "eye-level", and "stage" in the spec, but they are mostly undefined.

I see "stage" is defined here: https://immersive-web.github.io/webxr/#dom-xrframeofreferencetype-stage
Not seeing explicit definitions for "head-model" and "eye-level".

**Comment by toji** [comment]
Added explicit definitions for all the types in 898fdcb091779b4a84de407b81a79461edcb484e
