### ISSUE TITLE
normative requirements in security considerations section might be problematic

### ISSUE THREAD

**Issue by dbaron** [immersive-web/webxr#386]
I was looking at the [Security, Privacy, and Comfort Considerations section](https://immersive-web.github.io/webxr/#security) and noticed that it has a number of normative requirements with MUST and SHOULD in it.

I think this is generally a sign that something is wrong, for the following reasons:
* an implementor implementing the specification will generally be reading the normative text defining the features that they're implementing, and thus might miss the extra requirements in the security considerations section.
* presence of normative requirements in the security considerations section might also be a sign that parts of the spec's processing model aren't as well defined as they should be, since text might sometimes end up in the security considerations section because it belongs in a description of concepts or processing model that should be somewhere in the spec but is currently missing, and therefore the text ends up in the security considerations section by default.

I'm not certain how much these considerations apply to this spec in particular, though.

**Comment by NellWaliczek** [comment]
Thanks for raising this issue!  In general, we're going to need to do a more detailed scrub of the WebXR API to address the concerns that are in the process of being documented in the immersive-web/privacy-and-security repo.  An explainer is being authored and concrete issues will be filed in the webxr repo once that explainer has gotten agreement in a wider review.  In the meantime, I'm going to close this issue in favor #393
