### ISSUE TITLE
Address concerns outlined in immersive-web/privacy-and-security

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#393]
A repo has been created to create an explainer regarding threat vectors, user consent issues, privacy, security, and related issues.  That repo can be found here: https://github.com/immersive-web/privacy-and-security
This issue tracks the need to review and evaluate the explainer document in that repo when it's ready and submit PRs to address the concerns appropriately.

**Comment by johnpallett** [comment]
Proposed design for this is here: https://github.com/immersive-web/webxr/pull/638
