### ISSUE TITLE
Light estimation for AR

### ISSUE THREAD

**Issue by kyungtae** [immersive-web/webxr#401]
Light estimation is one of the key features of AR platforms (ARCore, ARKit,...),
and is essential for creating realistic AR contents.
However, current WebXR spec doesn't support it.

So, how about add the "light estimation" to the XRFrame  like below?

interface XRFrame {
  ...
  readonly attribute Float32Array? lightEstimate;
}

IMHO, it should be included in XRFrame, because it changes throughout the frame change,
and it should be Float32Array because the lightEstimate is cosist of lightIntensity and color correction.
- ArCore : 4 float values ( R, G, B, intensity)
    https://developers.google.com/ar/reference/java/com/google/ar/core/LightEstimate
- ArKit : 2 float values (intensity, colorTemperature)
     https://developer.apple.com/documentation/arkit/arlightestimate

I experimentally implemented it on Chromium with ArCore using ArFrame_getLightEstimate ,
and checked it works well.

**Comment by cwilso** [comment]
This is currently in proposals: https://github.com/immersive-web/proposals/issues/27, so I'm going to resolve this issue for now and it should be discussed there.

FWIW, I think you're suggesting that the return types could vary depending on the underlying system (ARCore vs ARKit).  That would be a really bad thing for usability, IMO.

**Comment by kyungtae** [comment]
You're right.
I think what both platform (ArCore & ArKit) want are same - adjusting the intensity and the color of the ambient light.
The ArKit style is simpler but the ArCore style is detailed.
I think for making common API, ArKit style will be better, but I didn't mentioned it because I thought more discussion is needed for that.
