### ISSUE TITLE
supportsSession vs supportSession

### ISSUE THREAD

**Issue by dontcallmedom** [immersive-web/webxr#406]
I noticed the spec uses `supportsSession` (support*s*) on one hand, and `requestSession` on the other hand. The latter is what is more customary as far as I know; it may be too late to change this, but have we considered using `supportSession` as a method name instead?

**Comment by toji** [comment]
Definitely not too late to change it, so thanks for bringing this up!

I will say that `supportSession` sounds a bit funny to me grammatically, but I'm not against the change if there's prior art in other web APIs that suggests we should go that direction.

I'll also mention that I'm working on a refactoring of the session creation flow right now that might eliminate the need for a `support(s)` function all together, which would solve this problem nicely. 😁

**Comment by dontcallmedom** [comment]
nah, thinking some more about it, it's traditional for state-reporting operations to use the 3rd person form, so closing.
