### ISSUE TITLE
User agents should provide headset activation instructions

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#413]
While some VR platforms provide instructions on starting a VR session (e.g., inserting the phone into a Daydream View), others do not (e.g., Cardboard). Some authors created their own phone-insertion UI for Cardboard.

With WebVR, authors were able to detect the type of device via `displayName` before starting presentation. We've heard from authors that are looking to transition to WebXR that they can no longer differentiate the headsets (by design) and thus cannot determine whether to display such UI, especially before an immersive session starts and more data is available.

It seems, however, that applications should never have been trying to display such UI in the first place, and this was probably just filling a gap in what the implementation provided. While this approach may have been reasonable when there were few form factors, it's not reasonable for applications to provide appropriate instructions for all form factors or even know whether they need to. There are also additional cases to consider, such as when the user is already in a headset looking at a 2D page - it wouldn't make sense for the page to show such UI, but it might not be able to detect this case.

Thus, user agents should be responsible for showing such UI when appropriate. There probably isn't a lot of spec text to write for this, but authors should know that they do not need to and should not include such UI in their applications.

**Comment by ddorwin** [comment]
Note that since the UA is responsible for this, implementers have a lot of flexibility for what, if anything to display. For example, perhaps this does not make sense for desktop scenarios or maybe the desktop UI is displayed outside browser window. Also, implementations could allow users to disable/enable such UI, allow users to choose "Don't show this again," only display it the first N times, etc.

**Comment by Manishearth** [comment]
Fixed in #799
