### ISSUE TITLE
Body-locked content

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#416]
One thing that isn’t currently easy to do with the current WebXR APIs is adding body-locked content to a scene.  Body-locking means that content moves with the user as they walk around, but stays put when the user rotates.  An example of this sort of content would be control panels or tools that should always be in easy reach of the user.

There are a few possible approaches for adding this capability to WebXR, and to be honest I’m kinda meh about all of them.  There’s pros and cons to each one, so I’d really like to hear from the group about which one feels more sensible.  If I had to pick in a vacuum, I’d probably choose option 1.

### Add `body-locked` to XRStationaryFrameOfReferenceSubtype values

``` webidl
enum XRStationaryFrameOfReferenceSubtype {
  "eye-level",
  "floor-level",
  "body-locked",
  "position-disabled"
}
```

Functionally, the behavior is really similar to the `XRStationaryFrameOfReference` with the `position-disabled` subtype, but `body-locked` also includes neck-modeling in the pose data.  On devices with _orientation-only_ tracking, the `body-locked` subtype would behave identically to the `eye-level` subtype.

The big catch is that body-locked content is often intended to be rendered at the same time as other content which isn’t body-locked.  In other words, developers would be creating an `XRFrameOfReference` object just to use it’s `coordinateSystem` attribute in the context of another frame of reference.  This feels fairly counter intuitive to me for the common case.  However, it’s worth noting that it would actually be totally valid to use a `body-locked` frame of reference as the primary frame of reference.  I just don’t see it being very common… unless we end up telling developers that they should fall back to using it to render custom tracking loss UI?

### Add an `XRUser` type
```webidl
partial interface XRSession {
	readonly attribute XRUser user;
};

[SecureContext, Exposed=Window] interface XRUser : EventTarget {
  readonly attribute XRCoordinateSystem bodyLockedCoordinateSystem;

  attribute EventHandler onreset;
};
```

This approach removes the awkwardness of having an extraneous `XRFrameOfReference`, but it could be just as awkward to have a whole type dedicated to this (fairly small) feature.  The upside is that the usage model may be much clearer because it’s not forcing developers to use more than one frame of reference at a time.  This new type could also potentially be a good place to collect future information such as…other body parts?  On the other hand, adding new children to `XRUser` may mean the `onreset` event gets confusing.

### Adding an `XRCoordinateSystem` directly to `XRSession`
For what it’s worth, I also considered adding the `bodyLockedCoordinateSystem` directly to `XRSession`.  The big problem with that approach is that many XR hardware devices will have the ability to “re-home” the user which would cause a discontinuity in the coordinate system’s origin.  For frames of reference, this is reported via the `onreset` event which would either mean adding a similar event to `XRSession` or moving `onreset` to the `XRCoordinateSystem`.  The former seems pretty messy.  The latter implies something generic about `XRCoordinateSystem` objects that I believe isn’t true; spatial roots don’t all have the ability to experience a discontinuity of origin.  And by adding the event to that type, we’re implying something to developers about what they need to be resilient to that isn’t necessarily correct.

**Comment by blairmacintyre** [comment]
It's not really body locked.  Without a body orientation tracker separate from the head tracker, the content follows your position but it is locked to world orientation.  I don't have a good suggestion for a better name.

**Comment by thetuvix** [comment]
FWIW, we've had fairly good luck on HoloLens in implementing similar "tag-along" semantics with scripts at the app layer.

You can see our Unity Mixed Reality Toolkit code for tag-along behavior [here](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/Tagalong.cs).  This is implemented as a Unity component (MonoBehaviour) that developers can add to any Unity GameObject.  At the top of the linked file, you can see various fields like `PositionUpdateSpeed` and `SmoothingFactor`, representing the various parameters apps can adjust to affect the tagalong behavior.

**Comment by NellWaliczek** [comment]
After the F2F discussion at TPAC, it was decided to close this issue due to lack of developer interest in consuming it.  If at some point we get developer feedback requesting it be added to the platform, we can reevaluate the options described above.
