### ISSUE TITLE
Requiring multiple frames of reference

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#417]
In PR #409 an optional session creation argument was added that allows developers to block a session from being created if it will be unable to provide a specific type of frame of reference.   The current design only allows pages to block on a single frame of reference type, but it’s possible that a scene may wish to block on more than one.  For example an unbounded experience which wants to switch to a bounded experience and back again.

Naively, the simple solution would be to change the `requiredFrameOfReference` to accept an array rather than a single item.  The question is, should the `requestSession()` call reject if none of the required frames of reference are available or if at least one is unavailable.

My inclination is to reject if none are available since the `requestFrameOfReference()` call accepts an array of desired types.

Any objections?

**Comment by johnpallett** [comment]
Nell is one outcome of this that the UA could enforce privacy/security requirements for all potential session types at creation time, instead of on-the-fly? For example, if the UA hypothetically applied different policies for bounded vs. unbounded, those policies could be evaluated at session creation?

**Comment by NellWaliczek** [comment]
>For example, if the UA hypothetically applied different policies for bounded vs. unbounded, those policies could be evaluated at session creation?

I'm not entirely sure what you mean by this part... do you mean different policies based on immersive vs. inline sessions?

**Comment by NellWaliczek** [comment]
Also, to follow up, this issue was discussed at TPAC and the conclusion was that the single value should be expanded to an array in which only one type needs to be supported for session creation to succeed.  I'll get a PR posted shortly with this change.

**Comment by NellWaliczek** [comment]
Resolving this issue is on hold while we work on solutions for #423 and #424

**Comment by NellWaliczek** [comment]
Closed by #739
