### ISSUE TITLE
State and events for interstitial/warning screens

### ISSUE THREAD

**Issue by cvan** [immersive-web/webxr#42]
<a href="https://github.com/brianchirls"><img src="https://avatars.githubusercontent.com/u/492291?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brianchirls](https://github.com/brianchirls)**
_Thursday May 19, 2016 at 02:35 GMT_
_Originally opened as https://github.com/MozVR/webvr-spec/issues/34_

---

Over at webvr-polyfill, there's been a [request](https://github.com/borismus/webvr-polyfill/issues/93) for events that would fire when the Cardboard interstitial appears and disappears. I think I read @toji say somewhere that the interstitial would be built into Chrome on Android. It occurs to me that this is analogous to the Oculus safety screen and that it would be useful to know when these screens are blocking the display so the user doesn't miss any content.

Does anybody know if the Oculus SDK allows detection of this sort of thing?

It seems that there should be a boolean property on the `VRDisplay` that tells whether the screen is blocked by a warning and an event that fires when this property changes. Maybe something analogous to `document.hidden`. Alternatively, `onvrdisplaypresentchange` could wait to fire until the interstitial is cleared, but that might not make sense if different platforms vary enough in their behavior. For example, if Chrome/Android/Cardboard (or the polyfill) shows an interstitial when you tilt the device too close to vertical, then the latter approach wouldn't work.

I could imagine platforms in the future popping up warnings for various safety and comfort reasons, like: an epilepsy blocker if it detects bright flashing light, or an interruption if the frame rate drops too low.

**Comment by cvan** [comment]
<a href="https://github.com/toji"><img src="https://avatars.githubusercontent.com/u/805273?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [toji](https://github.com/toji)**
_Thursday May 19, 2016 at 05:44 GMT_

----

For the Oculus SDK I believe that any time the app isn't showing what it's rendering (whether due to the HSW or Unknown Sources screen or because Oculus Home is visible) `ovr_SubmitFrame` will return `ovrSuccess_NotVisible`. Not terribly granular, but it gives us something to work with. My first thought would be to not resolve the `requestPresent` promise until this starts returning `ovrSuccess`. (And have it submit dummy frames periodically in the background till then to test.) Maybe if it starts returning that after `requestPresent` has resolved we could knock down the rate that `VRDisplay.requestAnimationFrame` is called at to avoid spinning our wheels unnecessarily.

Same could go for the polyfill. Don't resolve the promise until the interstitial is ready to disappear.

**Comment by cvan** [comment]
<a href="https://github.com/brianchirls"><img src="https://avatars.githubusercontent.com/u/492291?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brianchirls](https://github.com/brianchirls)**
_Thursday May 19, 2016 at 12:34 GMT_

----

Sounds like a good start. I don't think slowing the frame rate is sufficient, since you may want to fully pause the experience. But we could start with this and then add in additional state and events later on if the need arises. Right?

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#27
