### ISSUE TITLE
Clarify floor-level for unbounded frame of reference

### ISSUE THREAD

**Issue by johnpallett** [immersive-web/webxr#421]
The explainers currently outline how floor level is handled for stationary and bounded frames of reference, but they leave open to the interpretation whether floor level has meaning for unbounded ones.

This may result in some platforms assuming floor level is similar to bounded frames of reference (e.g. Y=0 at the floor) and others assuming Y=0 at eye level which may cause problems if developers only test on one platform or the other.

Can guidance be provided as to whether floor level has meaning for unbounded frames of reference?

**Comment by NellWaliczek** [comment]
Floor level has no meaning on unbounded frames of reference as this type of frame of reference is one in which you can climb a hill, or go up and down stairs.  Thanks for the catch on lack of clarity.  I'll get a PR up with the clarification.

**Comment by toji** [comment]
This was a simple enough change (and Nell is busy enough with other work at the moment) that I just added a paragraph to the explainer and pushed it.
