### ISSUE TITLE
Determine fingerprinting impact of WebGL context compatibility

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#429]
It was pointed out in #427 that the `xrCompatible` flag for WebGL contexts may expose additional fingerprinting data on multi-GPU systems by enabling developers to introspect the WebGL context capabilities and debug information with and without the flag to determine if more than one GPU is present. This is similar to the additional data that may be exposed when using the `powerPreference` context creation attribute.

We should determine how much impact that change has on fingerprintability and if there's anything we should do to mitigate it (or if it's not a concern because of existing, similar techniques.)

**Comment by NellWaliczek** [comment]
Hey @johnpallett, got any thoughts on this one?

**Comment by johnpallett** [comment]
For context (ha ha) here is a list of similar [contextAttributes](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#Parameters).

**Comment by johnpallett** [comment]
Update: Our team is comfortable with this change and does not believe it poses a significant fingerprinting concern.

**Comment by NellWaliczek** [comment]
Thanks, John!  I'm a bit surprised to hear we're not more worried about exposing the fact that someone has a multiGPU system (and, through WebGL, which GPUs) without a verification of user intent.  But if that's the case, then yay!  

@avadacatavra can you confirm you're also on board with this being a non-issue?

**Comment by johnpallett** [comment]
In case it helps, a bit more background... as far as we can tell this attribute in isolation doesn't allow a developer to develop a unique device fingerprint. The attribute may represent a slight increase in entropy, but access to the data is through an API and thus visible to user agents to mitigate if necessary.

Feedback welcome if we're missing a scenario where the attribute could be used to develop a unique device fingerprint, or if we missed some other way to use this attribute to generate a strong signal.

**Comment by avadacatavra** [comment]
I'm on board with this being a non-issue 😄

**Comment by NellWaliczek** [comment]
Sounds good to me!
