### ISSUE TITLE
Provide a way for developer to supply their own transform offset.

### ISSUE THREAD

**Issue by darktears** [immersive-web/webxr#431]
Here is a context in this demo : https://darktears.github.io/demos/xr/

In that example there are two cases where the user is moved by an offset : 

- Moving the user in space during in an inline/magic window scenario. In this demo it is achieved by a virtual navpad/joystick. Say you would want to explore your hotel room without going immersive.
- Teleporting/locomotion when in immersive mode. For example moving further than the stage bounds or in 3DoF being able to move in the world.

I'm sure there will be more use cases of artificial locomotion but I believe #2 will be extremely common to see amongst WebXR experiences.

One of the current problem with the API is that it's up to the developer to basically update the view matrix before the rendering to account for that "moving" offset. The math is not impossible but it's something that we don't want developers to have to do for each frames ([see here](https://github.com/darktears/darktears.github.io/blob/master/demos/xr/demo.js#L830)). Also it slightly different in the case of a magic window vs immersive mode ([see here](https://github.com/darktears/darktears.github.io/blob/master/demos/xr/demo.js#L780)). An additional burden for the developer is that he/she has to update the controller position as well (and that's yet another math operation on each frame, for e.g. [here](https://github.com/darktears/darktears.github.io/blob/master/demos/xr/demo.js#L999) and [here](https://github.com/darktears/darktears.github.io/blob/master/demos/xr/demo.js#L880))

I think we could simplify the life of developers by providing them a way to specify an offset matrix before they retrieve the view matrix. The UA will then be able to do all these math operations efficiently and transparently for the developer.

One possibility on the spec side would be to let the developer provide the offset inside the `XRFrameOfReference` as a member (most likely a Float32Array). When the developer would query the view matrix using `xrFrame.getViewerPose(xrFrameOfRef);` it's already adjusted.

This would work for the inputs as well when calling `xrFrame.getInputPose(inputSource, xrFrameOfRef);`. The only caveat here is in the IDL : `optional XRFrameOfReference frameOfReference`. This may create confusion is the developer doesn't provide the frame of reference.

@thetuvix mentioned to me at TPAC that OpenXR may have the concept of offset provided by the developer as well.

@toji @NellWaliczek thoughts?

**Comment by modulesio** [comment]
The question I have is:
- is offset a property of the session?
- a property of the content/contexts in the session?
- or a thing passed in by the app's renderloop for easier math (what is suggested here)?

In my tests blending WebXR sites, it made sense to put it on the site context (per-site blend offset). Alternatively putting this concept on the session enables things like multiple virtual displays over the same context. But what's proposed here is probably the simplest option.

**Comment by darktears** [comment]
@modulesio good questions.

I think your suggestion of per site context make sense. For example one can think you could switch from immersive to non immersive (or vice-versa) and expect to be at the same position when you left one or the other. In that particular case we're beyond sessions. But wouldn't it make sense for the developer to store the current offset and apply it on the`XRFrameOfReference` whenever a new session is granted and when requesting the new frame of reference?

**Comment by NellWaliczek** [comment]
@toji  is going to take point on this issue, but odds are we'll have this functionality hang off of XRFrameOfReference.

**Comment by blairmacintyre** [comment]
In our work on Argon and on a precursor to webxr (our WebXR API from last year) we wanted to support overlaying multiple sites, as well.  A core requirement is that locomotion is coordinated, as you say @modulesio.  So, in Argon, all user locomotion offsets are handled by the platform.

A key point: we differentiated between "augmentation" layers (transparent, can have many) and a "reality" layer (renders "the view of the world").  The critical point is that only the reality layer would (to use the terminology here) set an offset;  the augmentation layers would simply get the merged coordinate system.

I've suggested this capability a long time ago, but there wasn't much uptake.  I will second it here.

However, it does not (by itself) solve the problem of enabling multiple sites to be combined:  any relatively sophisticated app is very likely to combine using an offset like this with it's own coordinate system management.  For example, as a VR site moves through a building, it might use offsets within a room, but reset the coordinate system when the user moves from one area of the building to another.  For another site to be properly overlaid, we would need the base site to ALSO expose a global coordinate system (e.g., say what the current origin is in a unique global coordinate system).

**Comment by toji** [comment]
Whether or not OpenXR provides a way to do this (Not gonna say @thetuvix is wrong, though... 😏) the offset is pretty basic math that the UA can easily handle on it's own for any API. You can make the argument that the same could be said for developers in their JS code, but I think this is a valuable simplification we can provide for a pretty common use case.

I agree that `XRFrameOfReference` feels like the best place to do this. I question whether providing a straight `Float32Array` is desirable, though, since it would mean that developers could feed in things like shearing/scaling/inversions which... 🤢 Really we just want to allow rigid transforms: translation and rotation.

Also, @darktears, I understand from @NellWaliczek that you were saying that developers are frequently being forced to decompose the matrices we're returning anyway for the purposes of engine integration? I wondering if that should feed into the solution of this issue as well somehow.

@modulesio and @blairmacintyre's points about multiple concurrent sites is an interesting one, but I'm hesitant to factor it into the design too much at this exact point specifically because of Blair's point that it's going to take more than just this to solve that particular problem. It does feel like something that has to be coordinated at a platform level.

**Comment by darktears** [comment]
@toji I share your view that the math is relatively simple for the UA to handle and that we should provide it as a convenience as we all strongly think that is a pattern we're going to see out there very often. Simplification is always good and will avoid mistakes from developers.

Good suggestion on the full matrix so what you would want to expose? A rotation and/or translation vector?

And yes I mentioned to @NellWaliczek that I had to decompose the matrices often but that number is so far linked to that issue. In a magic window case, I had to decompose the view matrix to apply the translation on it without being affected by the device rotation/emulated height (so movements are always in the correct direction, considering the 2D navpad). In immersive mode, same problem with the addition of the controllers as I had to decompose their gripMatrix/pointerMatrix for example. The only other case where I decompose as of today is for the ray cast/intersection but probably that could be simplified if I get to the bottom of why the new XRRay type didn't work for me since it's been introduced.

**Comment by toji** [comment]
> Good suggestion on the full matrix so what you would want to expose? A rotation and/or translation vector?

Probably a translation vector and rotation quaternion pair? That way it's an unambiguous rigid transform.

**Comment by darktears** [comment]
> > Good suggestion on the full matrix so what you would want to expose? A rotation and/or translation vector?
> 
> Probably a translation vector and rotation quaternion pair? That way it's an unambiguous rigid transform.

Looks good to me. We don't have anything in WebIDL out of the box to represent that, we'll need some intermediate types to provide x,y,z vector for the translation and x,y,z,w for the rotation quaternion.

**Comment by toji** [comment]
We've already committed to using `DOMPoint` for vectors elsewhere in the API, so that would definitely make sense here. (We'd ignore developer-supplied `w` components and force them to `1.0`) As for the orientation... it's kinda tempting to also run with `DOMPoint`, simply because it has the right number of components. :stuck_out_tongue_closed_eyes:

Still gauging how I feel about that, but I'm leaning towards inventing as few new data containers as we can...

**Comment by darktears** [comment]
I like the `DOMPoint` suggestion, I had forgotten about it (for some reason my mind still maps a DOMPoint as a 2D point :) )

**Comment by toji** [comment]
Related PRs have all been merged now. Closing. Thanks for the input, everyone!
