### ISSUE TITLE
Using makeXRCompatible to upgade a webgl context to an XR Context

### ISSUE THREAD

**Issue by phtaylor** [immersive-web/webxr#437]
Our app falls into the category of XR Enhanced. Most users probably won't use XR, or even use the app for a while before putting on the headset. 

So we have lots of resources in the GPU, and want to simply start rendering to the HMD. (We have been working with WebVR for a long time now).

However, there appears to be no such method WebGLRenderingContext.makeXRCompatible
I have created the context with the option xrCompatible: true

I am using Chrome 70.0.3538.110
I don't see any examples on upgrading a context. Is this feature currently supported or still in the works?

Next I will try modifying the xr-barebones example to create a regular context and upgrade it, but I just wanted to check here first. 

Thanks.

**Comment by toji** [comment]
This is an unfortunate case where the implementations haven't quite caught up with the current state of the spec/explainer. The call you'd actually need to make in Chrome today is `gl.setCompatibleXRDevice(xrDevice)`, which is what the spec detailed until just recently when we removed the need for an `XRDevice` from the API. Apologies for the confusion!
