### ISSUE TITLE
Better indicate when elements of a pose are estimated

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#445]
In #440 there was some discussion about the need to better flag when certain elements of a pose, such as the `position` are based on estimations rather than observed sensor data. Specifically, see [these comments](https://github.com/immersive-web/webxr/pull/440#discussion_r240743420) between @thetuvix and @blairmacintyre.

We already have an `emulatedPosition` bool in `XRInputPose`, but as Alex points out we don't have an equivalent for head poses and we should be more consistent about it. The suggestion within the thread is to promote the estimated flag into `XRRigidTransform`, which is workable. I've got an alternate idea for where the flags could be hosted that would make the ergonomics of creating transform for things like teleportation cleaner, which I'll try to put up in this repo soon for discussion. Either way, it's a good point that should be addressed.

**Comment by NellWaliczek** [comment]
Fixed by #460
