### ISSUE TITLE
Chac Mool Example - black screen after chrome canary update.

### ISSUE THREAD

**Issue by hajop** [immersive-web/webxr#455]
Good morning!

I have tried the last few days, the Chac Mool Example and I am really very impressive. It's really great!

Yesterday my Chrome Canary did an update to version 73.0.3634.0. Since then I only get a black window when I open the 3D object in the example.

Am I alone with this problem or is it already known?

**Comment by klausw** [comment]
The WebXR spec is currently undergoing some major changes, including incompatible API changes. Chrome is in the process of getting updated to match the latest spec, and unfortunately there will be a rough transition time until things settle down again. In this specific case you can rename `getDevicePose` to `getViewerPose`, but more changes are incoming.

For now, I'd recommend staying with Chrome Beta or Dev until things stabilize. @toji had previously used a [compatibility shim](https://github.com/immersive-web/webxr-samples/blob/master/js/webxr-version-shim.js) to help samples work across browser versions, but there's no easy solution yet for the current batch of API changes.

**Comment by cwilso** [comment]
Indeed, the Chacmool example was not written to the current spec, and in this transition time, I wouldn't expect it to stay up and running on current Canary.  Once our core has stabilized with the new API changes, we can update the Chacmool sample, but there's no WebXR issue here.

**Comment by hajop** [comment]
Thanks! It's works with Chrome dev. 👍
