### ISSUE TITLE
Document what happens when the session has ended

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/webxr#467]
BS Issue: https://immersive-web.github.io/webxr/#end-the-session

The session may end in a variety of situations such as end method of the XRSession is invoked: https://immersive-web.github.io/webxr/#dom-xrsession-end

When this happens the session permanently shuts down. The process is described here: https://immersive-web.github.io/webxr/#shut-down-the-session

We should elaborate on some of the platform-specific steps to shut down the device’s tracking and rendering capabilities.

**Comment by AdaRoseCannon** [comment]
Should probably include at what step the end event is fired as detailed in: https://immersive-web.github.io/webxr/#event-types

**Comment by Artyom17** [comment]
Another question: should "inline" session fire "end" event when switching to "immersive-vr" occurs? This is not really clear, IMO.

**Comment by toji** [comment]
No. Inline sessions should not be ended by an immersive session starting. They should be suspended till the immersive session ends (firing what's currently the "blur" and "focus" events respectively.) And yes, this should definitely be better documented.

**Comment by Manishearth** [comment]
So, it's not clear to me what the difference between end and shut down is. It seems like they should be the same process.

Is it that "end the session" is what should happen when you call `.end()`, and other ways of shutting down the session are "shut down the system" (with "end the session" calling "shut down the session"). Which ones should set the ended flag? Which ones should trigger onend?

**Comment by Manishearth** [comment]
_tentative_ fix here: https://github.com/immersive-web/webxr/pull/710
