### ISSUE TITLE
Document how to poll the device pose.

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/webxr#480]
BS Issue: https://immersive-web.github.io/webxr/#issue-0eabb7ae

Add information about how to use requestAnimationFrame from the XRSession to get the device pose from XRFrame to section 3.1 (https://immersive-web.github.io/webxr/#xrframe-interface)

**Comment by toji** [comment]
This should be resolved by recent changes related to better describing spatial relationships.
