### ISSUE TITLE
Expand upon the XR Compositor

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/webxr#481]
BS Issue: https://immersive-web.github.io/webxr/#issue-6d0cdba2

Section: https://immersive-web.github.io/webxr/#compositor

The XRCompositor is needs some detail such as the XRCompositor Interface, how the list of layer images works and explain the frame lifecycle.

**Comment by Manishearth** [comment]
The target of this bug has changed significantly since it was filed, but I tried to fix remaining concerns in https://github.com/immersive-web/webxr/pull/805
