### ISSUE TITLE
Expand the last two steps of the getViewerPose() and getInputPose() algorithms

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/webxr#483]
re: https://immersive-web.github.io/webxr/#xrframe-interface

The last two steps are:

> If [pose] cannot be determined relative to referenceSpace, return null.

This needs to describe the kind of situation in which this would happen such as there being no relationship between the two reference spaces or the  XRRigidTransform describing the difference between the reference spaces having nonsensical entries such as NaN or Infinity.

> Return a new [Pose] describing the [pose] relative to the origin of referenceSpace at the timestamp of the XRFrame.

This should describe the algorithm to transform the reference space of the pose into the XRFrame's reference space into to generate the new pose.

**Comment by NellWaliczek** [comment]
This issue is from before we removed getInputPose() in favor of getPose().
