### ISSUE TITLE
Define the creation of a swap chain, or remove references

### ISSUE THREAD

**Issue by cwilso** [immersive-web/webxr#484]
The XRWebGLLayer constructor alogorithm (https://immersive-web.github.io/webxr/#dom-xrwebgllayer-xrwebgllayer) refers to the swap chain (steps 11 and 12).  It's not clear that we should get this deep into the process by which the browser takes the pixels and shuffles them off to a device -  the native apis tend to refer to DirectX,  but we can't presuppose a particular underlying API.  We can talk about WebGL buffers but it's not clear if we should define swap chain better or just not go this deep - e.g. "Step 11: Initialize any required render API constructs, and if they are unable to be creating throw an OperationError and abort these steps."

**Comment by kearwood** [comment]
IIUC, the reason for including "initialize the layer's swap chain" here is to ensure that the XRWebGLLayer constructor fails if the UA is unable to allocate GPU-side resources needed to support the layer rendering.  Perhaps we could describe this in a more generic manner:

11. Allocate and initialize resources, including GPU accessible memory buffers, as required to support the compositing of the XRWebGLLayer.
12. If layer’s resources were unable to be created for any reason, throw an OperationError and abort these steps.

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/708
