### ISSUE TITLE
Discuss use of sensor activity as a possible fingerprinting vector.

### ISSUE THREAD

**Issue by cwilso** [immersive-web/webxr#485]
Section on Fingerprinting (https://immersive-web.github.io/webxr/#fingerprinting-security) should likely explicitly mention use of sensor activity for fingerprinting.

**Comment by ddorwin** [comment]
Presumably, this will be addressed by integrating the the privacy design in #638 into the spec.
/cc @johnpallett

**Comment by NellWaliczek** [comment]
Fixed by #746
