### ISSUE TITLE
"focus"/"blur" naming on XRSession may be confusing

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr#488]
The naming of the `"focus"` and `"blur"` events on `XRSession` are somewhat confusing to me.

I hadn't thought about those events for a bit and when I saw them today in the spec, I presumed they were telling the app when it could expect or not expect to receive XR input updates such as pose updates, `select` events and other input source button presses.  Basically, I presumed these events to be the equivalent of [`"focus"`](https://developer.mozilla.org/en-US/docs/Web/Events/focus)/[`"blur"`](https://developer.mozilla.org/en-US/docs/Web/Events/blur) in the core DOM.  However, these events actually tell the app when its pixels are invisible or visible, allowing it to save effort by pausing its rendering.

While it is likely that XR input will _also_ be removed from the app during the example situation of a sensitive overlay being displayed, that seems like a secondary effect.  Specifically, if XR input is removed from the page temporarily due to a non-sensitive _partial_ overlay, the UA _would_ expect the page to continue rendering.  However, it's unlikely that a UA could raise the `"blur"` event to communicate the loss of input, since we'd have already suggested that pages stop rendering when they receive that event.

This seems more similar to the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) and its `visibilitychange` event, which serves an equivalent purpose for 2D content, letting the page know when the user can't see it, allowing the page to stop expensive rendering or pause content.  Perhaps a single `visibilitychange` event better fits our intended developer mental model here?

**Comment by thetuvix** [comment]
Another hint that a name may be off is when we consistently use some word in prose to describe a concept, but then use a different token for that concept in the IDL.

The [explainer section](https://github.com/immersive-web/webxr/blob/master/explainer.md#handling-suspended-sessions) that describes these events talks about "suspended sessions" and then uses the terms "suspend"/"suspension" many times.  Another option would be to rename these events `"suspend"` and `"resume"`.

My primary concern with that option is that `"suspend"` seems _too_ strong given the description of how UAs would behave - I don't personally think of a suspended session as one where the app can still get device state, but just more slowly.  The primary qualitative thing going on here is that the user can no longer see the app's pixels, and so `"visibilitychanged"` still seems more correct.  However, in that case, perhaps we should adjust the prose too to refer to "invisible sessions".

**Comment by thetuvix** [comment]
Oops, clicked the wrong comment button :smile:

**Comment by kearwood** [comment]
In a future beyond having only XRWebGLLayers, we may have XRLayer types (eg quad floating in space) that are asynchronously rendered by the UA.  In this case, there would be no need to submit new frames or even have a RAF loop active for the content to continue to be projected and rendered correctly.  Such XRLayer types could be considered safe for use when compositing content from multiple origins simultaneously, as the UA could visually indicate the layer with input focus and accept user input without leaking information about the user's head pose to the content supplying the blurred XRSession.

While only having XRWebGLLayers, inherently requiring exclusive mode presentations, there may be confusion between the concepts of "visibility" and "focus", as they would be treated equivalently.  I would suggest considering potential of future non-exclusive XRSession interaction before losing "blur" and "focus".  Perhaps there are scenarios where an independent "suspend" and "resume" state would be beneficial?

**Comment by thetuvix** [comment]
Note that the [MDN page for the Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API#Use_cases) specifically warns developers about confusing the notion of page visibility with the notion of `blur`/`focus`:

> _Note:_ While `onblur` and `onfocus` will tell you if the user switches windows, it doesn't necessarily mean it's hidden. Pages only become hidden when the user switches tabs or minimizes the browser window containing the tab.

**Comment by toji** [comment]
Drawing on comments from the F2F and Alex's last comment, I've posted a PR (#687) for this issue that changes the `blur`/`focus` events to `visibilitychange`, as I think that's a better parallel to what we're trying to communicate here. Thanks for the suggestion!
