### ISSUE TITLE
Clarify statement about convex boundsGeometry

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#495]
The `boundsGeometry` attribute description currently says:
>The shape it describes MAY not be convex.

The combination of RFC "MAY" and non-RFC "not" is strange, and it's unclear what this statement means.

Which of these interpretations is correct?
1. The shape it describes MUST NOT be convex.
1. The shape it describes MAY be not convex.
1. The shape it describes MUST be concave.

RFC words generally reference the implementation (i.e., "Implementations MAY return a shape that is not convex"), so we may want to further rephrase this.

**Comment by toji** [comment]
This is a minor enough clarification request that I felt comfortable landing the fix directly. New verbiage is "The shape it describes MAY be convex or concave."
