### ISSUE TITLE
Which globals apply to security policy?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#497]
The current spec language for context isolation (https://immersive-web.github.io/webxr/#contextisolation-security) is phrased in terms of "page", for example:

> Also, to prevent CORS-related vulnerabilities each page will see a new instance of objects returned by the API, such as XRSession.

it is not obvious how to map this to HTML security policy (https://html.spec.whatwg.org/multipage/webappapis.html#realms-settings-objects-global-objects), which is phrased in terms of "realm"s or "global"s. In particular, the spec should make clear which global is being referred to by "page", does this mean incumbent global?

**Comment by NellWaliczek** [comment]
@Manishearth, is this one something you'd be comfortable picking up?

**Comment by Manishearth** [comment]
I'm not very clear on what changes need to be made here, @asajeffrey is it just updating "page" to "incumbent global" with the appropriate xrefs?

(I'm not 100% familiar with all the globals stuff, especially how it pertains to security)

**Comment by asajeffrey** [comment]
@Manishearth will that section will be non-normative when it stabilizes? If so, it's not as crucial to get the spec language 100% tight. The important thing is to make sure that whatever security goals we put in that section are actually met by the text!

The sentence "Also, to prevent CORS-related vulnerabilities each page will see a new instance of objects returned by the API, such as XRSession" seems to be validated by the requirement that each `Naviagator` gets an unique `XR` object.

The sentence "Similarly, methods invoked on the API MUST NOT cause an observable state change on other pages" seems weird, if security domain A opens an XR session, then domain B tries to, will there not be failures that B can observe which indicate that some other domain has opened a session?

**Comment by Manishearth** [comment]
> will that section will be non-normative when it stabilizes?

I don't know, I'm not a spec editor :smile: @NellWaliczek might

**Comment by toji** [comment]
I like to consider myself reasonably well versed in the workings of the web, but I've got to admit that trying to parse through what the various "realms" and "globals" actually correspond to here is making my brain melt. @asajeffrey: Could you help us resolve what globals we should be using if I describe the intent a bit better?

Some of the text in the example section could probably be dropped. For instance:

> Also, to prevent CORS-related vulnerabilities each page will see a new instance of objects returned by the API, such as XRSession. 

I think it would be extremely unusual (if not impossible) for Javascript objects created, for instance, in two separate tabs to receive the same object instance in both places. As such we probably don't need to specify that "our API should function like Javscript is normally expected to function."

Other text still feels necessary, such as:

> Methods invoked on the API MUST NOT cause an observable state change on other pages. For example: No method will be exposed that enables a system-level orientation reset, as this could be called repeatedly by a malicious page to prevent other pages from tracking properly.

The intent here is simply to say that the device itself has state that is potentially being reported to multiple scripts/pages/tabs/realms/globals/I-dont-know-the-right-word. (For example: the device pose.) Any given instance of an XRSession shouldn't be allowed to force system-wide changes to that device state that other XRSession's could observe. Not only is that a potentially poor user experience, but it could also potentially open an unintended communication channel between isolated scripts. Which, you know, is bad.

As you pointed out, the fact that we only allow a single immersive XRSession at a time seems like it could violate that, but I would argue that there are multiple reasons why we may reject a session request at any given point, with plenty of room for user agent discretion, so it would be difficult to state definitively that any given rejection was the result of a different script's state. Beyond that, blocking multiple immersive sessions at once helps achieve the goal of not accidentally causing state changes visible elsewhere on the system.

Any guidance based on that, or if it's still ambiguous could you help explain the differences between the various globals and why you might choose one vs. the other?

**Comment by Manishearth** [comment]
/agenda so that @asajeffrey can explain the nuances of this issue during the next call 😃

**Comment by asajeffrey** [comment]
In https://html.spec.whatwg.org/#concept-relevant-everything, the recommendation is "In general, web platform specifications should use the relevant concept, applied to the object being operated on (usually the this value of the current method)." In practice, this means that whenever an object is created, we should specify the relevant realm (e.g.  in https://immersive-web.github.io/webxr/#ref-for-xr%E2%91%A1 we should say something like "The user agent MUST create an XR object when a Navigator object is created in the relevant realm of the Navigator object..."

> I think it would be extremely unusual (if not impossible) for Javascript objects created, for instance, in two separate tabs to receive the same object instance in both places. 

Unfortunately there's two ways of breaking that: same-origin iframes, and `document.opener`, both of which allow access to objects in other realms. Sigh.

**Comment by asajeffrey** [comment]
Also, https://immersive-web.github.io/webxr/#xr-animation-frame step 8.2 says "Invoke the Web IDL callback function" (https://www.w3.org/TR/WebIDL-1/#es-invoking-callback-functions) which is defined in terms of incumbent globals.

The equivalent HTML text at https://html.spec.whatwg.org/#run-the-animation-frame-callbacks refers to https://heycam.github.io/webidl/#invoke-a-callback-function which in step 8 "prepares to run a script" (https://html.spec.whatwg.org/multipage/webappapis.html#prepare-to-run-script) updates the JS execution context stack.

I think the XR spec should follow the HTML spec in this case.
