### ISSUE TITLE
webxr and computer vision 

### ISSUE THREAD

**Issue by sylvaincordiere** [immersive-web/webxr#498]
Hi 
I just want to ask a question about the possibility of using computer vision in webxr. Would it be include in the api ? Would we have the possibilty to detect a face, a hand etc.
It would be useful in ecommerce for example detect a wrist in order to add a watch etc
And if this computer vision possibility isn't added to the webxr api.
Would we have the possibiliy to develop our own computer vision api with the webxr.
I guess that would cause some privacy issue because the computer vision api would have to access to user camera.

**Comment by NellWaliczek** [comment]
WebXR is explicitly not designed to be a multipurpose computer vision api, however we do consider it a very important that CV can be used alongside the data WebXR reports.  To that end, we are aiming to add the ability to get the appropriate camera for an XRSession and relate camera intrinsics to the session, though we do not yet have a formalized design.  This work is still currently in the "proposals" stage and can be found in immersive-web/proposals#4
