### ISSUE TITLE
Can app just update depthNear/depthFar during frame?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr#500]
WebXR currently requires apps to set `depthNear`/`depthFar` prior to the affected frame's rAF.  As with other parts of the API :smile:, I believe this originally flowed from a HoloLens restriction, which could only change the near/far plane before a `HolographicFrame` was created - however, this restriction has since been relaxed, with apps able to override the near/far plane after a frame is created.  This has helped ease life for apps that wish to dynamically adjust their depth range based on the virtual content they're rendering.

Do we know of any remaining runtimes and/or hardware that require the `depthNear`/`depthFar` values to be provided prior to the frame rAF?  If not, can we simplify this latent part of the API for developers?

From a different perspective, what do runtimes intend to do with `depthNear`/`depthFar` for now?  Is it purely used to provide a complete projection matrix back to the app?  I'd guess that runtimes won't have any further use for these values until WebXR accepts depth buffers, at which point the depth buffer submission function could more naturally just accept the `depthNear`/`depthFar` values directly.

That itself may be a motivation for giving apps projection FOV + shear component values rather than projection matrices - we could then remove the concept of `depthNear`/`depthFar` from WebXR 1.0 entirely!

**Comment by NellWaliczek** [comment]
Yes, that was the original reasoning.  And yes, being able to dynamically change the range in a given frame would be great for rendering.  The big question is...what is the consequence for screen-based input sources?  We could take the same approach we did with `XRReferenceSpace.originOffset`and say "well if you change it mid-frame the pose data will change and you need to re-query it".  Though actually... thinking about the math... i'm not 100% certain it would make a difference.  It does make me think we've perhaps spec'd the definition of the screen-based XRInputSource incorrectly for use with hit-testing....

**Comment by thetuvix** [comment]
Yea, the Windows MR APIs now have the middle ground of the [OverrideProjectionTransform method](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographiccamerapose.overrideprojectiontransform), letting the app override the projection matrix before presenting its frame, which can include updated near/far components.  However, those near/far planes are only relevant to the platform if a depth buffer is submitted, to give meaning to the normalized depth pixels.  If the app does not supply a depth buffer, it wouldn't need to bother providing its updated projection matrix.

> The big question is...what is the consequence for screen-based input sources? We could take the same approach we did with `XRReferenceSpace.originOffset`and say "well if you change it mid-frame the pose data will change and you need to re-query it".

If WebXR returns projection components (perhaps including shear/roll, if needed) instead of fully-formed projection matrices, that would likely remove the last need for the UA to know the app's `depthNear` and `depthFar` in WebXR 1.0, avoiding the need to spec answers to your questions above.  We could then reintroduce those in a more targeted way later once WebXR gains the ability to accept an app-submitted depth buffer, with the values giving meeting to the exact depth buffer being submitted in that call.

**Comment by rcabanier** [comment]
> Do we know of any remaining runtimes and/or hardware that require the `depthNear`/`depthFar` values to be provided prior to the frame rAF? If not, can we simplify this latent part of the API for developers?

Magic Leap needs to know the `depthNear`/`depthFar` before the start of the frame.

**Comment by toji** [comment]
That's really good to know, Rik. Thanks!

I don't see it as big inconvenience to specify the near/far prior to the frame start. The main benefit for us would be possibly making decomposing the projection matrix cleaner, but it's not clear from the F2F that we can decompose it anyway. As such, I think it's probably best to just leave this one be.
