### ISSUE TITLE
Getting started sample

### ISSUE THREAD

**Issue by Rosehart** [immersive-web/webxr#509]
I'm new to WebXR coming from Unity development. Hardly any experience in web development, and I'm having a hard time finding something to get me started with this. Where can I find an up to date version of the library, if that's even a thing. 
The [samples ](https://immersive-web.github.io/webxr-samples/) would be amazing and is exactly what I'm looking for, but they don't currently work. Is there currently something to show me how a project like this would be set up?

**Comment by AdaRoseCannon** [comment]
Hi Rosehart,

I am glad you are interested in WebXR, this isn't a JS library, we are working on new features to add to the Web Platform as a whole.
The APIs which are being detailed here will be added to web browsers to allow people to use them to use the Web to access VR and AR headsets.

Here are some good libraries to check out for getting started with graphics in the Web:

[A-Frame](https://aframe.io) - Build 3D scenes with HTML
[Three.js](https://threejs.org) - JavaScript library
[BabylonJS](https://www.babylonjs.com/) - Javascript Library

**Comment by Rosehart** [comment]
Hi!

Thanks for the great response, I've come across those libraries and have a very basic understanding of them. Just to check, this means I can just start typing all WebXR stuff in a js/html file and just go from there?
Again, thanks for taking the time to answer my question.

**Comment by AdaRoseCannon** [comment]
Yep, that's correct! 

Ada

**Comment by klausw** [comment]
Just be aware that this is a bleeding edge web API, and implementations are still catching up to recent spec changes. For example, the stable Chrome versions implement an older version of the WebXR APIs which isn't compatible with the current sample's source. (There's a compatibility library in webxr-samples which tries to work around some of these differences, but that's a stopgap and not recommended for long term use.) 

If you're going to experiment with WebXR, you'll likely need to use latest browser releases such as Chrome Canary and be willing to put up with some glitches until things stabilize. If you want things to just work as documented, it may be better to check back in a month or two.

**Comment by klausw** [comment]
Also, for Chrome Canary, you need to enable the WebXR device API in chrome://flags, it's off by default since the spec and implementation aren't ready for general use yet.
