### ISSUE TITLE
Remove unnecessary interface members that only reflect what was requested

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#513]
There are currently some member attributes in the spec that only reflect what the application requested. I believe this is generally discouraged as doing so increases the API surface without providing capabilities not otherwise available to the application. (It's also easier to add values in the future if necessary than it is to remove them.) The exception is where there is a fixup step or the correct value may not otherwise be obvious to the application.

The following attributes can be safely removed because they reflect a value provided to the method that created the object. There may be others:
* `XRSession.mode` is specified in `XR.requestSession()`.
* `XRStationaryReferenceSpace.subtype` is specified in `XRSession.requestReferenceSpace()`.

**Comment by toji** [comment]
This is good feedback that I've separately received from ergonomics reviews in the past. (Not on the attributes in question, but similar properties.) I'll admit that things like having the `mode` attached to the session make it a bit easier to work with in multi-session applications, but that can always be patched onto the object by developers at runtime if they need it:

```js
navigator.xr.requestSession({ mode: 'immersive' }).then((session) => {
  xrSession = session;
  xrSession.mode = 'immersive'; // Track the requested mode if needed.
});
```

Given that, I wouldn't object to this change.
