### ISSUE TITLE
9.2 Input.XRInputPose.targetRay : pointing source position & direction relative to gripTransform 

### ISSUE THREAD

**Issue by HyroVitalyProtago** [immersive-web/webxr#516]
If the targetRay is the default interaction technic of the WebXR API, we need to ensure that the pointing source position and direction is ergonomic by default.

For the moment, the ray of oculus touch is much more logical from a human hand pose perspective that the vive. The vive controller ray follow the object geometry of the controller (like a remote control) and points (more) "up" while oculus touch points "toward" (more like a gun) with the same "relaxed" (default) hand pose. There is the same problem with a lot of 3dof remote controllers.

The probably best pointing direction may be seen as when you handle the controller, points with your index finger. It's more natural, don't involve wrist annoying rotation and follow more the arm direction that when you points with the thumb up.

I don't know if I'm clear, but don't hesitate to comment! (I will probably add images to ensure everyone can understand).

Maybe this issue is much more related to hardware controller api...

**Comment by toji** [comment]
I think the concern is clear enough. :) Thanks for posting the issue!

We have some text to this effect in the explainer which hasn't made it's way into the specification just yet:

> The exact orientation of the ray relative to a given device follows platform-specific guidelines if there are any. In the absence of platform-specific guidance or a physical device, the target ray points in the same direction as the user's index finger if it was outstretched.

The one disconnect in that statement from what you said is that the "platform guidance" for a Vive controller is, as far as I know, to have pointer rays point directly along the controller geometry as you stated. It's not clear to me that we would want to break the platform convention in the browser for the sake of ergonomics. I wouldn't mind reinforcing the idea that a more ergonomic position IS preferred in most cases, but ultimately it's probably a UA choice if they override platform defaults or not.

In any case, I'll consider this issue to be a task to ensure that language about the ergonomic preferences of the target ray get migrated into the spec text.
