### ISSUE TITLE
Specify the behaviour if the user does not provide an `outputContext`

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#527]
At the moment, if the user does not provide an `outputContext` when requesting a `XRSession`, it will be initialized to `null` (https://immersive-web.github.io/webxr/#initialize-the-session), and I don't see anything that subsequently sets it.

When session runs an XR animation frame (https://immersive-web.github.io/webxr/#xr-animation-frame), it aborts if `outputContext` is `null`.

**Comment by toji** [comment]
To clarify: The outputContext is set now with the `XRSession.updateRenderState` function (this is a recent change, it used to be handled at session creation time.
