### ISSUE TITLE
WebXR status page

### ISSUE THREAD

**Issue by bwasty** [immersive-web/webxr#529]
I find it difficult to follow the progress of the spec - I'm occasionally looking at commits/issues/milestones on GitHub, but I'm not sure when it will be 'stable enough' for me to update my prototypes.

It would be great to have a simple status page, tracking and explaining the milestones and current browser support (including things like the necessity of a `webxr-version-shim.js` like in the examples repository). Perhaps similar/based on https://webvr.rocks/?

A weekly/monthly summary of changes might also be helpful.

**Comment by DoDecaDence** [comment]
Same here.

A go-to status page with a summary would be a great addition, unless maintaining it would cause too much additional overhead.

On the other hand, it could be quite valuable in facilitating communication by providing an entry point for a quick overview of the latest developments.

[`webxr`](https://github.com/immersive-web/webxr) is such an extensive repository that tracking the latest changes isn't trivial. 
There's the occational change in the other repositories, but anyone that's not deeply involved in the development will have a hard time making use of it.  
(Like finding valuable things as the shim in the [`webxr-samples`](https://github.com/immersive-web/webxr-samples))

So, another advantage of such a status page would be that the readme files of those repos could all link to it.  
That way, anyone browsing the files would quickly end up there and know what to expect.
(For similar reasons I've [suggested earlier](https://github.com/immersive-web/webxr-reference/issues/18) to link the explainer in the [`webxr-reference`](https://github.com/immersive-web/webxr-reference/issues/19) repository.)

Having a hub for the latest changes would definitely be useful.

**Comment by AdaRoseCannon** [comment]
We have something in the works to help with this.

**Comment by AdaRoseCannon** [comment]
First status update: https://github.com/immersive-web/administrivia/blob/master/newsletter/2019-01-01-Recent_Spec_Changes-agenda.md

These will probably be approximately monthly but the timing will vary depending on the cadence of Pull Requests.

If you would like more information in the reports please raise an issue under the administrivia repo. :)
