### ISSUE TITLE
Clarify when `requestViewportScaling()` changes apply

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#541]
Now that we've got clarity around when `updateRenderState()` changes apply, we need to update the logic for `requestViewportScaling()` to either match or apply immediately (and no longer be promise based).  This change needs to be made in both the explainer and the spec text

**Comment by ddorwin** [comment]
/triage This can be closed or moved to Future now that the feature has been removed (#617).

**Comment by toji** [comment]
Thanks for calling that out!
