### ISSUE TITLE
Creating glContext with XR Device

### ISSUE THREAD

**Issue by blairmacintyre** [immersive-web/webxr#545]
In the explainer.md, when discussing creating a webgl Context that for **XR Centric** applications, the explainer says 
> These types of applications can avoid the need to call `makeXRCompatible` and the possible context loss that it may trigger by passing the XR device that the context will be used with as a context creation argument.

and then shows this code, which does not pass in an XR device, but rather sets a flag.
```js
let gl = glCanvas.getContext("webgl", { xrCompatible: true });
```

Which is correct?

**Comment by NellWaliczek** [comment]
The source code is correct.  The prose is a bug leftover from when we removed the `XRDeviceType`.  Good catch!

**Comment by toji** [comment]
Fixed with a direct commit. Didn't think this obvious one-line change warranted a pull request.
