### ISSUE TITLE
Web ? 

### ISSUE THREAD

**Issue by 3DRSenior** [immersive-web/webxr#552]
why you call that web ? it have nothing to do to the root definition of the WEB !  which is related to the look of the spider web based on the interconnection from page to page only ! I really don't understand ! .... the WEB XR like the WEB VR like the WEB GL are only some (good) API in JavaScript to interact inside a html page ... nothing related to the web ...

**Comment by AdaRoseCannon** [comment]
Thanks for your feed back :neutral_face:

**Comment by 3DRSenior** [comment]
You are welcome, I added you on LinkedIn, we may have to talk ...
