### ISSUE TITLE
Support rectangular play space for Bounded reference spaces

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#557]
Migrating from #228, which was closed and then re-opened with a comment from @NellWaliczek:

> During the course of finishing #409, a comment was filed to change the boundsGeometry attribute from being an arbitrary array of points to instead be an axis-aligned XZ rectangle. The reasoning was that on systems with arbitrary geometry, developers have been saying that they would prefer the rectangle rather than having to compute a rectangle themselves.
>
>Rather than removing boundsGeometry, I’d recommend adding an additional property boundsRectangle so that we preserve providing the raw boundary data if developers want it.
>
>Does anyone object to this? This may put more of a burden on some UA to compute the boundary rectangle on top of the raw data available.

@cwilso followed up with:

> Resolved at FTF (Oct 2018): Nell will put together a PR to leave the existing bounds and also add a new attribute to XRBoundedFrameOfReference.

Pulling that into it's own issue to prevent confusion with the original intent of #228.

**Comment by klausw** [comment]
Is it still planned to support a boundsRectangle? If the intent is that this is more convenient for developers, I think it would be useful to have it as a standard feature. 

See also discussion in https://github.com/immersive-web/webxr/issues/674#issuecomment-512605931 for related timing questions - the bounded reference space may be less useful if it's not consistently providing bounds. If the reference space promise resolution were delayed until the bounds are available, developers could assume that the `boundsRectangle` is valid at the time they get it.

**Comment by bjornbytes** [comment]
LÖVR is interested in this, its headset API exposes both `getBoundsDimensions` and `getBoundsGeometry`.  It's more common to use the dimensions, but right now it's always returning zero on WebXR.  This means that people would have to add a special case for WebXR and compute the rectangle themselves in Lua.

**Comment by cabanier** [comment]
Is there a reason that the bounds can't be converted to a rectangle by the developer?
(FWIW Quest always returns a rectangle for the bounds)

Closing as nothing happened since 2019
