### ISSUE TITLE
Clarify "significant changes" for the reset event on XRReferenceSpace

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#561]
https://immersive-web.github.io/webxr/#eventdef-xrreferencespace-reset

> A user agent MUST dispatch a reset event on an XRReferenceSpace when discontinuities of the origin occur. (That is, significant changes in the origin’s position or orientation relative to the user’s environment.)

It's not exactly clear when such significant changes can happen (when settings change? when tracking is temporarily lost? if the input device is turned off for a bit?). It's worth clarifying what exactly this means here.

**Comment by NellWaliczek** [comment]
We struggled with finding a clear definition for this, but agree that at least a bit more clarity would be helpful.  Unless it's urgent, our intention is to address it in a subsequent Working Draft.

**Comment by Manishearth** [comment]
A non normative note that suggests when this may happen may be a low overhead stopgap

**Comment by NellWaliczek** [comment]
Feel free to put together a PR! :)

**Comment by cwilso** [comment]
@Manishearth Did you want to take a crack at making the verbiage more clear here?

**Comment by Manishearth** [comment]
I can try
