### ISSUE TITLE
requestReferenceSpace() should talk more about when you can reject the request

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#564]
There's a list of situations where `requestReferenceSpace()` can fail listed in [the explainer](https://github.com/immersive-web/webxr/blob/master/spatial-tracking-explainer.md#practical-usage-guidelines), this should be part of the spec.

**Comment by Manishearth** [comment]
(A lot of that document needs to be moved to the spec, really. I guess this is part of the plan?)

**Comment by NellWaliczek** [comment]
Yep, good catch.  We'll aim to get this fixed before we snap the next Working Draft, but there's a chance it will get pushed to a subsequent snap.

**Comment by Manishearth** [comment]
I might try adding it myself if I get time. (I wanted to be sure we wanted this in the spec in the first place)

**Comment by NellWaliczek** [comment]
@Manishearth did you want to pick this one up?

**Comment by Manishearth** [comment]
Sure!

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/651
