### ISSUE TITLE
Clarify what originOffset is applied to

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#567]
The spec says

>  The originOffset attribute is a XRRigidTransform that describes an additional translation and rotation to be applied to any poses queried using the XRReferenceSpace.

However, it's not exactly clear how exactly the rotation is applied: is it applied after the pose (like a periscope)? Or before the pose (as if the user is standing on a platform or something)? Or is it an offset being applied to the space?

I would have assumed it's a premultiplication with the pose, however [the chromium impl](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/xr/xr_space.cc?q=xrspace&sq=package:chromium&g=0&l=92-93) seems to indicate that its _inverse_ is premultiplied, which makes me think it's logically a transformation applied to the entire space.

Could this be clarified? (May be worth doing as part of #565)

**Comment by klausw** [comment]
I contributed some pictures and math here while working on the Chrome implementation: https://github.com/immersive-web/webxr/issues/477#issuecomment-471803936

The test page https://cs.chromium.org/chromium/src/third_party/webxr_test_pages/webxr-samples/input-selection.html exercises teleportation via originOffset manipulation, this was working as expected for me in Chrome both in 3DoF and 6DoF headsets:

My understanding is that the originOffset matrix transforms coordinates from world space (the virtual world's coordinate system) to tracking space (the roomscale area in the physical world), first rotating then applying translation. In the usual GL convention, these successive transforms get accumulated by multiplying them from the left:

```
originoffset_translation = (
     1 0 0 xform.position.x
     0 1 0 xform.position.y
     0 0 1 xform.position.z
     0 0 0 1
)

originoffset_rotation = (
    . . . 0
    . . . 0
    . . . 0
    0 0 0 1
)

point_worldspace = (px py pz 1)

point_trackingspace = originoffset_translation * originoffset_rotation * point_worldspace
```
 
The world space origin `point_worldspace = (0 0 0 1)` gets transformed to tracking space coordinates `(xform.position.x, xform.position.y, xform.position.z, 1)`, using the exact x/y/z values from the originOffset XRRigidTransform, and the resulting tracking space location stays the same when a rotation is added.

If you change the originOffset rotation component while keeping the originOffset position component unchanged, that corresponds to sticking a pin through the virtual world's origin that nails it to the originOffset position in tracking space (i.e. your play space), and then spinning the virtual world around that pin.

If that's not the behavior you want, i.e. if you want to rotate the virtual world around where you're currently standing in tracking space, you need to combine rotation and translation as per the formulas and diagrams in https://github.com/immersive-web/webxr/issues/477#issuecomment-471803936 .

Does this help? To the best of my knowledge this matches the Chrome implementation, and I'm interpreting the lack of feedback on issue 477 that others either are OK with it or don't have an opinion, though I'd really appreciate some tightened-up spec language to make this unambiguous.

**Comment by klausw** [comment]
As far as the implementation in Chrome is concerned, getViewerPose internally receives a pose in tracking space from the low-level APIs (aka "mojo space" in the source") and needs to returns a pose in world space. Since originOffset is a transformation from tracking space to world space, the inverse of that is what we need.

**Comment by klausw** [comment]
(Reposting this comment for people reading in email - I got the transform order wrong in the first draft)

As far as the implementation in Chrome is concerned, getViewerPose internally receives a pose in tracking space from the low-level APIs (aka "mojo space" in the source) and needs to returns a pose in world space. Since originOffset is a transformation from world space to tracking space, the inverse of that is what we need.

**Comment by Manishearth** [comment]
> Does this help? 

This does, thanks!

I've been looking at viewer poses as living within world space (which they do, at zero offset), and originOffset reads as an _additional_ offset applied to the pose, as opposed to an offset applied to world space to obtain the tracking space.

We should probably clarify this in the spec somehow.

I'll have a closer look at your comment on the other issues tomorrow.

**Comment by klausw** [comment]
Using the terminology from my comment https://github.com/immersive-web/webxr/issues/565#issuecomment-475711161 , the viewer pose is the XRRigidTransform `referenceSpace_from_viewerSpace`. 

Chrome internally has the transform pose == `unoffsettedReferenceSpace_from_viewerSpace`, and needs to transform that to the effective reference space:

```
referenceSpace_from_viewerSpace
  = referenceSpace_from_unoffsettedReferenceSpace * unoffsettedReferenceSpace_from_viewerSpace
```

where `reference_space_from_unoffsettedReferenceSpace = inverse(unoffsettedReferenceSpace_from_referenceSpace) = inverse(originOffset)`
