### ISSUE TITLE
Dependencies or Liaisons?

### ISSUE THREAD

**Issue by anssiko** [immersive-web/webxr#57]
The last remaining todo in the Charter draft is the [Dependencies or Liaisons](https://w3c.github.io/webvr/charter/#liaisons) section. Do folks foresee any significant dependencies on other groups (inside or outside W3C) we should mention in this section of the Charter? For examples from other Community Groups, see e.g. the [Web NFC Community Group Charter](https://w3c.github.io/web-nfc/charter/#liaisons) and [Web Bluetooth Community Group Charter](https://github.com/WebBluetoothCG/web-bluetooth/blob/charter-2015-04/charter.md#dependencies-or-liaisons).

I suggest we add at least the [W3C Device and Sensors Working Group](https://www.w3.org/2009/dap/#roadmap) that is defining the [Generic Sensor API](https://w3c.github.io/sensors/), a framework for exposing sensor data to the Web in a consistent way, to be used by concrete sensors (e.g. ambient light, proximity, accelerometer, gyroscope, magnetometer). This could be used to improve the [webvr-polyfill](https://github.com/borismus/webvr-polyfill), and/or enable better code reuse in browsers (Chromium implementation is [in progress](https://crbug.com/606766), starting with ALS, but moving to other concrete sensors soon). There are also reuse opportunities on the spec-level.

I can submit a PR with proposed changes after getting everyone's feedback.

**Comment by toji** [comment]
Closing since we're re-doing the charter and this is just one of many issues that we'll have to re-visit.
