### ISSUE TITLE
Clarify behavior of buttons/axes at reserved indices

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#570]
The "xr-standard" Gamepad Mapping section (added by #553) says, "Additional buttons or axes may be exposed after these reserved indices, and SHOULD appear in order of decreasing importance." However, the values and/or behavior of the buttons or axes at the reserved indices is not defined.

@toji says there is established behavior for Gamepad API, but it doesn't appear to be documented there either. It would be helpful to have some sort of text in the WebXR spec giving a hint of the intended behavior. It might be ideal if this pointed to general guidance in the Gamepad API spec.

**Comment by NellWaliczek** [comment]
Good catch! We'll aim to get this fixed before we snap the next Working Draft, but there's a chance it will get pushed to a subsequent snap.

**Comment by cwilso** [comment]
I will go get gamepad to clarify.

We should add temporary text in WebXR, but this really needs to get solved in Gamepad.
