### ISSUE TITLE
Only head-model hit testing is supported

### ISSUE THREAD

**Issue by Fehler40** [immersive-web/webxr#577]
Hey, 
I'm trying to implement hit-testing in my webXR app. In the onSessionStarted function I set the frame of reference, but I'm forced to do this in 'head-model'.  When I try to set it to 'eye-level' I get this error: `Unhandled Promise Rejection: Only head-model hit testing is supported`

This is my onSessionStarted function: 

```
`onSessionStarted = async () => {
        this.setState({ isARSessionStarted: true, arMessage: 'session started' });
        this.renderer = new THREE.WebGLRenderer({
            alpha: true,
            preserveDrawingBuffer: true,
        });
        this.scene = new THREE.Scene();

        this.renderer.autoClear = false;
        this.renderer.shadowMap.enabled = true;
        this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;
```

        this.gl = this.renderer.getContext();

        await this.gl.setCompatibleXRDevice(this.session.device);
        this.session.baseLayer = new window.XRWebGLLayer(this.session, this.gl);

        const framebuffer = this.session.baseLayer.framebuffer;
        this.renderer.setFramebuffer(framebuffer);       
        
         // this.camera.matrixAutoUpdate = false;
        //  this.camera.position.z = 100;
        this.camera = new THREE.PerspectiveCamera();
        

        this.frameOfRef = await this.session.requestFrameOfReference('head-model');
        this.session.requestAnimationFrame(this.onXRFrame);

    };`

So the behavior of my app is strange. When I want to add an object on the surface, it instead "sticks on the display" and moves with the camera. Is this caused by 'head-model'? Is there a way to fix this? 
I am on iOS in the XRViewer Browser.
Thanks!

**Comment by AdaRoseCannon** [comment]
I'm sorry I think you have the wrong repository. This repository is for designing the WebXR standards which are being implemented by browsers such as XRViewer Browser.

You probably want to post this issue on their repository for this: https://github.com/mozilla-mobile/webxr-ios
