### ISSUE TITLE
Decide what to do with Gamepad.index

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#583]
One issue that we currently have with input sources is that if we have two controllers of the same type without different handedness (think Vive controllers prior to handedness estimation) and then one of them disconnects we have no way of indicating which one it was outside of tracking the pose frame to frame and trying to identify which one the remaining controller is closest to, which... 🤢

The Gamepad API addresses this by leaving holes in the gamepads array, so that a single controller remains in the same index for the lifetime of it's connection. [Developers are opinionated about this approach.](https://twitter.com/stuk/status/1107754849062412288)

I would propose instead that we should use the `Gamepad.index` attribute to uniquely identify devices within a session. The value should be something that monotonically increases with each newly connected device and doesn't actually correspond to the element index in the array at all, which allows us to avoid array gaps. Thoughts?

**Comment by toji** [comment]
Edited the title of this to be a bit more generic, because while I think we could use the index as an arbitrary counter the bigger issue is simply deciding what it should be used for, period. (As pointed out by Nell in https://github.com/immersive-web/webxr/pull/628#discussion_r283589964)

**Comment by cwilso** [comment]
This should just be -1.  Gamepad says index is a signed long.  (Chrome needs an impl. fix.)

**Comment by ddorwin** [comment]
There seems to be a gap between @toji's https://github.com/immersive-web/webxr/issues/583#issuecomment-492079244 29 days ago and a constant value being the fix for this issue. Was the decision to not pursue those earlier ideas made somewhere else or is #690 just a related fix?

**Comment by toji** [comment]
Yes, we should have made that clearer: It may be beneficial to do something along the lines of what I stated in the first comment, but we don't anticipate working that out in time for the VR complete milestone. Since it's possible that `0` will be a valid value in a future system like that, though, and almost certain that `-1` will not be, AND since the Gamepad API spec allows `-1`, we decided that it would be best to make the initial value the clearly-not-a-valid-index one.

**Comment by ddorwin** [comment]
Thanks for the update. SGTM.

**Comment by NellWaliczek** [comment]
A clarification about the original reason this issue was filed... the inputsourceschange event was modified during the hit-testing-explainer design and now has "added" and "removed" attributes that list the XRInputSources that were added and removed respectively.  This, combined with the XRInputSource objects now being tagged as [SameObject], should mean #690 effectively addresses this issue completely.
