### ISSUE TITLE
When we add more options to session creation, do it with a dictionary.

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#591]
This is not an issue so much as a directive. As discussed in #566 it's assumed that we probably will have need of additional arguments beyond the `mode` that will need to be passed into `navigator.xr.requestSession()`, even though we don't have any at this exact moment. When that time comes, the pattern to be used, per #542, is:

```webidl
dictionary XRSessionCreationOptions {	
  XROptionThingy option;
};

partial interface XR {
  Promise<XRSession> requestSession(XRSessionMode mode, optional XRSessionCreationOptions options);
};
```

Called like so:

```js
navigator.xr.requestSession('immersive-vr', { option: value });
```

**Comment by NellWaliczek** [comment]
Closed by #739
