### ISSUE TITLE
Specify if/when new Gamepad objects are created

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#593]
The WebXR spec is not explicit about when to create new Gamepad objects. This was a source of interop problems for the Gamepad API, so we should try to avoid that.

Gamepad API implementations create a new Gamepad object when the state changes. If we decide not to do that for WebXR, we should have a good reason for the inconsistency in the platform and consider the impact on developers and use cases.

**Comment by ddorwin** [comment]
The Gamepad API spec issue is https://github.com/w3c/gamepad/issues/8.

/cc @nondebug

**Comment by Manishearth** [comment]
Ah, I stumbled across this in my implementation too -- it's not clear to me if the Gamepad is dynamic or not.

**Comment by toji** [comment]
The spec has been updated recently to specify that `XRInputSource`s are live, and the `gamepad` attribute on `XRInputSource` has the `[SameObject]` extended attribute. Is that sufficient in this case? We can certainly add a line of text to indicate that the same `Gamepad` instance must be returned from the `gamepad` attribute each time, but that's *literally* the entire purpose of `[SameObject]` so it would feel strange to call this one specific attribute out further.

**Comment by ddorwin** [comment]
That sounds fine. This is different behavior from (some?) Gamepad API implementations, though, so it might be worth calling that out in a non-normative note.

Context: IIUC some developers were comparing `Gamepad` objects between frames, which is not a supported pattern for `XRInputSource`/WebXR.

**Comment by toji** [comment]
Ah, thanks for the context! That does sound worthy of a non-normative note.
