### ISSUE TITLE
Is the XRRenderState object live?

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#600]
Brought up by @toji in https://github.com/immersive-web/webxr/pull/599

Should the result of `xrSession.renderState` be a live object that gets auto-updated with `updateRenderState()`? i.e. in the following code:

```js
let rs = xrSession.renderState;
xrSession.updateRenderState({baseLayer = newLayer});
```

is `rs.baseLayer` `newLayer`? Or does `xrSession.renderState` return a fresh object?

In one case, `XRSession.renderState` is `[SameObject]`, in the other case the `XRRenderState.baseLayer` and `XRRenderState.outputContext` are.

We also have the option to not spec this at all, but we run the risk of code in the wild relying on implementation-specific live `renderState` objects.

**Comment by toji** [comment]
The editors talked about this just now and decided that we'd like the `XRSession.renderState` attribute to be `[SameObject]` and the individual attributes under it to update live on the frame boundaries as already described by the spec.
