### ISSUE TITLE
When a session is shut down, should this clear the xrCompatible flag?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#607]
Currently, ending an XRSession (https://immersive-web.github.io/webxr/#shut-down-the-session) doesn't clear the xrCompatible flag of any WebGL rendering context. As a result, ending a session, then beginning a new session on a device with a different GPU, results in the xrCompatible flag being true, even though the context is using an incompatible GPU.

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/705

**Comment by toji** [comment]
Sorry for the confusion, but I don't think this is a concern. If a session shuts down and another is created with the same XR device we definitely want to keep the compatibility bit valid. The only time that it should become invalid is if the underlying device that new sessions would be created against changes, and we already have it specified that making that change does invalidate the compatibility bits. See http://localhost:8080/webxr/#select-an-xr-device

@NellWaliczek: Is there something else about this issue that I'm not remembering that we wanted to address? Feels like we should have caught this during triage, but maybe we did and there was an aspect of it that we still wanted to look into?

**Comment by asajeffrey** [comment]
Ah, so the flag isn't cleared when the session is shut down, but it is cleared when a new session is begun. That works.
