### ISSUE TITLE
What values to use for untouched Gamepad touchpad?

### ISSUE THREAD

**Issue by jacobcdewitt** [immersive-web/webxr#622]
For WebXR Gamepads, there are two possible ways of reporting the input axis values for a touchpad that is not currently touched:
A) last position at which the touchpad was touched
B) origin (0, 0)

After some discussion, @toji and I agree that option B would be the better choice and that the restriction should be documented in the spec. However, we're not sure if this restriction on touchpad behavior should be in the Gamepad spec and apply to all Gamepads or if it should instead be in the WebXR spec as an additional constraint on how WebXR Gamepads must behave.

**Comment by cwilso** [comment]
We should make a decision on our preferred solution here, and then we'll have to go drive this in the Gamepad spec.

**Comment by NellWaliczek** [comment]
Discussed with @toji and we're both strongly in favor of option B.  To move forward quickly, we'd like to go ahead and land text in WebXR stating this behavior.  @cwilso Can you assist coordinating with the folks working on Gamepad so that we can have one authoritative place for this to be defined?
