### ISSUE TITLE
Xr-standard mapping description lists axes values as being in "axis" array, when it should be "axes" array

### ISSUE THREAD

**Issue by alcooper91** [immersive-web/webxr#627]
https://immersive-web.github.io/webxr/#xr-standard-gamepad-mapping

The table illustrating the xr-standard mapping shows how axis values are mapped out in an "axis" array.  This should probably be listed as the "axes" array so that it aligns with the gamepad spec/the code that would be written.
https://w3c.github.io/gamepad/#gamepad-interface

**Comment by toji** [comment]
Fixed in de8f55231d3a353aaa9a9182cff8d0d7e7fe49d4
