### ISSUE TITLE
Determine how to handle detached Typed Arrays

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#630]
Matrices are currently returned as a `Float32Array`, which is a view over an `ArrayBuffer`. As it turns out, `ArrayBuffers` can be detached and tossed over a worker boundary, which then makes any views into that buffer invalid. In WebXR terms this means that a matrix that was previously returned as a `Float32Array` would no longer provide the matrix data it needs, nor could it be updated in-place if the spec called for it.

We should specify exactly how the spec reacts to detached typed arrays, or alter the spec design to avoid the problem entirely.

**Comment by Manishearth** [comment]
[WebAudio](https://webaudio.github.io/web-audio-api/) does a bunch of stuff with detached array buffers within AudioBuffer, this may be useful.

**Comment by toji** [comment]
Oh, that's very helpful! Thank you!

**Comment by AdaRoseCannon** [comment]
Omg I was literally writing an article about this topic today. That was weird.

**Comment by toji** [comment]
Editors discussed this today. Seems like there's three potential paths to addressing this in the spec text:

**Option 1: You break it, you bought it.**
All of the objects that have `Float32Array` attributes are currently are snapshots, with new objects being returned each time they're updated (usually per frame). This includes `XRView`, `XRRigidTransform`, and `XRRay`. Thus the thinking behind this option says "well, you ripped the guts out of that array, but it's only valid for a single frame anyway so that attribute is just broken forever now. You only have yourself to blame." Downsides to this approach is that it may not lend itself well to environments where multiple libraries are all operating on the same data each frame. Also, it would introduce a constraint down the road where we can't have ANY live objects which expose a `TypedArray`, which also includes things like `XRRigidTransform`s.

**Option 2: Quietly clean up the developers mess**
If we take the `[SameObject]` extended attribute off of all the `Float32Array` attributes, we then open up the option of silently swapping them out any time we want. This enables us to specify that if the `ArrayBuffer` is detached then the next access of the attribute is a new `Float32Array` representing the same data. That doesn't fully solve the multi-library issue, since it's possible that multiple points in the code could all grab a reference that one of them then detaches the buffer from unexpectedly, but it helps the API be more resilient.

**Option 3: Snapshot all the arrays!**
A more drastic version of Option 2 that avoids the multi-reference issue (at a cost) is to say that EVERY access of the matrix returns a new `Float32Array`. For ergonomics sake we'd probably want to change the attributes to methods if we went this route, as that suggests the new allocation better. Obviously the downside is that we're adding more overhead to any use cases that access the matrices from more than one location.

**Option 4: Go full DOMMatrix**
One final possibility is to switch away from using the `Float32Array` representation directly, and if we did that the only really reasonable route is to switch over to using `DOMMatrix` (which would at least be consistent with our use of `DOMPoint` elsewhere in the API.) `DOMMatrix` does have a method that returns a `Float32Array` version of the data, so developers could still get to it, though it allocates a new copy each time. Biggest downside is that given that WebGL/WebGPU both operate natively on `TypedArray`s to communicate data like matrices to shaders, it's presumed that a large number of developers would need the data in that format anyway. As a result going through `DOMMatrix` for each matrix each frame would effectively double the amount of allocations required to access the matrix data in the desired format. (Note that a `DOMMatrix` can be constructed from a `Float32Array`, so going the other direction has approximately the same amount of overhead but less expected use.)

**Comment by klausw** [comment]
> Option 4: Go full DOMMatrix

As far as I can tell from the [DOMMatrix spec](https://www.w3.org/TR/2013/WD-matrix-20130919/#three-dimensional-attributes), a DOMMatrix is required to have type "double" attributes:

```
partial interface DOMMatrix {
    attribute unrestricted double m11;
...
```

This would mean that converting DOMMatrix to/from Float32Array involves a precision downgrade/upgrade in addition to just memory allocation.
