### ISSUE TITLE
What happens if the Handedness/TargetRayMode of a controller changes?

### ISSUE THREAD

**Issue by alcooper91** [immersive-web/webxr#632]
Until PR #618 the Handedness and TargetRayMode attribute on the XRInputSource was tagged with "SameObject." 618 removed this attribute because it cannot be applied to enums. If it is the intention that these values should not change on a given XRInputSource, then that implies that the UA's need to create a new XRInputSource if either of these values of a given object change (an example of this would be the Vive controllers, which lack natural handedness but instead get implicit handedness reported by the runtime based on their positioning).  However, as it is currently written the spec doesn't mention what should happen if these values of a controller were to change, which could lead to divergent implementations where some UAs re-create the controller, and some simply update them on the existing controller.

**Comment by cwilso** [comment]
Consider as fixed with #628.
