### ISSUE TITLE
Clarify the relationship between "XR device" and "inline"

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#635]
The language about the "XR device" is a bit confusing as it relates to `"inline"` sessions, especially on clients with an external headset (e.g., desktop).

https://immersive-web.github.io/webxr/#xr-interface says:
> An XR object has an XR device... which... represents the active XR device

and https://immersive-web.github.io/webxr/#xr-device says:
>An XR device is a physical unit of hardware that can present imagery to the user. On desktop clients, this is usually a headset peripheral.

>An XR device has a list of supported modes (a list of strings) that contains "inline"...

On desktop, `"inline"` and `"immersive-vr"` sessions are on two physical units of hardware.
Is the inline capability really a supported mode of the `XR device` representing the HMD?

Note that `"inline"` can't be a provided by a separate XR device because that would prevent using `"inline"` and `"immersive-vr"`sessions at the same time, at least with the current text.

It may be that what we really want is that _user agents_ will always support `"inline"` sessions, but that doesn't necessarily mean every "XR device" needs include it in its "list of supported modes."

**Comment by Manishearth** [comment]
You can have a browser in VR (e.g. Firefox Reality), and that 2d browser could have a page containing a canvas that's a  little window into VR.

But yeah I think making this a UA thing makes sense.

**Comment by ddorwin** [comment]
Related: https://github.com/immersive-web/webxr/commit/0e63561656e268c508503e7496d360b548af5eb4 removed a reference to the inline mode when adding a reference to the "XR device." I'm not sure the new check actually covers inline. @toji

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/704
