### ISSUE TITLE
oninputsourceschange event out of sync between spec and explainer

### ISSUE THREAD

**Issue by alcooper91** [immersive-web/webxr#639]
PR #493 looks like it changed the language around what data was expected to be sent with the inputsourceschange event (though the title of that PR doesn't seem to imply that change); however the spec: https://immersive-web.github.io/webxr/#eventdef-xrsession-inputsourceschange still specifies that that event is of type XRSessionEvent.

Which is the correct event type?

**Comment by NellWaliczek** [comment]
This is already being fixed by the currently open #628
