### ISSUE TITLE
requestSession() should set "pending immersive session" synchronously

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#643]
The requestSession() algorithm currently sets "pending immersive session" to true and false in the asynchronous ("in parallel") part of the algorithm.

I believe this makes it possible to have concurrent outstanding requests (i.e., if two calls are successive). Also, I'm not sure there is any inherent synchronization between runs of "steps in parallel." Thus, the "in parallel" part of the algorithm might actually run at the same time. I believe the right way to handle synchronization is on the main thread, which is the synchronous part of the algorithm.

Thus, "pending immersive session" should be checked and set to true in an early synchronous part of the algorithm, and it should be cleared inside a task queueing a task (to the main thread).

**Comment by ddorwin** [comment]
Addressing #644 will make it easier to address this issue.

**Comment by ddorwin** [comment]
Note that per https://www.w3.org/2001/tag/doc/promises-guide#shorthand-manipulating, "Resolve promise with session" in the "in parallel" steps is shorthand for, among other things, queueing a task. In this case, we probably need to make explicitly queue a task that includes resolving the promise. See, for example, step 10.10 of https://w3c.github.io/encrypted-media/#dom-mediakeysession-generaterequest.

**Comment by ddorwin** [comment]
"pending immersive session" should also be cleared before _rejecting_ the promise. Since the "reject promise with..." steps actually queue a task, the promise will be rejected and the executor may run before "pending immersive session" is cleared. This could lead to unexpected behavior for an application that requests a session in the executor's reject function.

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/706
