### ISSUE TITLE
Include synchronous steps in procedural algorithms

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#644]
The spec currently uses the following pattern:
>When the requestSession(mode) method is invoked, the user agent MUST return a new Promise promise and run the following steps in parallel:

The examples in the TAG's Promises Guide (https://www.w3.org/2001/tag/doc/promises-guide#async-algorithms) use a different pattern where the creation and returning of the promise are in the numbered steps.

In addition to being consistent with this guide and, presumably, other specs, this pattern helps avoid/address issues like #643.

https://w3c.github.io/encrypted-media/#dom-mediakeysession-generaterequest is one such example and includes synchronous checks of state similar to those in #643.

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/700
