### ISSUE TITLE
Do not use successive steps for handling conditionals in algorithms

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#647]
The spec currently uses the following pattern for conditionals where there are steps to be run in multiple branches:
>1. Do some stuff.
>1. If foo, do...
>1. Else do...
>1. Do more stuff.

IMO, the steps would be easier to read if the branches were more differentiated from the other steps. See, for example, see steps 10 and 12 of https://w3c.github.io/encrypted-media/#get-supported-configuration-and-consent.

**Comment by ddorwin** [comment]
On a related note, the requestSession() has an _If - Else if - Else if_ set where each of the conditionals is an unrelated error condition. This may be a good candidate for the "Follow the steps for the first matching condition..." pattern. (Note that this may need to be otherwise refactored per https://github.com/immersive-web/webxr/issues/643#issuecomment-492444537.)

**Comment by Manishearth** [comment]
Working on this

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/657
