### ISSUE TITLE
Inconsistency between explainer and spec for inline sessions with no device.

### ISSUE THREAD

**Issue by billorr-google** [immersive-web/webxr#658]
Maybe related to issue #635.

In the spec, the algorithm for RequestSession claims:
If the XR device is null
Reject promise with null.

However, the explainer says:
UAs implementing the WebXR Device API must guarantee that inline sessions can be created, regardless of XR device presence, unless blocked by page feature policy.

Which is correct?  Should all implementations be required to support a "device-less" inline mode?

**Comment by billorr-google** [comment]
If I assume the explainer is correct, should the supportsSession for inline return true if there is no device and we are querying for inline?

**Comment by NellWaliczek** [comment]
Chatted with @toji.  The explainer is correct and this is a spec bug.

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/704
