### ISSUE TITLE
Should we invert the Gamepad Y axes range?

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#664]
The Gamepad API defines the following recommend mapping for axes:

> -1.0 SHOULD correspond to "up" or "left", and 1.0 SHOULD correspond to "down" or "right".

(https://w3c.github.io/gamepad/#dom-gamepad-axes)

The recommendation of "up" as negative appears to conflict with the data that is output from pretty much every XR API that we've encountered to date, and isn't particularly intuitive either. Is this an area where we want to override the base gamepad spec to ensure more consistent behavior with the native XR APIs?

**Comment by klausw** [comment]
I think this is important to get this consistent ASAP since there's no good application-side workaround. There aren't any trappable errors or obviously-invalid values, and having to do case-by-case overrides based on device and UA version would get ugly.

**Comment by NellWaliczek** [comment]
Yep.  This is kind of not great.  We need to coordinate with the Gamepad folks on whatever we end up deciding.  Assigning this issue to the June milestone with the intention that we address asap.  @cwilso Can we get a meeting scheduled with the Gamepad folks for the first or second week of June to cover this and the other Gamepad dependent issues?

**Comment by AdaRoseCannon** [comment]
Damn sorry i don't know why the bot failed there 😕

**Comment by AdaRoseCannon** [comment]
/triage fixed the triage issue it should work in the future

**Comment by toji** [comment]
This was brought up on a previous working group call, and the general sentiment seemed to lean towards adhering to the gamepad API convention in this case, even if it may seem counterintuitive to some. As such, since this is likely a minor inconvenience to developers at worst, the editors feel it's appropriate to make the call to not override the gamepad API behavior. Given that the spec text already states:

> Gamepad instances returned by an XRInputSource's gamepad attribute behave as described by the Gamepad API, with several additional behavioral restrictions...

it looks like we're already covered in this regard. Closing.

**Comment by NellWaliczek** [comment]
Worth adding a non-normative note explaining that this may mean implementers need to flip axes depending on their underlying XR platform?
