### ISSUE TITLE
Should XRSession.inputSources be tagged [SameObject]

### ISSUE THREAD

**Issue by alcooper91** [immersive-web/webxr#667]
There's a few notes throughout the spec that maybe imply that it should be, but no concrete definition either way.

For examples of notes that imply that maybe it should be:
https://immersive-web.github.io/webxr/#xrinputsourcearray-interface, mentions that the XRInputSourceArray type is used in favor of the FrozenArray type since the objects are expected to change.
The note under: https://immersive-web.github.io/webxr/#xrinputsource-interface indicates that the inputSource objects themselves are "live", but nothing indicates whether we expect the XRInputSourceArray to be live or not.

**Comment by jacobcdewitt** [comment]
You mean XRSession.inputSources (with the "s"), right?

**Comment by toji** [comment]
The answer is "Yes". #669
