### ISSUE TITLE
Define how a WebGLFramebuffer is allocated from XRWebGLLayerInit options 

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#671]
Called out by @NellWaliczek during review of #656. We should be more explicit about exactly how the options specified in `XRWebGLLayerInit` contribute to the `framebuffer` that is allocated for an `XRWebGLLayer`. Specifically the `alpha`, `depth`, and `stencil` options.

**Comment by Manishearth** [comment]
fixed in https://github.com/immersive-web/webxr/pull/800
