### ISSUE TITLE
Describe the purpose of XRRenderState

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#677]
The description at https://immersive-web.github.io/webxr/#xrrenderstate-interface currently says, "There are multiple values that developers can configure which affect how the session’s output is composited. These values are tracked by an XRRenderState object." Most [1] other sections describing a type begin with "An XRFoo represents..."

In addition, use of `XRRenderStateInit` and `XRRenderState`, including how and when the former is applied, is non-obvious, so it would be nice to provide more information on this. Some of that may belong in `updateRenderState()` (see https://github.com/immersive-web/webxr/issues/676), but it probably makes sense to document the overall design and use in one location.

[1] `XR` and `XRSession` are notable exceptions.

**Comment by ddorwin** [comment]
Specifically, everything in this structure gets applied on frame boundaries.

It may also be worth noting the reasons for this design in a non-normative note. For example, all values are optional and do not have default values to allow for extension. Specifically, applications don't need to set values they don't care about and, in the future, there may be members values where the default may be set by the platform.

**Comment by ddorwin** [comment]
As noted in #680, the current text may not encompass all values. See https://github.com/immersive-web/webxr/issues/680#issuecomment-500618617 for info on the intent.

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/703

Not sure if this is quite what you wanted, but it's a shot.
