### ISSUE TITLE
Consider replacing "list of pending render states" with "pending render state"

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#678]
Having a list just adds a little more complexity and potential confusion for the user, so it'd be nice to collapse it if possible.

It seems that `updateRenderState()` could maintain a single nullable "pending render state" that gets updated (as in step 5 of https://immersive-web.github.io/webxr/#apply-pending-render-states) and when not null gets applied in https://immersive-web.github.io/webxr/#apply-pending-render-states.

**Comment by toji** [comment]
Editors talked about this and remembered that the current design was due to a previous design that had us resolving a promise every time a change was applied. That's not longer a concern, however, so this simplification is fine.

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/701
