### ISSUE TITLE
Remove XRSession parameter from XRLayer.getNativeFramebufferScaleFactor()

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#682]
The layer itself was created with an XRSession, so we don't need to pass one into this api.

**Comment by toji** [comment]
This is a static method, so the session is necessary to know what session you are asking about. It has to be static because the value it produces is used when calling the layer constructor, so it wouldn't make sense for developers to have to construct a layer prior to calling it.

**Comment by ddorwin** [comment]
FYI, I filed a related issue: https://github.com/immersive-web/layers/issues/5.
