### ISSUE TITLE
"XRInputPose is not defined" after Chrome75 Update

### ISSUE THREAD

**Issue by koboldMaki** [immersive-web/webxr#683]
Today updated Chrome to new Version 75.0.3770.80 (Win10 - 64bit) and webXR dont work any more. Neither my local project with use of this files here, nor the live-samples from your page here. 
Error is:
`Uncaught ReferenceError: XRInputPose is not defined  
at WebXRVersionShim._applyPatch (webxr-version-shim.js:511)  
at new WebXRVersionShim (webxr-version-shim.js:140)  
at input-selection.html:71  
at input-selection.html:268`

Using an Oculus Rift and Chrome Flags (XR/VR) are set. So, what can i do to get it to work again?
Thanks

**Comment by cwilso** [comment]
This is a change in the spec that Chrome now reflects.  (WebXR is still under active development, and not yet stable.)

**Comment by cwilso** [comment]
(Should have said - your code needs to be updated.)
