### ISSUE TITLE
Link "fire an XRInputSourceEvent" text to the related algorithm

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#711]
https://immersive-web.github.io/webxr/#xrinputsourceevent-interface contains an algorithm that begins with:
> When the user agent fires an `XRInputSourceEvent` _event_ it MUST run the following steps:

I believe that all of the references to "... fire an `XRInputSourceEvent`..." in other algorithms should link (those three words) to this algorithm.

**Comment by ddorwin** [comment]
Related: Should there be guidance related to ensuring these events are delivered before the next rAF callback? That may be implied/specified by text like the following, but it would be nice to make the intent obvious, potentially with a non-normative note.
> When an XR input source for XRSession session begins its primary action the UA MUST run the following steps:

**Comment by Manishearth** [comment]
This is a tiny bit more than just an editorial fix, because as it stands we never create the `frame` attribute, and _when_ that gets created is kind of important.

**Comment by Manishearth** [comment]
Fixed in #797
