### ISSUE TITLE
Unstable API banner implies the explainer is more stable

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#713]
The Unstable API banner currently says
>Parts of the API represented in this document are incomplete and may change at any time.
>
>For additional context on the use of this API please reference the WebXR Device API Explainer.

Given the context of the header and first line, the second line could be interpreted as saying that the explainer is more stable and should be referenced instead.

**Comment by Squareys** [comment]
(Related to https://github.com/immersive-web/webxr/issues/672: Remove the annoying "Unstable" banner)

**Comment by toji** [comment]
Banner has been removed.
