### ISSUE TITLE
Querying user consent status

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#722]
**[Disclaimer: This issue is one of several being filed to capture discussions that began either on #638, on #689, or at the most recent F2F]**

This issue is dependent on the outcome of #720. If it is possible to request user consent in the middle of an immersive session, developers will likely need a way to determine if an API call will trigger a consent prompt so that they can explain to the end user that this will happen. For non-XR features, the Permissions API services this need via the query() API.

This issue tracks the need to determine if WebXR should allow for the ability to check if a prompt will be shown. It also track the discussion about what (if any) relationship WebXR should have with the existing Permissions API.

(Note, this issue will probably be one of the later ones that gets solved out of this batch as it is dependent on a number of others landing first)

**Comment by ddorwin** [comment]
The answer likely depends on the answer to #725.

**Comment by Manishearth** [comment]
We seem to be leaning towards the direction of relying on the existing permissions API _to some extent_ at least, so there's a good chance this issue will be unnecessary, based on what we settle on.
