### ISSUE TITLE
[Feature Policy] Should "inline" with sensors ("magic window") be controlled by the same feature policy as immersive VR (headsets)?

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#730]
[This is one of the decisions to make as part of resolving #308 and #729.]

When deciding on the policy-controlled features for WebXR (#729), we'll need to decide whether to group `"inline"` sessions with sensor data with 6 DoF headsets and `"immersive-vr"`. Especially if pose data for inline sessions is limited to address privacy concerns and avoid the need for consent, should it be controllable by Feature Policy? Or maybe there will be various levels of sensitive data for inline sessions, and the determination should be made based on that.

**Comment by ddorwin** [comment]
Similar questions could be asked related to reference spaces. For example, `"bounded-floor"` poses more privacy concerns (i.e., ` boundsGeometry`) than `"viewer"` or `"local*"`.

For some scenarios, such as embedding a 360 video, there is no need for the embedding page to allow the embedded origin access to the more sensitive reference spaces. Of course, it may be too much to expect the embedding page to understand this, and more levels of control add complexity. This could also limit what the embedded site can do in the future as it improves its experience.

**Comment by ddorwin** [comment]
The outcome of #308 is that all VR features are controlled by `"xr"`. Thus, the answer to this question is "yes." 

/agenda to ensure there are no concerns with this answer. If not, it can be closed. #731 is similar. It's also worth reading #729, though that one is only partially answered by #308.

**Comment by toji** [comment]
As noted on #731, Nell and I revisited this issue and our impression was that polyfilling is an appropriate way to address scenarios where a developer wants inline, sensor-driven XR access in an environment where the "xr" feature policy is blocked. It allows for a significantly cleaner feature policy, though it implicitly means that motion based on device-orientation or generic sensors is gated on the feature policies governing those APIs. Depending on the resolution of #768 this will either naturally be the desired behavior or, at worst, a minor inconvenience that causes the polyfill to fall back to desktop-like behavior on mobile devices.
