### ISSUE TITLE
[Feature Policy] Should (sensorless) "inline" "viewer" sessions be allowed without the XR policy-controlled feature?

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#731]
[This is one of the decisions to make as part of resolving #308 and #729.]

There shouldn't be any privacy concerns for `"inline"` sessions using the `"viewer"` reference space. Should it be possible for applications to create such sessions and reference spaces without any WebXR-related policy-controlled feature enabled (i.e., without `"xr"` or `"vr"`) or should it not be possible to successfully request any session without a/the "base" feature enabled?

**Comment by ddorwin** [comment]
The outcome of #308 is that all features included in "VR complete" are controlled by `"xr"`. Thus, the answer to this question is "no." 

/agenda to discuss this along with #730 - see that issue for more details.

**Comment by toji** [comment]
Nell and I talked this over again today, and the general response that we came to was that polyfilling is an appropriate way to address scenarios where a developer wants inline, sensorless XR access in an environment where everything else is blocked. It allows for a significantly cleaner feature policy as well.
