### ISSUE TITLE
Allow features to be marked as deferrable

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#740]
In the discussion on https://github.com/immersive-web/webxr/issues/720#issuecomment-504609177, we came to the conclusion that consensus had been established on Optional and Required features as described in #723, but not on the requirements for Deferrable features.  This issue is intended tracks adding Deferrable features to the spec when the outstanding questions have been addressed.  Based on my understanding, those questions are:
* Given that a deferrable feature may need to show a consent prompt in the middle of an Immersive session, agreement is necessary on the characteristics of Trusted Immersive UI. (#718)
* If Trusted Immersive UI is not present in a UA, what should be done with deferrable features with require explicit consent?
* Or should Trusted Immersive UI of some form be a conformance requirement?  (#719)
* Should a developer be able to discover if a using a deferrable feature will trigger a consent prompt?  This includes both indirect and direct ways of finding out the answer (#722, #725)

Any other considerations I'm missing?

**Comment by avadacatavra** [comment]
It seems like if we decide to do [this](https://github.com/immersive-web/webxr/issues/719#issuecomment-532065474), then deferrable features aren't necessary

A UA would have three options for a mid-session prompt:
1. Ignore it and continue with the session as instantiated
2. Use a trusted immersive UI to handle the prompt
3. Pause immersive mode, handle the prompt, then reenter immersive mode

**Comment by kearwood** [comment]
Mozilla intends to implement permissions prompts that can appear at any time (including during active XR sessions).  For FxR, this means that deferred sessions will not be required.  There may be a short period where mid-session prompts may be ignored, prior to such an implementation which will be added ASAP.

**Comment by kearwood** [comment]
The initial FxR implementation will be taking the #3 option (Pause immersive mode, handle the prompt, then reenter immersive mode).  Later updates to FxR may implement #2 also.

**Comment by avadacatavra** [comment]
Ok, so let's ask for consensus on this.

It sounds like *most* UAs don't feel that they need deferred features, because they will take one of two paths:
1. Use a trusted immersive UI to handle the prompt
2. Use a trusted non-immersive UI, pausing the immersive session, to handle the prompt

If the UAs can comment here on whether they need deferred features, that would be great

**Comment by Manishearth** [comment]
No UAs seem to have spoken up about a need for this, and we see a clear path for adding this backwards compatibly in the future if a UA does need it. Closing for now.
