### ISSUE TITLE
Spatial tracking on inline sessions when viewed within an XR headset

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#756]
First up, I'm not suggesting the core spec include a diorama reference space.  I filed that in proposals a while back, which is absolutely the right place to track it.  (See https://github.com/immersive-web/proposals/issues/31) 

I'm assuming we're expecting inline sessions to be allowed to be created for a 2D page being viewed from within an XR-headset.  If we allow spatial tracking to be enabled for that session, what does that mean for view/projection matrices?

The current designs have developers rendering directly into the canvas's default framebuffer, which means no stereoscopy for now. (We'll definitely need to address this in the potential layers module being considered for design).  However, a bunch of questions now occur to me, some of which might have impact on the core spec, and I'd super appreciate a quick sanity check

The questions that occurred to me are:
* With the reference space types we have today, what is expected to happen to the view/projection matrices provided in response to the user moving to the left or right of the floating browser window?
* In the future, would we require all reference spaces for an inline session being viewed within a head-worn XR device be required to report at least 2 views?
* If not, does that mean we'd want to create a specific reference space for that purpose?  (for ease of discussion, let's call it `diorama`).  Let's assume such a reference space will be it's own feature in the `XRSessionInit` feature arrays.
* If a developer creates both a `local` and `diorama` reference space, would that cause `getViewerPose()` to  return a different number of views depending on the supplied reference space? If so, we probably need to update the spec text so that the list of views isn't owned (even indirectly) as a single property of the session.
* Are there other implications of inline sessions with spatial tracking that are different when in a head-worn XR device?
* Should we be considering disallowing spatial tracking for inline sessions inside an XR headset for now?

**Comment by ddorwin** [comment]
I think the assumed answer to the last question has been "yes" as the privacy implications/considerations have not been discussed or addressed.

Related to this, the last sentence of the non-normative note in https://immersive-web.github.io/webxr/#xr-device-concept seems to imply that this _is_ supported and may need to be updated depending on the outcome of this issue.
>In case the browser is already running on an XR device, the inline XR device will be the same device, and may support multiple views.

**Comment by toji** [comment]
Bumping from Aug to Oct so we can close that (woefully late) milestone. What was the decision here again?

**Comment by rcabanier** [comment]
I thought we were going to remove spatial tracking for inline sessions since noone had interest in supporting them

**Comment by NellWaliczek** [comment]
The lack of interest was expressed for supporting tracking on inline sessions being viewed in an immersive headset, not inline sessions in general.  There is no need to make any spec text changes in response to this statement though because UAs are free to reject the request if tracking is marked as required and they wish to do so.

That said, my original concern had to do with accidentally blocking ourselves from being able to add support later for diorama style rendering through.  @toji has convinced me that there is no actually issue here by pointing out that inline sessions today only allow the use of the default framebuffer, meaning that sterescopinc rendering to each eye isn't allowable by the API.  If/when we decide to support this at a framebuffer level, we will need to consider the right approach for doing so but it will be independent of the type of spatial tracking.

Based on these points, I'm closing issue since it doesn't appear to be a problem.
