### ISSUE TITLE
Split the spec into multiple modules

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#758]
We've collectively decided that future development of the spec should happen across multiple logical modules. This issue is to track making that split actually happen.

The modules that we know need to be created initially are:

- The core WebXR spec (this repo)
- An AR module, which includes the `immersive-ar` mode and `XRRay` from the current spec.
- A Gamepad modules which includes all Gamepad API integration logic.

**Comment by cwilso** [comment]
Link to modularization proposal: https://github.com/immersive-web/administrivia/blob/master/modules.md.

**Comment by blairmacintyre** [comment]
@cwilso looking at that doc, lighting estimation should be moved from "future" up to AR.
