### ISSUE TITLE
Explore solution for mid-session consent prompts

### ISSUE THREAD

**Issue by johnpallett** [immersive-web/webxr#766]
This issue tracks exploring a solution to allow mid-session consent prompts.

For context, #751 suggests blocking mid-session consent requests until a suitable solution for such requests can be found. 

The following related issues include considerations for mid-session consent prompts:

#751 suggests that some platforms might not allow mid-session prompts, so developers will need some method of determining whether or not they are allowed on a given platform, or allow the UA to ensure permission requests are handled appropriately in a manner that works predictably across platforms.

#726 tracks determining what, if any, restrictions might be placed on consent/permission requests from non-XR APIs. For example, are there non-permission consent flows that need to be considered?

#723 proposes deferrable features which might be an approach for cross-platform compat.

#718 and #719 explore trusted UI

#702 explores how permissions and WebXR features should interact

**Comment by johnpallett** [comment]
Note: The solution to mid-session consent prompts might also inform the [Navigation incubation](https://github.com/immersive-web/navigation/issues/6)

**Comment by Manishearth** [comment]
We discussed trusted UI stuff at TPAC and the consensus seemed to be that UAs already have an idea of how to do this kind of thing, and there's no need to specify exactly how they should, instead leaving the specifics up to their discretion.
