### ISSUE TITLE
Remove unnecessary or redundant information from "Security, Privacy, and Comfort Considerations" 

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#776]
The **Security, Privacy, and Comfort Considerations** section of the spec now has some information which is redundant, unnecessary, or possibly conflicting since we've migrated a bunch of content over from the privacy explainer. Let's do a cleanup pass over it and remove any older content that isn't needed.

**Comment by Manishearth** [comment]
cc @avadacatavra a lot of this has been cleaned up now, do you feel that there's anything left for us to do here?

**Comment by avadacatavra** [comment]
I'm ok with closing this
