### ISSUE TITLE
Requirements for native viewport size?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#777]
Over in https://github.com/immersive-web/webxr-test-api/issues/37 there is a discussion about whether WebXR tests can assert anything about viewport sizes. The motivation for this is to make sure that the dimensions being reported are based on the device, not based on the canvas providing the WebGL rendering context. (This was a bug that Servo had, so we'd like to make sure we don't regress.) In https://github.com/immersive-web/webxr-test-api/issues/37#issuecomment-514347004, @alcooper91 said "I’m unable to find anything in the WebXR spec calling out any requirements for sizing the canvas/viewport, so the output size is largely up to the UAs."

This is true, there is text at https://immersive-web.github.io/webxr/#native-webgl-framebuffer-resolution about the native viewport resolution, but there is no text about a native viewport size. https://immersive-web.github.io/webxr/#list-of-viewports requires that the XRSession keep a list of viewports, but nothing about the size of the viewports.

Can we add matching requirements for viewport size?

**Comment by toji** [comment]
It's slightly difficult to put much in the way of meaningful requirements in place here that don't feel arbitrary. I think it should be non-controversial to say that is must be a valid viewport in that the viewport must be _at least_ 1x1 in size, and the coordinate must all lie within the framebuffer. There's already a documented requirement in the spec that they be non-overlapping. Beyond that I'm not sure, as we do want to allow plenty of UA/platform-specific behavior here. (Some devices change the viewports every frame, for example.)

There's definitely some common sense behavior you'd expect from the viewports but are hard to justify putting into the spec text. Most of us would recognize an 8x1024 viewport as absurd for this kind of use, but I could also probably invent some silly potential uses such a thing given an overabundance of spare time, so it's really just a question of what limitations we'd actually benefit from.
