### ISSUE TITLE
Additional situations when XRInputSource.profiles should be empty

### ISSUE THREAD

**Issue by jacobcdewitt** [immersive-web/webxr#781]
In the spec, "For example, if the gamepad attribute is not null the profile identifies the mapping of the buttons and axes of the attribute of the XRInputSource." Does this imply that the profiles list should be empty for an XRInputSource that does not have a gamepad? If not, then some text clarifying that it's still useful even without a gamepad would be helpful.

Also, should the profiles list be empty for transient input sources? For example, WMR voice commands are transient input sources that can occur in immersive sessions.

**Comment by jacobcdewitt** [comment]
@toji - any idea when this will be resolved?

**Comment by toji** [comment]
FYI: discussion of when empty `profiles` arrays are appropriate is currently happening in https://github.com/immersive-web/webxr-input-profiles/issues/14

**Comment by Manishearth** [comment]
@toji That issue closed out, but it's not clear what the resolution as it relates to this issue was. Do you have additional info?

**Comment by toji** [comment]
So the behavior that we generally settled on in immersive-web/webxr-input-profiles#14 is that UAs are not forced to provide profile strings. The most common expected circumstances are that either the UA doesn't know how to describe the device it's exposing, in which case no description is going to be better than an inaccurate one, or the UA is intentionally masking profiles for privacy reasons. I'd also expect that some transient input sources may fall into that bucket, but it's worth noting that we at least have a `generic-touchscreen` input profile.

I don't think we need to explicitly limit it to a particular set of circumstances, though, and instead focus on emphasizing that the user experience will be better the more accurately the UA is able to report the device profiles. I'll put together a spec change that communicates that.
