### ISSUE TITLE
Informing apps which optional features were granted?

### ISSUE THREAD

**Issue by klausw** [immersive-web/webxr#794]
If I'm reading the spec right, the requestSession algorithm includes [list of enabled featues](https://immersive-web.github.io/webxr/#xrsession-list-of-enabled-features) as an internal implementation detail, but as far as I can tell there's no direct way for an application to tell if a requested optional features was enabled or not?

At this time, the only defined features are reference space names, and for these the corresponding requestReferenceSpace call indicates if it's available, but this may not be a good fit for future optional features where there may not be an easy way to check if they are enabled, for example if they don't cause direct observable changes to existing APIs.

For example, some optional features may be be related to performance parameters, i.e. fixed-foveated rendering where the app may want to adjust its graphics when it's in effect. Or a hypothetical optional feature asking the UA to show instructions how to initiate tracking for handheld AR, where the app would need to know if the UA is doing so to decide if it it needs to show its own instructions instead.

Instead of having feature-specific "is this enabled" checks that may have large variations, would it help to have a common way to check for this? 

One approach would be to expose the set of enabled features directly as a session property, i.e. a `getEnabledFeatures` call returning a list of strings or XRFeature objects.

Alternatively, a more specific `isOptionalFeatureEnabled` call could potentially return multiple values such as true / false / unknown / in progress / invalid, where for example "in progress" would mean that it's still indeterminate (i.e. "bounded" reference space is supported, but the device hasn't reported bounds yet, so a requestReferenceSpace promise would still be unresolved), and "invalid" could mean that this was rejected due to an unsupported combination of mode and features. This has some privacy implications, for example there presumably shouldn't be a "supported by device but declined by the user" state.

**Comment by cabanier** [comment]
> 
> One approach would be to expose the set of enabled features directly as a session property, i.e. a `getEnabledFeatures` call returning a list of strings or XRFeature objects.

👍

**Comment by klausw** [comment]
/facetoface

(Not the most urgent issue, but I think it would be good to discuss in case there should be an API change to expose granted features.)

**Comment by Artyom17** [comment]
Agreed that we need a way to detect if a feature was granted or not. Examples, how Klaus said on face-to-face in Fukuoka: optimizations hints, like foveation rendering or chromatic aberration correction.
