### ISSUE TITLE
Consent requirement should not be normative

### ISSUE THREAD

**Issue by mounirlamouri** [immersive-web/webxr#801]
```
Some feature names, when present in the requested features list, require that user intent to use the 
feature is well understood, via either explicit consent or implicit consent. The following table 
describes which features require consent prior to being enabled:
```

The paragraph should be clear that these are recommendations to the implementation (with the usage of MAY). Specifications should recommend UI flows but not enforce them.

**Comment by NellWaliczek** [comment]
The phrase "user intent" does not imply the presence of any required UI.  That is left to the user agent via the phrase "explicit or implicit consent".  This language was fairly closely taken from the Permissions specification.  For more information on the reasoning behind this choice, please consult with @johnpallett
