### ISSUE TITLE
Main spec should link to Gamepad module

### ISSUE THREAD

**Issue by jacobcdewitt** [immersive-web/webxr#803]
It would be helpful to have the main spec link to the WebXR Gamepad module spec documentation, probably in the XRInputSource section: https://immersive-web.github.io/webxr/#xrinputsource-interface

Otherwise, people reading the main spec might be unaware that there can potentially be Gamepads on the XRInputSource objects. Even if they are aware of this, the official documentation is difficult to find.

**Comment by NellWaliczek** [comment]
Great idea.  Thanks!
