### ISSUE TITLE
Should XRRigidTransform.matrix be [SameObject]?

### ISSUE THREAD

**Issue by jacobcdewitt** [immersive-web/webxr#808]
The other `readonly Float32Array` attribute in the spec, `XRView.projectionMatrix`, is marked as `[SameObject]`, but `XRRigidTransform.matrix` is not.

**Comment by toji** [comment]
Yes, it should be. The matrix values are not expected to change for the lifetime of the `XRRigidTransform` object. We do expect it to be lazily evaluated in many cases, but that can be done without violating the `[SameObject]` behavior.

**Comment by Manishearth** [comment]
So while the values are always the same, the matrix array object itself may change, see https://immersive-web.github.io/webxr/#xrrigidtransform-obtain-the-matrix

We recompute the array whenever its buffer is "detached", so this can't be `SameObject`.

That said, we should be _removing_ `SameObject` from `projectionMatrix` and giving it a similar "obtain" algorithm.

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/830
