### ISSUE TITLE
Update XR Compositor section to be more generic about layer types

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#812]
In order to more easily enable future layer types (ex: XRWebGPULayer), we probably want to change this text from:

> The compositor MUST use an independent rendering context whose state is isolated from that of any WebGL contexts used as XRWebGLLayer sources.

to something like...

>The compositor MUST use an independent rendering context whose state is isolated from that of any rendering contexts used as XRLayer sources.

(I'm not in a place to easily submit a PR, so filing an issue to not forget!)

**Comment by toji** [comment]
Agreed with the sentiment here, and just wanted to point out that `XRLayer` is not (currently) an actual type within the spec, so we should likely stick to language along the lines of:

> ... isolated from that of any rendering contexts used by the `baseLayer`.

or, even more generically:

> ... isolated from that of any rendering contexts created by the document.

**Comment by NellWaliczek** [comment]
> The compositor MAY composite additional device or user agent UI over rendered content, like device menus.

Do we need to define the blending technique here?  I suspect no, because the developer will never know that it happened and the compositor will know what to do.  Does that make sense? @rcabanier ?

**Comment by modulesio** [comment]
> The compositor MAY composite additional device or user agent UI over rendered content, like device menus.

This might not be the right issue for it, but doesn't this sentence open up major concerns with security/spoofing? This feels like it should be disallowed for the same reasons navigation was punted on.

**Comment by rcabanier** [comment]
> Do we need to define the blending technique here? I suspect no, because the developer will never know that it happened and the compositor will know what to do. Does that make sense? @rcabanier ?

I agree that we don't need to define the blending technique. It's up to the UA's discretion as how they want to present this additional content.

**Comment by rcabanier** [comment]
> The compositor MUST also run in separate thread or processes to decouple performance of the page from the ability to present new imagery to the user at the appropriate framerate.

I don't quite follow what this sentence is trying to convey. Is it that compositor should draw other UI or the camera feed at the required fps even if the session's framerate drops below that?

Maybe it can be reworded to:
> The compositor MUST also decouple performance of the page from the ability to present new imagery to the user at the appropriate framerate.

In case the compositor is not done through software
