### ISSUE TITLE
WebXR phrasing is not extensible & potentially incorrectly treats “immersive session” as synonymous with “immersive-vr”

### ISSUE THREAD

**Issue by bialpio** [immersive-web/webxr#817]
It seems to me that the phrasing of parts of WebXR spec is not extensible. One example is related to requesting reference spaces, during the [check](https://immersive-web.github.io/webxr/#reference-space-is-supported) if the reference space is supported:
“3. If type is `local` or `local-floor`, and session is an `immersive session`, return `true`.”

“Immersive session” text links to a [section](https://immersive-web.github.io/webxr/#immersive-session):
“In this document, the term inline session is synonymous with an inline session and the term immersive session is synonymous with an immersive-vr session.”

The above text does not allow for extending the main WebXR spec (see for example issue immersive-web/webxr-ar-module#21) w/o causing potentially breaking changes (or at least might make life harder for the early implementers).

**Comment by rcabanier** [comment]
Can we add phrasing in the AR spec that changes the definition of "Immersive session"?

Are there other extension specs so we can see how this is usually done?

**Comment by Manishearth** [comment]
IMO this issue should be moved to the AR module for modifying the immersive session definition. That's kind of why it exists, so there's one "patch" that needs to be applied.

**Comment by Manishearth** [comment]
This was fixed by #869
