### ISSUE TITLE
Should the spec dictate the state of isPresenting flag when requestPresent and exitPresent promises are run?

### ISSUE THREAD

**Issue by wrr** [immersive-web/webxr#82]
There is a difference in the early implementations of WebVR between Firefox  and Chrome:

```
vrDisplay.requestPresent([{source: canvas}]).then(
    function() {
        // Fails in Firefox but not in Chrome.
        console.assert(vrDisplay.isPresenting);
  });

vrDisplay.exitPresent().then(
    function() {
        // Fails in Firefox but not in Chrome.
        console.assert(!vrDisplay.isPresenting);
  });
```

The spec currently doesn't explicitly dictate what should be the state of `isPresenting` flag in these promises, but it would be beneficial if the state was consistent between implementations.

**Comment by cvan** [comment]
Ping, @kearwood. Sounds like a Firefox bug that needs to be filed. Can you confirm?

**Comment by toji** [comment]
Regardless of whether one browser or another has a bug, though, we should
make the order of operations explicit in the spec.

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#4
