### ISSUE TITLE
Demo issue for building TPAC Agenda

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/webxr#822]
This is a test issue the "/facetoface" command is used to add the label for requesting agenda items. It works on all "immersive-web/*" repos.

Before we begin:

* Code of Conduct
* Introductions, everyone says who they are 
* Pick a Scribe

/facetoface requesting to add an agenda item so that everyone gets to know each other before we start during TPAC.

**Comment by AdaRoseCannon** [comment]
/facetoface to show that you can also use the command in comments as well.

**Comment by NellWaliczek** [comment]
Thanks!
