### ISSUE TITLE
[Feature Policy] should not control exposure of navigator.xr

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#823]
https://immersive-web.github.io/webxr/#feature-policy currently says that the "policy-controlled feature... controls whether the `xr` attribute is exposed on the `Navigator` object."

According to @clelland, controlling exposure of an IDL member is not a common pattern ([context](https://chromium-review.googlesource.com/c/chromium/src/+/1783670/1/third_party/blink/renderer/modules/xr/xr.cc#493)). For consistency with other APIs, the feature check should probably be moved to the top-level methods on the `navigator.xr` object.

<br>FWIW, the decision to use `"xr"` was somewhat motivated (i.e., https://github.com/immersive-web/webxr/issues/308#issuecomment-504610297 and related conversations) by the simplicity of not exposing the `xr` attribute. Changing _how_ the control works would enable make other options possible, though that's not required or blocking this change.

**Comment by toji** [comment]
Thanks for bringing attention to this issue! I'd like to take some time at TPAC to discuss the group's approach to feature policy now and in the future, but prior to that I've put together a doc that outlines what the editors have discussed. It would be great if anyone with an interest in the topic can read through and either leave comments or be prepared to discuss at TPAC:

https://docs.google.com/document/d/1RZTL69JsTxoJUyXNnu_2v0PPILqrDpYW3ZxDjMAqQ-M/edit?usp=sharing

**Comment by AdaRoseCannon** [comment]
Removing from the Agenda since it was addresses Face-to-face at TPAC, feel free to re-agenda.
