### ISSUE TITLE
Does VRDisplayEvent's reason need to be nullable?

### ISSUE THREAD

**Issue by foolip** [immersive-web/webxr#83]
https://w3c.github.io/webvr/#interface-vrdisplayevent

This seems a bit odd, can it ever be null in an event created by the UA? If not, it's probably best to just make it non-nullable, and also to make it required in VRDisplayEventInit, or to give it a default in VRDisplayEventInit.

**Comment by toji** [comment]
I think it would be fine to give it a default. We could probably just have it be an empty string when nothing else is necessary or applicable.

**Comment by foolip** [comment]
The default would have to be one of VRDisplayEventReason's values though. I'd go the required route, which overall seems simpler.

**Comment by toji** [comment]
"" can be a valid enum though, right? We do that in the Gamepad API already.

**Comment by foolip** [comment]
Yes, if you add it to VRDisplayEventReason it'd be a valid value. But if only script-created events would ever end up with that reason, I think I'd lean towards just requiring one of the reasons that UAs actually use. Doesn't matter much, though.

**Comment by kearwood** [comment]
Is there a use case for creating a VRDisplayEvent in a script without a reason in the enum?

If not, I'd like to give my +1 to making reason non-nullable and required.

**Comment by smaug----** [comment]
The current spec 1.1 VRDisplayEvent doesn't make sense.
The dictionary has non-nullable, non-required 'reason', yet the event has nullable reason.
What should the value be when one calls
(new VRDisplayEvent("foo")).reason ?
Nothing initializes reason to null in that case.

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#5
