### ISSUE TITLE
Support for premultipliedAlpha in XRWebGLLayerInit?

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#838]
See also: #837

Split off from https://github.com/immersive-web/webxr-ar-module/issues/14#issuecomment-529595422

Do we want [XRWebGLLayerInit](https://immersive-web.github.io/webxr/#dictdef-xrwebgllayerinit) to support a `premultipliedAlpha` parameter? Currently this is basically implicitly set to `true`, but it may be useful to expose the ability to disable it.

I _think_ the main reason to expose it is just for symmetry and clarity -- people don't seem to forsee actual use cases for this, and implementations may internally need to do a premultiplication blit pass anyway.

This automatically solves the problem in #837.

We should also bear in mind that this may matter more as we start supporting multiple layers (cc @Artyom17)

cc @klausw @rcabanier @thetuvix

**Comment by Manishearth** [comment]
If the decision here is to not expose this ability, we should clarify that WebXR expects all color buffers in its layers to have premultiplied alpha

**Comment by toji** [comment]
Closed by #840
