### ISSUE TITLE
Result of calling checkFramebufferStatus on an opaque framebuffer

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#854]
https://immersive-web.github.io/webxr/#opaque-framebuffer doesb't say what the result of calling `checkFramebufferStatus` on an opaque framebuffer should be.

**Comment by asajeffrey** [comment]
Should it be `FRAMEBUFFER_COMPLETE` during an rAF and `FRAMEBUFFER_UNSUPPORTED` otherwise?

**Comment by toji** [comment]
We do have text that says:

> When not in a `requestAnimationFrame()` callback calls to `checkFramebufferStatus` outside of a `requestAnimationFrame()` callback MUST generate a `FRAMEBUFFER_UNSUPPORTED` error

But that doesn't explicitly cover what the status should be inside a rAF, and we should add that. It should indeed be `FRAMEBUFFER_COMPLETE`, but I'm not sure if we can say that it MUST be that. Need to give some thought to if there's situations where it would be necessary or appropriate for the framebuffer to report something other than complete inside a rAF.

**Comment by asajeffrey** [comment]
Yes, that's what I was wondering, is there ever a time when the session is in an rAF and it returns anything other than `FRAMEBUFFER_COMPLETE`?

**Comment by toji** [comment]
Thinking out loud: Most common scenario I can think of is context loss but that behavior is already described in the WebGL spec (returns `FRAMEBUFFER_UNSUPPORTED`) and we shouldn't override it. Could possibly run into an `OUT_OF_MEMORY` situation as well, but in that case your whole context is pretty effectively screwed and reporting complete vs. unsupported is the least of your problems. 

Beyond that most of the things that would potentially cause an incomplete framebuffer are state management issues, and we should be able to trust that the browser is capable of handling that properly. So yeah, I'm gonna say that we should always consider it complete in the rAF callback (barring the existing behavior for lost contexts).

**Comment by rcabanier** [comment]
Do we know what happens today?

**Comment by Manishearth** [comment]
Closing, this is already technically specified and specifying it gets too redundant: https://github.com/immersive-web/webxr/pull/1035
