### ISSUE TITLE
Can opaque framebuffers be deleted?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#855]
https://immersive-web.github.io/webxr/#opaque-framebuffer doesn't specify what should happen if `deleteFramebuffer` is called on an opaque framebuffer.

**Comment by asajeffrey** [comment]
Should it be an `INVALID_OPERATION` error?

**Comment by toji** [comment]
Yes, that would be the ideal behavior. Thanks for pointing out that this behavior isn't yet specified.
