### ISSUE TITLE
Do opaque framebuffers have a reference to their XR session?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#856]
https://immersive-web.github.io/webxr/#opaque-framebuffer says "An opaque framebuffer is considered incomplete outside of a `requestAnimationFrame()` callback." Does this mean an rAF on the XR session that the framebuffer is associated with? If so, should an opaque framebuffer store a reference to that `XRSession`?

**Comment by toji** [comment]
Good point! It definitely should only be marked as complete for rAFs from the session that it's associated with, and as a result likely does need to be associated with that session somehow.

**Comment by asajeffrey** [comment]
This makes a difference for GC, since it means the framebuffer keeps the session object live.

**Comment by asajeffrey** [comment]
Also, an XR session currently doesn't track a flag for whether or not it is in an rAF. Should it have one? Or keep track of the current `Frame`?
