### ISSUE TITLE
Add explainer discussion of why webxr shares its WebGL context with a canvas

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#861]
Working through the implementation of opaque framebuffers in Servo, which is make more complex by webxr sharing WebGL contexts with canvas. Any canvas element with an XR-compatible WebGL context now has two potential targets: the canvas and the webxr device, and since we're using double-buffering and the cadence for webGL rAF and webxr rAF are independent, this means four buffers to juggle.

Looking at the explainer, I don't see any discussion of this design choice, can we add one?

**Comment by toji** [comment]
Sure, that's a good piece of context to get down in text!

FWIW the short version is: We don't want to create yet another way to get a GL contex when canvas and OffscreenCanvas cover developers needs pretty well already. Also, a significant number of experiences are expected to want to show an inline preview of content prior to going immersive, and if we weren't able to re-use the canvas context we'd force devs to reload that content upon starting the immersive session.

**Comment by asajeffrey** [comment]
OK, but it's worth discussing the tradeoffs. In particular, this introduces GL contexts which are being rendered in two different places (canvas and XR) which complicates implementations. On platforms where surface attributes such as depth and stencil are shared between all surfaces in the same context, this means that either a) all canvases have to support depth and stencil, just on the off chance that they get used for XR, or b) creating an XR compatible GL context causes the context to be destroyed and recreated, which removes the benefit of sharing the context between canvas and XR.
