### ISSUE TITLE
Should getRenderbufferParameter on an opaque framebuffer result in an error?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#862]
https://immersive-web.github.io/webxr/#opaque-framebuffer says "Calling ... `getRenderbufferParameter` with an opaque framebuffer MUST generate an `INVALID_OPERATION` error." It is not obvious that this is necessary, as there is no way to access the renderbuffer of an opaque framebuffer in order to bind it.

**Comment by Manishearth** [comment]
cc @klausw do you have any idea what Chromium does for this (and [the other framebuffer questions Alan asked](https://github.com/immersive-web/webxr/issues/created_by/asajeffrey)?).

**Comment by toji** [comment]
I think @asajeffrey is correct. We can't get a renderbuffer name out so there's no reason to add further limits to our renderbuffer operations. (And as a general principle less XR-specific WEbGL behavior is always Good Thing)
