### ISSUE TITLE
Possible typo in section about limiting poses

### ISSUE THREAD

**Issue by jacobcdewitt** [immersive-web/webxr#864]
The wording for step 2 of the section about [determining if poses must be limited](https://immersive-web.github.io/webxr/#poses-must-be-limited) is unclear. Specifically, the part "the distance between the space’s native origin's" might have a typo. Should it be "the distance between the spaces' native origins"?

**Comment by Manishearth** [comment]
yep!

**Comment by jacobcdewitt** [comment]
In that case, does step 2 essentially mean "limit the pose if the native origins are too far apart for local or local-floor spaces"?

**Comment by Manishearth** [comment]
Correct.
