### ISSUE TITLE
Definition of "active and focused" is confused about the concept of "active document"

### ISSUE THREAD

**Issue by bzbarsky** [immersive-web/webxr#872]
https://immersive-web.github.io/webxr/#active-and-focused-document says:

> If document is not of the same origin-domain as the active document

but what is "the active document"?  The link there is to the "active document" property of a browsing context, but determining that involves knowing which browsing context is involved, and the "active and focused" text does not specify that.  Note that many documents are active at the same time when there are multiple browsing contexts involved (e.g. on a page with subframes, or when multiple tabs are involved, etc).

**Comment by bzbarsky** [comment]
@a2sheppy

**Comment by Manishearth** [comment]
This was removed https://github.com/immersive-web/webxr/pull/1030
