### ISSUE TITLE
Typo/grammar error in section 4.3

### ISSUE THREAD

**Issue by a2sheppy** [immersive-web/webxr#878]
In section 4.3 (Animation Frames) we find the following sentence (it's the fourth block, including the callback signature block):

> Each XRSession has a list of animation frame callbacks, which is initially empty, and an animation frame callback identifier, which is a _number initially be zero_.

Note the italicized phrase at the end; this should probably be changed to something like "number which is initially zero."

**Comment by toji** [comment]
Thanks for catching that. Fixed.
