### ISSUE TITLE
Corrections and clarifications for description/steps for updateRenderState()

### ISSUE THREAD

**Issue by a2sheppy** [immersive-web/webxr#880]
A couple of things about the information provided for [`updateRenderState()`](https://immersive-web.github.io/webxr/#dom-xrsession-updaterenderstate):

First, item 3 has a minor typo: "If newState's baseLayer's was created..." The "'s" should be removed from "baseLayer's", leaving the text as "If newState's baseLayer was created..."

More importantly, it would be useful to explicitly state what this method does if you do not provide the optional parameter. I know it's optional because WebIDL requires that dictionary parameters with all optional members must also be optional, but given that, the spec should be clear on what the method does when this is the case. Does the method have no effect, or does it still cause some secondary effect to occur? Presumably it's essentially a no-op but it would be wise to be specific either way.

**Comment by Manishearth** [comment]
The method will have no effect.
