### ISSUE TITLE
Clarify semantics of preserveDrawingBuffer

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#891]
https://immersive-web.github.io/webxr/#opaque-framebuffer says

> The buffers attached to an opaque framebuffer MUST be cleared to the values in the table below when first created, or prior to the processing of each XR animation frame. This is identical to the behavior of the WebGL context’s default framebuffer.

Implicitly, this means ignoring `preserveDrawingBuffer`, but perhaps this should be made explicit? Especially because this is not identical to WebGL!

**Comment by rcabanier** [comment]
We already defined that `preserveDrawingBuffer` is not supported in WebXR

**Comment by rcabanier** [comment]
See @toji 's PR: https://github.com/immersive-web/webxr/pull/866

**Comment by asajeffrey** [comment]
Er, doing a search for `preserveDrawingBuffer` in that PR doesn't find anything.

**Comment by rcabanier** [comment]
I thought we discussed it as part of https://github.com/immersive-web/webxr/issues/775 which that PR solved.
I agree that if the spec doesn't call this out, it should (just like how we call out `premultipliedAlpha`

**Comment by Manishearth** [comment]
I think the more general discussion around that was that the normal webgl context options are to be ignored, the only way to set them is through XRWebGLLayer, and if an option (like premultipliedAlpha) is not in XRWebGLLayerInit then there is no way to set it for XR. We could call this out more explicitly.

**Comment by asajeffrey** [comment]
Since WebXR inherits its WebGLContext from canvas, there will be a value for `preserveDrawingBuffer`, we should just be explicit that webXR ignores it. This does mean there may be odd effects on pages that use it, where the web page's canvas will display different content than webXR, even if uses the same WebGL code.

**Comment by klausw** [comment]
I think a core part of the confusion is that the canvas WebGL options are a mix of general context properties together with configuration for the default framebuffer used for canvas drawing. Even apart from WebXR, an offscreen framebuffer would have independent properties such as depth/alpha that don't inherit from the canvas creation attributes, and using premultiplied alpha would be an application choice for purely-internal buffers, it only needs to be specified as metadata for external interfaces. There was more discussion [in issue 14](https://github.com/immersive-web/webxr-ar-module/issues/14#issuecomment-528657456) about this.

Would it be feasible to update the canvas / WebGL spec to differentiate between general properties and configuration of the canvas-backing default framebuffer? This wouldn't require any API changes, the goal would just be a documentation update to avoid people expecting them to apply to non-default render buffers.

**Comment by Manishearth** [comment]
We should just be explicit that we ignore preserveDrawingBuffer here (and perhaps others?)

**Comment by rcabanier** [comment]
I agree. The spec should say that if a canvas is provided, all unsupported properties should revert to their default state. We called this out for `premultipliedAlpha` but not for anything else.
