### ISSUE TITLE
All promise rejections should say what they're rejected with

### ISSUE THREAD

**Issue by foolip** [immersive-web/webxr#90]
https://w3c.github.io/webvr/#dom-vrdisplay-requestpresent
https://w3c.github.io/webvr/#dom-vrdisplay-exitpresent
https://w3c.github.io/webvr/#navigator-getvrdisplays-attribute

Some spec editors (@annevk) like TypeError for everything, but for user gesture there's [precedent in HTML](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-media-play) to use `NotAllowedError`.

**Comment by annevk** [comment]
But at the minimum, we should always reject with an `Error` class/subclass.

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#24
