### ISSUE TITLE
makeXRCompatible mutates object state directly in a parallel section

### ISSUE THREAD

**Issue by bzbarsky** [immersive-web/webxr#908]
https://www.w3.org/TR/webxr/#dom-webglrenderingcontextbase-makexrcompatible step 1.6.1 is:

> Set context’s XR compatible boolean to false.

but that state is synchronously observable (e.g. via whether the `XRWebGLLayer` constructor throws).  As a result, if the web page does:

    ctx.makeXRCompatible();
    var layer = new XRWebGLLayer(session, ctx);

this will sometimes throw and sometimes not, depending on the scheduling of the parallel section vs the main thread of execution.  Or maybe it will read a partially-updated value, depending on the exact hardware architecture and memory model...

In any case, parallel sections should not be synchronously touching (reading _or_ writing) state.  They should queue tasks (and say which document and task queue those are associated with!) to do that.

**Comment by foolip** [comment]
https://github.com/immersive-web/webxr/issues/911 is also about "in parallel" and https://github.com/immersive-web/webxr/issues/912 about task sources, but I'll pick this issue to comment on / follow.

@bzbarsky has already said it all, but I'll elaborate a bit more with how I think of these things mapping to implementation.
- Any "in parallel" section is one that could be running on another thread or another process, so its steps could be interleaved with the steps after (outside) the "in parallel" invocation and any other "in parallel" sections. (They're not *always* implemented off-main-thread though, they could exist mainly to settle a promise at some point after the sync steps have returned.)
- To get back to the main thread, "queue a task" as @bzbarsky says. This includes firing events, and the spec already does this. In implementation, there often isn't an explicit "queue a task" if the parallel steps are truly parallel, then instead the message posted about task completion will serve that purpose.
- [Task sources](https://html.spec.whatwg.org/multipage/webappapis.html#generic-task-sources) are tricky. When the implementation has fewer task sources than the spec, it can end up providing more ordering guarantees than the spec does. It can be hard to not accidentally depend on this in tests, and sometimes hard to write tests without the ordering guarantees. WebXR should probably use either the user interaction task source, or create a new one.

**Comment by toji** [comment]
Thanks, @bzbarsky, for bringing this to our attention, and thank you @foolip for clarifying the expected behavior. Based on that, it seems like the appropriate way to ensure that the order of the steps is dependable is to do something like the following: (Additions in bold)

> 6. If the immersive XR device is null **queue a task to perform the following steps**:
>    1. Set context’s XR compatible boolean to false.
>    1. Reject promise with an InvalidStateError and abort these steps.
> 7. **Otherwise** if context was created on a compatible graphics adapter for the immersive XR device **queue a task to perform the following steps**:
>    1. Set context’s XR compatible boolean to true.
>    1. Resolve promise and abort these steps.
> 8. **Otherwise** queue a task to perform the following steps:
>    1. Force context to be lost and handle the context loss as described by the WebGL specification.
>    1. If the canceled flag of the "webglcontextlost" event fired in the previous step was not set, reject promise with an AbortError and abort these steps.
>    1. Restore the context on a compatible graphics adapter for the immersive XR device.
>    1. Set context’s XR compatible boolean to true.
>    1. Resolve promise.

Would this be sufficient to resolve the parallelization issue for the boolean flag? (I recognize that there are other outstanding issues that affect the text above. I'm only attempting to address the synchronization here.)

**Comment by bzbarsky** [comment]
That would be sufficient for this specific boolean if it said which task source and document is used for queuing the tasks, this would resolve this specific issue, yes.

(It's still not clear to me whether this would do the right thing if the context is lost between when the task from step 7 is queued and when that task runs, but that might be part of the "other issues" bit.)
