### ISSUE TITLE
The timing of requestPresent and exitPresent probably needs to be defined

### ISSUE THREAD

**Issue by foolip** [immersive-web/webxr#91]
https://w3c.github.io/webvr/#dom-vrdisplay-requestpresent
https://w3c.github.io/webvr/#dom-vrdisplay-exitpresent

When the promises are resolved relative to everything else that happens is observable, and probably needs to be defined. With [`requestFullscreen()`](https://fullscreen.spec.whatwg.org/#dom-element-requestfullscreen) this is pretty complicated and still not properly implemented everywhere, hopefully you can get it right from the start with something simpler and shared web-platform-tests.

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#6
