### ISSUE TITLE
makeXRCompatible seems to have an unnecessary parallel section

### ISSUE THREAD

**Issue by bzbarsky** [immersive-web/webxr#911]
https://immersive-web.github.io/webxr/#dom-webglrenderingcontextbase-makexrcompatible has a parallel section that does the following:

* Check the context lost flag; this needs to happen outside a parallel section anyway.
* Check the XR compatible flag.  This needs to happen outside a parallel section anyway, so there is no race with mutators of the flag.
* "Ensure an immersive XR device is selected", which can be done without going parallel as in the changes for the `getContext` method.  Though this part doesn't even make sense; see https://github.com/immersive-web/webxr/issues/909
* _Sets_ the XR compatible flag.  This needs to happen outside a parallel section.
* Queues a task.  That clearly doesn't need to be in a parallel section, though it could be...

**Comment by toji** [comment]
This is a compelling argument, and would certainly simplify the algorithm a bit. I wouldn't mind an answer to my question in #908 for the sake of better understanding the required flow of parallel sections, but it seems that removing the parallel section here could negate much of the necessity for that change.
