### ISSUE TITLE
cancelAnimationFrame: clarify behavior when called from a frame callback

### ISSUE THREAD

**Issue by lojjic** [immersive-web/webxr#923]
As discussed in https://github.com/immersive-web/webxr-polyfill/pull/116#discussion_r346593146 calling `xrSession.cancelAnimationFrame` from within a frame callback should be able to cancel another subsequent callback within that same frame's callbacks list. A strict reading of the current algorithm as written does not allow for this; it says to search through the "list of animation frame callbacks" for the handle to cancel, but that "list of animation frame callbacks" is explicitly set to an empty list prior to callback execution.

**Comment by Manishearth** [comment]
Yes, we should be structuring it so that cAF within a callback should cancel subsequent callbacks. This might require some queueing.
