### ISSUE TITLE
is boundsGeometry static or live-updated data?

### ISSUE THREAD

**Issue by klausw** [immersive-web/webxr#932]
Unless I'm missing something, https://immersive-web.github.io/webxr/#xrboundedreferencespace-interface doesn't make it very clear if the `boundsGeometry` attribute of a bounded reference space will remain the same for the lifetime of a session, or if this may change during the session, i.e. due to the underlying system reporting updated values.

This also affects the `getOffsetReferenceSpace` algorithm at https://immersive-web.github.io/webxr/#dom-xrreferencespace-getoffsetreferencespace . That currently copies and multiplies the parent space's `boundsGeometry`. If the underlying values change during the session, those changes wouldn't be reflected in the offset space when following that algorithm.

If these values are intended to be static for the lifetime of the session, should that be made explicit? 

See also https://github.com/immersive-web/webxr/issues/674#issuecomment-512605931 - if the bounds are static, implementations would need to delay resolving a `requestReferenceSpace('bounded-floor')` promise until actual bounds are available. If that's the case, I think that should also be called out explicitly in the spec.

**Comment by Manishearth** [comment]
It's live-updated, see https://immersive-web.github.io/webxr/#eventdef-xrreferencespace-reset

If it changes, we're supposed to trigger the reset event.

We could potentially use the concept of [frame update](https://immersive-web.github.io/webxr/#frame-update) to keep this updated per-frame instead of having to listen for it differently.

**Comment by klausw** [comment]
If bounds are live updated, is an offset space derived from it expected to get the updates also, including forwarding reset events for bounds and tracking discontinuities? If yes, I think the spec should say so, including something along the lines that the bounds calculation algorithm needs to be re-run on changes. If only the underlying space gets reset events, I think that would make offset spaces a lot less useful.

**Comment by Manishearth** [comment]
I think so, because offset spaces are internally just the normal space with the offset slot set.

**Comment by klausw** [comment]
Thank you for clarifying, I filed new issue https://github.com/immersive-web/webxr/issues/933 to avoid confusion.
