### ISSUE TITLE
Clarify that offset spaces inherit reset events and bounds changes

### ISSUE THREAD

**Issue by klausw** [immersive-web/webxr#933]
According to https://github.com/immersive-web/webxr/issues/932, offset spaces should get the same reference space reset events as the underlying space, and changes to `boundsGeometry` should also be reflected in the offset space's data. I think the spec should make this explicit to avoid inconsistent implementations.

The current `getOffsetReferenceSpace` algorithm at https://immersive-web.github.io/webxr/#dom-xrreferencespace-getoffsetreferencespace looks like a one-time calculation at the time the offset space was created, and should clarify that this needs to be re-run each time the underlying bounds change.

Also, should the getOffsetReferenceSpace description and/or the XRReferenceSpaceEvent description at https://immersive-web.github.io/webxr/#xrreferencespaceevent-interface explicitly point out that the same events must be sent for any offset space derived from an underlying space?

**Comment by Manishearth** [comment]
> The current getOffsetReferenceSpace algorithm at https://immersive-web.github.io/webxr/#dom-xrreferencespace-getoffsetreferencespace looks like a one-time calculation at the time the offset space was created, and should clarify that this needs to be re-run each time the underlying bounds change.

This is incorrect, the current algorithm only deals with adding together offsets, which don't change when the bounds do. The effective origin is computed from the offset and original bounds space, per-frame.

------

To some extend the event stuff is related to https://github.com/immersive-web/webxr/issues/845 , which we fixed with a note since the proper spec way of specifying reset events would be very tedious.

**Comment by klausw** [comment]
I'm confused - the current text says:

```
The <dfn method for="XRReferenceSpace">getOffsetReferenceSpace(|originOffset|)</dfn> method MUST perform the following steps when invoked:

  1. Let |base| be the {{XRReferenceSpace}} the method was called on.
  1. Initialize |offsetSpace| as follows:
    <dl class="switch">
      <dt> If |base| is an instance of {{XRBoundedReferenceSpace}}
      <dd> Let |offsetSpace| be a new {{XRBoundedReferenceSpace}} and set |offsetSpace|'s {{boundsGeometry}} to |base|'s {{boundsGeometry}}, with each point multiplied by the {{XRRigidTransform/inverse}} of |originOffset|.
```

To me, that sounds as if the offset space's `boundsGeometry` is calculated one time, when `getOffsetReferenceSpace` is called, and transforms the original points based on the current value of originOffset at that time.

**Comment by Manishearth** [comment]
Oh! I forgot about that part. Yeah, you're right, sorry.
