### ISSUE TITLE
`navigator.xr` undedined on WebXR enabled Android Chrome 79

### ISSUE THREAD

**Issue by vedtam** [immersive-web/webxr#935]
Hi,

On Android, Chrome 79 Beta (WebXR Device API is enabled in flags) for `navigator.xr` I get undefined. No other session is active.

With the polyfill inlined, its defined but `.isSessionSupported()` / `.supportsSession()` - throws `is not a function`.

```
<head>
  <title>WebXR Test</title>
  <script src='https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.js'></script>
</head>
<body>
  <script>    
    let polyfill = new WebXRPolyfill();
    console.log(navigator.xr); //with polyfill enabled `xr` is ok but .isSessionSupported() / .supportsSession() - throws `not a function`
    
    let isSupportedPromise = navigator.xr.isSessionSupported('immersive-vr');
  </script>

  ...
```

Would really appreciate your help.
Thanks!

**Comment by Artyom17** [comment]
Make sure you use HTTPS, not HTTP. WebXR is enabled only for secured origins.

**Comment by Artyom17** [comment]
Also, check this doc out: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/xr-spatial-tracking

**Comment by vedtam** [comment]
@Artyom17 thank you so much, totally overlooked this while remote debugging the app. Thanks!!!

**Comment by NellWaliczek** [comment]
Also, please note this is repository is for specification definition not for individual browser implementations.
