### ISSUE TITLE
local-floor reference space foor SteamVR 1.8.20

### ISSUE THREAD

**Issue by ManuelGraf** [immersive-web/webxr#955]
Hi,

I tried to issue an XRSession with local-floor reference space for HTC Vive running on steamvr 1.8.20 Win10 with nvidia Geforce 1080 on Chrome  79.0.3945.130.
I get the following error:

core.js:6406 ERROR Error: Uncaught (in promise): NotSupportedError: Failed to execute 'requestReferenceSpace' on 'XRSession': This device does not support the requested reference space type.

Same for 'bounded-floor' and 'unbounded'

The only ones that seem to work are 'viewer' and 'local'.

Am I doing something wrong or is steamVR just not quite there?

**Comment by Artyom17** [comment]
It should be filed to crbug.com, I think. Both - Floor and Bounded Floor - should be supported. Unbounded - no, it is mostly for AR.

**Comment by avaer** [comment]
For future reference, is it acceptable for this repository be used as a Chrome implementation support forum?

**Comment by Artyom17** [comment]
I'd say - no. Chrome is only one of the WebXR-enabled browsers. This forum is about the spec, not the specific browsers.

**Comment by klausw** [comment]
This issue tracker is intended for general specification questions, and I agree that browser-specific questions should be handled in a separate issue tracker or forum specific to that implementation.

In this case, have you asked for `local-floor` as a required or optional feature in the `requestSession` call? It's not one of the enabled-by-default reference space types, so `requestReferenceSpace` will be rejected unless you did that. Does https://immersive-web.github.io/webxr-samples/room-scale.html work for you?

(In general, when asking for help, it's best to have a runnable complete example. Just error messages by themselves often lack important context.)
