### ISSUE TITLE
Timing of initial inputsourceschange event

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#961]
https://immersive-web.github.io/webxr/#list-of-active-xr-input-sources

> Each XRSession has a list of active XR input sources (a list of XRInputSource) which MUST be initially an empty list.

This means that if the device already has input sources connected from the start, it needs to immediately fire an `inputsourceschange` event after the session is created. [Threejs relies on this happening](https://github.com/mrdoob/three.js/issues/18638).

However, there's a period of time in which the session exists but is not yet available to user code (when the promise hasn't been resolved yet, or the promise has resolved and the resolution microtasks haven't triggered yet). In such a scenario, firing an `inputsourceschange` event is not useful since nothing can catch it. The current design of the spec seems to have a bit of a pit of failure where codebases can reasonably assume that all input sources will arrive through an `inputsourceschange` event, but it is technically legal for implementors to fire these events before JS code is practically able to catch it.

I feel like we should _either_: 

 - Change the spec wording to allow the input sources list to be non empty at the beginning, and urge framework authors to not make this assumption
 - Add spec text that _explicitly_ triggers the [add input source](https://immersive-web.github.io/webxr/#xrsession-add-input-source) algorithm for existing input sources right after the "resolve" line in [the `requestSession()` algorithm](https://immersive-web.github.io/webxr/#dom-xrsystem-requestsession)

Servo _currently_ does the former, but that's currently incorrect. Chrome _seems_ to be doing the latter, but it's not explicit, so it might be possible that there's actually a race there.

cc @alcooper91

**Comment by Manishearth** [comment]
> Add spec text that explicitly triggers the add input source algorithm for existing input sources right after the "resolve" line in the requestSession() algorithm

This might actually not be correct either, the correct thing may be to _spawn a task_ doing this at this point.

Honestly this feels like it hinges too much on the precise scheduling of tasks, no matter what.

It also means that you can only rely on this if you're running `requestSession(...).resolve(....)`, if you're resolving later it may not work out and you will have to check the initial array anyway. It might be better to pick and document the former approach, as opposed to choosing the latter approach where applications _still_ should check the initial array but now it's much less obvious why.

**Comment by Manishearth** [comment]
It's been pointed out to me that we can even have the resolve happen _after_ the "queue a task to fire events" because of how microtasks work (the microtask for `resolve()` callbacks will be fulfilled before any new task). This is nice in that it's typical to not do anything in a task after resolving a promise. However, this gives me _even more_ spec heebie jeebies.

**Comment by Manishearth** [comment]
cc @cabanier oculus browser may also have this race, worth looking into

**Comment by cabanier** [comment]
> cc @cabanier oculus browser may also have this race, worth looking into

Thanks! I will take a look

**Comment by cabanier** [comment]
@Manishearth Is the issue that the `inputsourceschange` event can be missed because the author didn't get the session yet?

**Comment by Manishearth** [comment]
Yes, because there's a gap between when the session sets up its resources and when `resolve(..)` has its callbacks run

**Comment by cabanier** [comment]
If the event was missed, the list of controllers should not be empty. 
Maybe authors should check for controllers when the session resolves (in addition to when the event is generated) and not rely on it being empty.

**Comment by Manishearth** [comment]
Right, threejs is currently incorrect by making this assumption. Our options are:

 - document this possible issue very strongly and hope nobody else makes the same mistake as Three
 - change the spec so this isn't an issue anymore
 - do both: harden up implementations, but document the behavior as still possible, so the related issues of attaching listeners even later than resolve isn't a problem


I _slightly_ prefer the second option because the failure mode of (1) is a very subtle race and I'm not certain that authors will notice it.

But I'm down for any of these options, I just want us to do _something_

**Comment by cabanier** [comment]
I don't quite follow. Can you elaborate what would be the spec change? 
Also, why would we make a change if it doesn't always solve it? It seems just leaving the normative part and just adding a note would be better...

**Comment by Manishearth** [comment]
The spec change would be to:

 - Tweak https://immersive-web.github.io/webxr/#dom-xrsystem-requestsession  so that _after_ the "resolve promise" step, we have an "if there are any existing input sources on session, queue a task to fire an XRInputSourceChange event with these sources" step
 - Tweak https://immersive-web.github.io/webxr/#xrsession-add-input-source to clarify that we only start monitoring for input sources after the "resolve promise" step in the requestSession query has executed.

The reason I'd like to make the change is that given that Chrome never starts off with input sources attached based on their architecture (but may have a rare race condition around it), authors may assume this to always be the case, and I'd like to avoid the pit of failure by asking user agents to implement this robustly.

**Comment by Manishearth** [comment]
@cabanier any thoughts? should we go with allowing the array to start empty, or tweaking the spec as listed above to be more robust? I can try and write a PR for it.

**Comment by cabanier** [comment]
I think we should tweak the spec.

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr/pull/1002
