### ISSUE TITLE
XRSession creation failed: The specified session configuration is not supported. Chrome 80.0.3987.116

### ISSUE THREAD

**Issue by devsatish** [immersive-web/webxr#964]
I have Oculus Rift connected and it works great with Firefox. But can't get any of the samples to work on current stable Chrome release that I have - version 80.0.3987.116

The error I get is :  XRSession creation failed: The specified session configuration is not supported
for any of the samples.

I did configure NVIDIA settings to let Chrome use GPU. Used to work with WebVR in chrome in the past ,. and it worked fine. But can't get WebXR demo's to work.

Edit:
I do have all the VR/XR/Oculus flags toggled to enabled in Chrome, but still no luck

**Comment by klausw** [comment]
Please see https://immersiveweb.dev/chrome-support.html

**Comment by chen8888** [comment]
> Please see https://immersiveweb.dev/chrome-support.html

My chrome version is this (com.android.chrome_79.0.3945.79-394507905_minAPI19_maxAPI23 (armeabi-v7a) (nodpi) _apkmirror.com.apk), my Android system is 9.0, the mobile platform is OnePlus7 (supports ARCore), I have opened all XR items in chrome://flags, and the homepage of this link (https://immersive-web.github.io/webxr-samples/) also shows that my browser supports WebXR, everything It's all so beautiful. But when I click immersive ar session to enter the page and click start AR, the console prompts an error: "XRSession creation failed: The specified session configuration is not supported."!
why? Please give guidance, thank you.
