### ISSUE TITLE
XRPermissionStatus is a dictionary but inherits from an interface

### ISSUE THREAD

**Issue by stephenmcgruer** [immersive-web/webxr#965]
https://github.com/immersive-web/webxr/pull/900 added two dictionaries, `XRPermissionDescriptor` and `XRPermissionStatus`, which inherit from `PermissionDescriptor` and `PermissionStatus` respectively.

Unfortunately, `PermissionStatus` is an interface not a dictionary ([spec](https://w3c.github.io/permissions/#permissionstatus))! This caused the IDL import into WPT ([PR](https://github.com/web-platform-tests/wpt/pull/21949)) to start failing with `object "XRPermissionStatus inherits PermissionStatus, but XRPermissionStatus is not an interface."`

I'm not an IDL expert, but I assume a dictionary isn't meant to be able to inherit from an interface, and `XRPermissionStatus` should be an interface :)

**Comment by Manishearth** [comment]
Yikes, that is indeed an oversight.

**Comment by stephenmcgruer** [comment]
> Yikes, that is indeed an oversight.

It's why we have tests - I'm glad they caught it! :). Thanks for looking at it so quickly!
