### ISSUE TITLE
WebXR should describe what happens if no draw calls happen during RequestAnimationFrame

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#969]
As mentioned in https://github.com/immersive-web/layers/issues/20, the spec needs to be updated to describe reprojection behavior in case the author didn't draw into the WebGL framebuffer.

Currently the specification is silent which might cause UAs to implement different behavior.

**Comment by raviramachandra** [comment]
Update: On Magicleap One, if we don't explicitly draw anything in RAF we render black. @toji @cabanier

**Comment by cabanier** [comment]
> Update: On Magicleap One, if we don't explicitly draw anything in RAF we render black.

Is this something that you can fix on the ML side? 
Also is there a minimum refresh rate on your platform?

**Comment by Manishearth** [comment]
We discussed this a bunch in https://github.com/immersive-web/webxr/issues/877 as well

**Comment by Manishearth** [comment]
/agenda get quick platform feedback on what their expected behavior is

**Comment by cabanier** [comment]
FYI the customer experience was skipping frames between scenes while displaying a loading screen.

**Comment by cabanier** [comment]
The spec was updated to cover this case. Closing.
