### ISSUE TITLE
[Question] Is this what firefox/samsung internet is using? Missing device in list

### ISSUE THREAD

**Issue by Serpens66** [immersive-web/webxr#972]
I first thought android firefox app is using "WebVR", but here is says "WEBXR" replaced it https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API/Using_the_WebVR_API .

So when I try to watch a VR video in firefox or samsung internet browser on my phone, it asks me to tell them the phone name and the cardboard device.
1) Why isnt it possible to get the phone name automatically?
2) Why can't I scan the QR code from cardboard device, like it is done in google cardboard app?
3) Neither the phone I have, nor the cardboard I use is listed in the available list.

If this is not the right place to complain about this limited functionality, please tell me where I should write instead.

**Comment by toji** [comment]
This is not a good forum for browser support, and if you're having trouble with Firefox I'd suggest looking at their [Support Pages](https://support.mozilla.org/en-US/products/firefox). Seems like this type of inquiry will get the best results from their community support forums.

That said, it sounds like what you're seeing is actually the WebXR Polyfill being used, which is a Javascript implementation of the API that works with Cardboard. Firefox is still in the process of shipping WebXR, as far as I understand, and so WebXR experiences on that device will fall back to the polyfill for the time being. Once they ship WebXR these pages should automatically start using the native implementation and will no longer have to ask you to identify the device.
