### ISSUE TITLE
Access the touch 2D coordinate

### ISSUE THREAD

**Issue by boehm-e** [immersive-web/webxr#977]
Hi,

Is it possible to get the 2D screen coordinate of a touch event ?
```js
onSelect(event) {
        // I want to know where the user click on the screen (x, y)
};

xrSession.addEventListener('select', this.onSelect);
```

Thank you :)

**Comment by klausw** [comment]
In Chrome's immersive-ar mode (as of 81.0.4042.0), the input source's gamepad.axes provides x/y screen coordinates as -1..1 float values:

```js
> event.inputSource.gamepad.axes
(2) [-0.09861111640930176, 0.3284722566604614]
```

I don't know if there's a clear statement in the spec if devices are required to do this, but I hope this helps.

**Comment by toji** [comment]
At the moment you'd have to use the `projectionMatrix` to unproject the `targetRaySpace` of the `inputSource` indicated by the `select` event in `viewer` space. If that sounds like a massive pain that's easy to get wrong, well... it is. We're discussing alternatives in a couple of places, like https://github.com/immersive-web/layers/issues/21

**Comment by klausw** [comment]
If you're interested in the unprojection approach, I had some code doing this this in https://github.com/klausw/a-frame-car-sample/blob/09249f220015ea05b166d8839e2f57d9168d619a/index.html#L196 , though I've since removed it in favor of using gamepad.axes.

**Comment by boehm-e** [comment]
Thank you for your answers @klausw and @toji , will try it as soon as possible :)

**Comment by Manishearth** [comment]
Going to close this since it's a question but I think I should file an issue for extending `InputSourceEvent`

**Comment by boehm-e** [comment]
@klausw @toji 
my session.inputSources is empty, I am speaking about getting touch screen tap coordinates, not gamepad or any other things.
What am I doing wrong?
Thx :)
