### ISSUE TITLE
Experiences with no translatory tracking

### ISSUE THREAD

**Issue by ManuelGraf** [immersive-web/webxr#979]
Hi,

I am trying to build a WebXR Experience which is basically a panoramic Image viewer

1. One specialty of this app is that the coordinate system is rotated, so that XY plane is the floor, up vector being +z. So basically this is basically a rotation of -90° around x-axis.
2. Also the user is allowed to teleport to different photo spheres with a raycaster controller
so basically thats my XRSpace:

```
get myReferencespace() {

    this.positionOffset.copy(this.mainView.currentImage.location); // use current pano center as position offset

    this.orientationOffset = THREE.Quaternion()
      .setFromAxisAngle(new THREE.Vector3(1, 0, 0), THREE.Math.degToRad(-90));

    const offsetTransform = new (window as any).XRRigidTransform(this.positionOffset, this.orientationOffset);

    return this.hmdSpace.getOffsetReferenceSpace(offsetTransform); // HMDSpace is of type local for oculus quest/htc vive

}

```

At least that was my understanding of relative XR Spaces. But this kinda doesnt work at all. Camera position is way off and also Controllers are either way above me or around 0,0,0 in the scene...

So, in myAnimation Frame, I still have to set camera to a FIXED position manually (camera shouldnt move because this would disturb the view of the photo sphere as you have to be in it's center)

Is there any accounting for this in the WebXR Spec? Like all of the modes besides viewer ALLOW you to move, also changing the pose translate.
But what I need is a FIXED (only orientation, no translation) camera and the controllers gripspaces still being correctly positioned relative to the hmd... how can I achieve this?

**Comment by Manishearth** [comment]
You can always replace your reference space with a new one calculated with the position vector removed, and use `getPose(viewer, newSpace)` instead of `getViewerPose()`, and then apply eye offsets from `getViewerPose(viewer)`
