### ISSUE TITLE
Clarify whats learn-able through an inline session re privacy

### ISSUE THREAD

**Issue by pes10k** [immersive-web/webxr#984]
To my read, the spec seems ambiguous on whether the user needs to give permission to start an inline session (in chromium and similar browsers, it currently doesn't).  The spec is similarly unclear what devices are accessible from the `inputSources ` property of the returned, un-permission-gated `XRSession` object.

From conversation with implementors, it seems like this will be the same for all platforms (and so doesn't have a privacy risk), but that doesn't seem to be required by the spec.

The spec should either require that implementations never return device information through this ungated path, or require permission to start an inline session

**Comment by toji** [comment]
> From conversation with implementors, it seems like this will be the same for all platforms

This is definitely the intent, yes. `inline` is basically just an ease-of-use mechanic for developers that allows them to re-use their rendering and input loop from AR/VR in a 2D context if they want, but it shouldn't expose anything that wasn't already immediately available to the page by other means. For example, the `inputSources` should only report inputs derived from mouse/touch events, and the only thing WebXR is really providing in that case is a bit of math to get the in-world coordinates of the events. You could compute it yourself, but it's a bit of a pain.

There are options for having `inline` sessions expose some basic motion tracking capabilities, similar to device orientation events, but making use of them triggers a permission.

> but that doesn't seem to be required by the spec.

We definitely need to make sure the spec is unambiguous on this point. I'll review the text for opportunities to clarify, and if you have any sections that caused confusion that you can point out I'll happily work on addressing them.

**Comment by Manishearth** [comment]
> but that doesn't seem to be required by the spec.

It is: the spec requires that you go through a permission prompt to get spatial tracking in inline sessions, and without spatial tracking there's no device info that can be revealed.

**Comment by Maksims** [comment]
Currently flow is like so:
1. Page loads
2. App checks support of immersive-vr session
3. If supported provides UI to user to enter VR
4. User interacts with UI
5. Permission popup

If there will be permission popup on support checks, does that mean we will have to ask for it during user interaction, or it will just be at any point. We do have slightly annoying scenarios like with page notifications permissions - they are intrusive, as user might have not expected them to happen yet. And if support check will be available only on user intent, then we will have issue as it is async operation, so either developer will have to request immersive-vr session without knowledge of its support, or ask user to have two interactions: one for check, one for starting a session.

**Comment by toji** [comment]
@Maksims: Feels like you comment was intended for #983?

**Comment by pes10k** [comment]
@toji @Manishearth Thank you for both for helping me understand.  Your description sounds great, but I'm having trouble finding that requirement in the spec.  @Manishearth can you kindly point me to the part of the spec that requires / enforces that?

**Comment by Manishearth** [comment]
https://immersive-web.github.io/webxr/#feature-requirements  , local reference spaces in inline sessions require consent.

**Comment by pes10k** [comment]
@Manishearth I appreciate the pointer, but having read through the spec a few times now, I still think this is very unclear.  I'm not trying to pick a fight here, but from reading through this, I don't think that this is going to be clear to anyone not deeply involved in the writing of the spec.  

Also, I know this comment is long, but I'm being as specific as i can to demonstrate that I'm making a sincere, good faith effort to understand the spec and evaluate its privacy implications. I'm not trying to poke holes in the hard work its clear you all have done (which is greatly appreciated).

## Broader "its unclear" concerns

1. [The text you linked to](https://immersive-web.github.io/webxr/#feature-requirements) says consent can be implied / implicit, which does not match my understanding of @toji's comment above, about needing permission to get access to the devices.
2. I can't figure out how the text you linked to integrates into the relevant algorithms (e.g. the "new XR input sources become available" algo, "Each time the list of immersive XR devices changes the user agent should" algo, etc).  More on this below…
3. How does what you linked to interact with the text "The user agent is allowed to use any criteria it wishes to select an immersive XR device…"
4. How does the text you linked to interact [with the text](https://immersive-web.github.io/webxr/#xr-device-concept) "This device MAY be the same as the immersive XR device if one is present, but doesn’t have to be…".

## Specific concerns

### the `requestSession` seems to give access to sensitive device capabilities w/o permission

Specifically, I run into these ambiguities by:
1. Follow the `requestSession` algorithm if `mode=inline` and `options=undefined`
2. For step 4, inline is always allowed (is my understanding), so continue
3. I get to step 5.1. and trying to figure out [the result of obtaining the current device](https://immersive-web.github.io/webxr/#obtain-the-current-device).
4. From here i take the "Otherwise" path to [Inline XR Device](https://immersive-web.github.io/webxr/#inline-xr-device)
5. From here i see that an "inline XR device" is [XR device](https://immersive-web.github.io/webxr/#xr-device) that is a physical device that should report "as much pose information of the physical device the user agent is rendering to as possible".  I'm understanding that the physical device being described at this point is the laptop / desktop / mobile device itself, a point supported by the note that follow.
6. I now continue with the requestSession algo and get to step 5.2.6 and go to the [request xr permission](https://immersive-web.github.io/webxr/#request-the-xr-permission) algo
7. (numbers now reflecting walking through the request XR permission algo) Step 2 seems to refer back to "inline" again here, and the requiredFeatures list seems to be ["viewer"](https://immersive-web.github.io/webxr/#dom-xrreferencespacetype-viewer), as determined by the table with the headings "Feature,Sessions,List".
8. I now go through the process of resolving these `requiredFeatures` (i.e. "viewer") to `consentRequired` features, through the [resolve the requested features](https://immersive-web.github.io/webxr/#resolve-the-requested-features) algo.  "viewer" is not in the table of with the headings "Feature, Feature Policy Required, Consent Required", so step it seems to hit step 7.6 in the "resolve the requested features", and so is granted.
9. Pop back up to the `requestSession` algo, which continues from 5.2.6.  `status` is not denied, so the rest of the algorithm returns a promise with a session initialize with mode=inline and device being the inline device, with the "viewer" feature.
9. The "viewer" feature seems to require a [viewer](https://immersive-web.github.io/webxr/#viewer) of a scene, which requires a XRDevice, which for inline sessions gives access to the gyroscope and accelerometer (re: note in [XR Device](https://immersive-web.github.io/webxr/#xr-device-concept) section).

So it seems like the algorithm either resolves w/o permission, but w/ access to something that will give accelerometer and gyroscope access, _or_ it gives access to some other device (hardware).  Either way, it seems like I can get ungated access to something very sensitive.  (re gyroscope and accelerometer, there has been a lot of work between PING and the Sensor API (and related) specs on how to protect these APIs.  Its important to at the very least mirror those privacy guarantees here.)

### requestSession algo seems inconsistent with above comments

As an additional, distinct concern, it seems like the `requestSession` algo must either succeed, with access given to the described device, or the promise is rejected.  I don't see a path through this algorithm where requestSession succeeds, but access to the device is restricted, which I can't square with https://github.com/immersive-web/webxr/issues/984#issuecomment-599026493 or https://github.com/immersive-web/webxr/issues/984#issuecomment-598474598

### privacy properties seem to bottom out in "user agent will decide"

Finally, related to the above, but distinct, there are several references to obtaining implicit consent, which is an oxymoron and again makes it very difficult to understand what the privacy guarantees of the spec are.  Put differently, it's very difficult to understand from the spec what features / capabilities require explicit (e.g. permission dialog) consent when requested by a website.  This could be solved by stronger text about when "implicit consent" is given; right now it seems to be "user agent decides", which dissolves the privacy guarantees of the spec.

**Comment by Manishearth** [comment]
> the requestSession seems to give access to sensitive device capabilities w/o permission

The flaw in this set of steps is that the viewer space is not enough to obtain the user's pose -- you need _two_ spaces to get a pose value. The only way to get the actual pose of the user is by combining the `viewer` space with some stationary space (typically `local` or `local-floor`), and both require consent for inline sessions. Without these spaces all you can do is relate the `viewer` space with other spaces built on top of the `viewer` space, i.e. a space that's offset from the viewer space (and thus the relative position).

The `viewer` space gives you an abstract handle to the _concept_ of the viewer's position. It does not directly give you access to the viewer's position, you need to relate it with another space to do so.

Inline sessions without additional features are not supposed to give you any access to the device.

> The text you linked to says consent can be implied / implicit, which does not match my understanding of @toji's comment above, about needing permission to get access to the devices.

[Implicit consent is still defined](https://immersive-web.github.io/webxr/#implicit-consent), it allows for cases like when the API is being used by an installed web application, or if consent has already been granted in a previous visit. This text could be improved if you have suggestions.

> How does the text you linked to interact with the text "This device MAY be the same as the immersive XR device if one is present, but doesn’t have to be…".

This is a spec mechanism to allow for cases where you have a 2D browser running on an immersive device, and someone uses an inline session, the underlying device is the same as the immersive one. This way the inline session can use the spatial tracking of the immersive one, but the only time it will need to do that is if you request the `local` feature, which requires consent.

The spec may "use" the immersive device but that doesn't mean the user actually has _access_ to its data.

> I can't figure out how the text you linked to integrates into the relevant algorithms (e.g. the "new XR input sources become available" algo, "Each time the list of immersive XR devices changes the user agent should" algo, etc). More on this below…

It's worth changing the spec to require that XR input sources are masked to just the screen-space input for inline sessions, or require an additional feature to get input controller data. I'm not sure what the best route forward is, this should be filed as a separate issue.

Regarding the `devicechange` event we could potentially allow UAs to disable it by default if they so wish. However, all the `devicechange` event does is tell you that devices were plugged in/out, which is something you can also learn through repeatedly calling `supportsSession()`.

**Comment by toji** [comment]
The various technical details that @Manishearth points out are accurate and reflect our intent in this case, but I think the higher-level point for this issue is that the intent is sprinkled throughout the spec in several different limits that aren't obvious to the outside reader, rather that being clearly stated in a single place. I don't think it's a bad idea to have a paragraph or so that explicitly lays out what you can get from a permissionless `inline` session. Maybe even a non-normative one that uses plainer language (like my initial reply) if we feel that the actual behavioral limits are otherwise well defined.

I'll work on a PR that tries to address everyone's feedback from this thread today.

**Comment by Manishearth** [comment]
Yeah, this would be good.

**Comment by pes10k** [comment]
@Manishearth @toji thank you both for the discussion here.  I'll read the PR ASAP too more fully and and provide feedback on it, but at first glance I have two concerns

### Implicit consent

I see that this is defined, but my concern is that the way its defined is basically "undefined behavior" (e.g. user agent can do whatever).  There is a parallel conversation going on regarding permissions.  I suggest just saying the behavior requires permission via the permission API, and then having the discussion for when / whether the permission from the permission API can be granted w/o explicit user consent as part of the permission group.

More broadly, I'm trying to avoid permission / consent meaning one thing for WebXR functionality, and another thing for some / all other specs.

### sensors

I appreciate the point @Manishearth makes that unpermissioned-sensor access is only granted w/o floor / perspective / orientation information, but:

1. this would seem to undo the protections imposed by recent changes to the Sensor API (which is working towards requiring permissions for accelerometer / gyro / etc), and (
2. just reading this sensor data, w/o ground reference, is enough in some situations to build a unique fingerprint of the user (by teasing out the underlying HW-specific calibration parameters).  PING and the Sensor API folks are working on a solution to this problem too.

So, instead of implementing an alternative path to sensor data, my suggestion / request is to just referencing the existing Sensor API, and inheriting the privacy improvements that are being implemented by those folks

**Comment by Manishearth** [comment]
> More broadly, I'm trying to avoid permission / consent meaning one thing for WebXR functionality, and another thing for some / all other specs.

As far as I understand it all specs dealing with permissions have this level of wiggle room, see [the permissions spec](https://w3c.github.io/permissions/#new-information-about-the-users-intent) for example. It has similar text about implicit signals. We could totally link to that from the webxr spec if you'd like.

> I appreciate the point @Manishearth makes that unpermissioned-sensor access is only granted w/o floor / perspective / orientation information, but:

No, this is not what I've said -- _no sensor access is granted at all_. The "viewer" space on its own does not expose _any_ sensor data. My point about the lack of reference is not about the sensor data only being self-relative, it's that the shape of the API doesn't expose _any_ pose information (absolute or relative) until you have two conceptually distinct reference spaces.

If you want pose information, you need to pass two reference spaces to `getPose()` (or one to `getViewerPose()`, which is equal to `getPose(space, viewer)`). Unpermissioned inline spaces only have `viewer` spaces and spaces defined as constant offsets from viewer spaces. All you can do there is `getPose(viewer, viewer)`, which is identity, or `getPose(offsetViewer, viewer)`, which will give you the constant offset. There is no way to "save" the position of the space in a previous frame and relate it to the current frame to get the relative changes either, since the `getPose` method is defined on the frame itself.

If you're not convinced, I suggest you try and come up with a code example exhibiting this sensor information leak. I feel like you have a misunderstanding as to how various information is exposed in the API.

**Comment by pes10k** [comment]
> As far as I understand it all specs dealing with permissions have this level of wiggle room

We're not disagreeing here.  My request is to not define concepts like implicit / explicit consent in this spec, and to just refer to the permissions API, which can then control when permission is given explicitly / implicitly.

If i'm following correctly, your spec says:

1. Do I have implicit consent?  If so, allow
2. Otherwise, if requires explicit consent, request permission through the permissions API

My request is to just say "ask permission, through the permission API".  The goal being, once a policy for permissions is standardized (in the permissions API) we don't need to go back and revisit every spec that does anything permission-like.

> sensors

I see, thank you for the clarification.  I will read through @toji 's PR carefully and see if it clarifies.  I see on first pass that it specifies / clarifies that the default XRDevice does not give sensor access, which might be the key to defogging my confusion.  I will circle back on this ASAP

**Comment by Manishearth** [comment]
> My request is to just say "ask permission, through the permission API".

That's fair, we actually had our own permissions system until I recently made it use the permissions API, but I kept the concepts of user intent/implicit consent/explicit consent around in the interest of not causing too much churn (and also i couldn't easily find exactly equivalent concepts in the other spec). I'm for collapsing all this down to references to that spec if possible.

**Comment by pes10k** [comment]
Hi all, i see the new PR which clarifies most of the concerns in this issue.  However, the issue of sensor API protections / calling out to that spec doesn't seem to be addressed in the PR.  Would it be more helpful to create a new issue instead?
