### ISSUE TITLE
Need to describe what happens when a non-string object is used as a XRSessionInit.requiredFeatures value

### ISSUE THREAD

**Issue by kearwood** [immersive-web/webxr#994]
It is not clearly defined what should happen when values such as `null`, `nothing`, or objects with a `ToString` function are included within the `XRSessionInit.requiredFeatures` array.

I would like to propose that objects that can be converted to a string, with `ToString` be converted and then compared with the enum values.

For `null` and `nothing`, perhaps they should be ignored without preventing the XRSession from being created?

**Comment by toji** [comment]
Similar to #860, but I think that calling out the non-string scenario specifically is good.

**Comment by Manishearth** [comment]
Yeah, we should probably expand that def to mention null/nothing and ToString things which can be ToStringd
