### ISSUE TITLE
WebXR test suite

### ISSUE THREAD

**Issue by iBicha** [immersive-web/webxr#996]
Would it make sense to create a unified test suite, to validate an implementation?

It would allow different vendors to validate their implementation, and make sure it follow the spec details, and can help detect inconsistencies (either in the implementation, or in the spec itself)

The end goal, is to prevent vendor specific bugs, and user libraries/apps having to implement workarounds. If there's a good time to do this, it's now while the spec is still fresh.

**Comment by jdm** [comment]
Do you mean something different than https://github.com/web-platform-tests/wpt/tree/master/webxr, which is based on https://github.com/immersive-web/webxr-test-api?

**Comment by iBicha** [comment]
Pretty much! I don't know how I missed that. Thanks, closing for now
